citizenfx/fivem

code/Rockerfile
code/tools/ci/build_server_2.sh
code/tools/ci/run.sh

It adds `run.sh` shell script to properly start the FXServer on the Docker built image.

Fix Rocker build for the latest FXServer

---

code/client/clrcore/External/Player.cs
code/client/clrcore/External/World.cs

IsPed is not yet fully implemented (and currently returns false at all times.)
This temporarily disables its use where it's causing issues.

clrcore: fix to ChangeModel and CreatePed always failing

---

code/Rockerfile

It fixes the automated build, however, we still can't remove the testing repository (`edge/testing`) because of `libc++`.
Side note: proot build already use Alpine `3.6`.

Bring back stability to Rocker build

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
ext/natives/codegen_cfx_natives.lua

Renamed `IsVehicleLeftBlinkerActive` and `IsVehicleRightBlinkerActive` to `GetVehicleIndicatorLights`, to match the original native `SetVehicleIndicatorLights` more. Sorry for the quick change, I should've looked that up.
Added `Get/SetVehicleWheelHealth`.

Update vehicle natives

---

code/components/citizen-server-impl/src/GameServer.cpp

As seen here http://upload.boras.org/upload/files/598bd0aeac1b9598bd0aeac257.png

Removing double "Quit:" message

---

data/shared/citizen/scripting/lua/scheduler.lua

Before when the user callback was failing with an error it was keep in the registry,
Not sure if we should do this this way ? or use pcall ?

Avoid keeping callback in registry on error

---

data/shared/citizen/scripting/lua/scheduler.lua

It introduce a cache for the reference of the callback function needed to call an export.
It should reduce latency when using exports function.
This cache is reset each time a resource start to take into account updated functions

Avoid extra call to event system for exports

---

data/shared/citizen/scripting/lua/scheduler.lua

This may help avoiding X messages about the MessagePack error when in fact it's an user error when calling an export

Improve DX when an errors happens on a export

---

data/shared/citizen/scripting/lua/scheduler.lua

Previously when restarting all this exports were reset to nil since the start for others resources were not called.
So i removed the detection of the resource on the cache and only trust the result of the event.

Fix bad cache when restarting a mod

---

code/client/clrcore/InternalManager.cs
code/client/clrcore/RuntimeManager.cs

This pull request prevents several error messages from appearing in the server log. The messages don't seem to make a difference and thus provide no additional information.
I haven't seen anyone else complaing about abstract classes, so I took the liberty to correct this little annoyance. The RuntimeManager would try and create abstract classes, which is not going to work. I added a simple IsAbstract check so this wouldn't happen again. I also merged the if statement to a LINQ statement as this is more neat and reduces nesting.
Plus when starting FXServer one would always see the following exception:
```Failed to get instance for guid a7242855-0350-4cb5-a0fe-61021e7eafaa and iid 567634c6-3bdd-4d0e-af39-7472aed479b7: System.InvalidOperationException: Sequence contains no matching element …
```

Abstract BaseScript support and stacktrace removed for CreateObjectInstance

---

code/components/extra-natives-five/src/PoolTraversalNatives.cpp

When a find handle was made but couldn't find any entities, it left the handle open but returned an invalid handle. Now it simply sets the pool back to nullptr when it fails to get the first entity.

Fix open handles when nothing is found.

---

ext/cfx-ui/src/app/app-nav.component.ts
ext/cfx-ui/src/app/game.service.ts
ext/cfx-ui/src/app/settings/settings.component.html
ext/cfx-ui/src/app/settings/settings.component.ts
ext/cfx-ui/src/assets/locale-en.json

A little update that allow developers use different port. I'm using 33333 port on my local server, so I forced to use Direct connect or console to connect. If "Custom port" is empty, it will use 30120. Also this setting support saving. I don't know can it be useful someone besides me, but still decided to share.

Ability to use specific port for localhost connect

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
ext/natives/codegen_cfx_natives.lua

Continuation of https://github.com/citizenfx/fivem/pull/90, fixing commented issues.
Some notes:
`Get/SetVehicleWheelCamber` was removed in favor of `Get/SetVehicleWheelXrot`. An alias can be added in the future. At that point, I suggest to also alias `Get/SetVehicleWheelXrot` to `*WheelXRot` due to capitalization.
`Get/SetVehicleWheelTrackWidth` was renamed to `Get/SetVehicleWheelXOffset`. While `TrackWidth` is a friendly and familiar name, it is technically not correct as it implies the distance between both wheels on a single axle. Instead, track width can be correctly applied like so:
```lua
function SetVehicleFrontTrackWidth(vehicle, width)
SetVehicleWheelXOffset(vehicle, 0, -width/2)
SetVehicleWheelXOffset(vehicle, 1, width/2)
end
```
Also added a short doc on the natives, including …

Implement Get/SetVehicleWheelXOffset.

---

ext/cfx-ui/src/app/home/home.component.html
ext/cfx-ui/src/app/home/home.component.scss
ext/cfx-ui/src/app/home/home.component.ts
ext/cfx-ui/src/app/home/tweet.service.ts
ext/cfx-ui/src/app/servers/components/servers-detail.component.html
ext/cfx-ui/src/app/servers/components/servers-detail.component.scss
ext/cfx-ui/src/app/servers/components/servers-detail.component.ts
ext/cfx-ui/src/app/servers/components/servers-list-item.component.scss
ext/cfx-ui/src/assets/locale-en.json

Preview: https://imgur.com/a/Dd9dS
An ability to open tweets by clicking detailed date label.
Server refresh button was added to detail page, have 2s timeout to prevent possible spam.
Fixed "favourite" svg button position, now it's looks right on any resolution.
Big server names on server detail page could use ~30% of page on small resolutions. Changed font-size to vh to prevent it.
"Players" panel looks too empty when no players online. Added description text when server is empty to make it looks a bit better

Open tweet, server refresh button, small improvements.

---

code/components/nui-resources/src/ResourceUI.cpp

This is needed when doing a callback from NUI to a script.
The domain name needs to be in all lowercase characters.

fixed issue with callback urls having capitals

---

data/client/citizen/common/data/ui/pausemenu.xml

Added INFO tab to pause menu.
The info tab contains a history of:
- Mission info (subtitles)
- Help (help messages displayed in the top left corner of your screen)
- Notifications (displayed above the minimap)
This is, for example, useful for developers wanting to create "missions" and have a log of instructions available in case the user wants to re-view the mission instructions after a notification/help message/subtitle is gone.
Looks like this:

Added INFO tab to pause menu.

---

code/Rockerfile
code/tools/ci/build_server_2.sh

It fixes docker builds:
* Alpine 3.7 is needed to use the cfx repo (added for v8)
* icu-libs is needed by libv8

Add compat for v8/node to Docker builds

---

ext/natives/codegen_dlc_natives.lua
ext/natives/natives_stash/gta_universal.lua

Changed some types according to the functions found in `gb_headhunter`
Changed the documenation of `_SCREEN_DRAW_POSITION_BEGIN` to properly reflect how it is working. So people can actually use it.
The parameter values were gained by bruteforce testing values from 0 - 255. I have no understanding of why or how they actually come to be.

Updated some native parameters + docs

---

ext/ui-build/data/root.html

With this function you can get frame's parent resource. This can be useful for resources that sending data from NUI to client. Without it you will be forced to hardcode resource name in post's url.
Example code:
`const name = GetParentResourceName();
$.post("http://" + name + "/test", JSON.stringify(data));`
Tested with vrp, wk_actionmenu and few other resources from the forum.

GetParentResourceName function for NUI frames

---

code/components/nui-resources/src/ResourceUIScripting.cpp
ext/natives/codegen_cfx_natives.lua

With this function you can get NUI's cursor position (x, y) from client scripts.
`void GET_NUI_CURSOR_POSITION(int *x, int *y)`
Usage example: https://hastebin.com/ikepijohux
Demonstration: https://gfycat.com/HonoredAmbitiousDwarfrabbit

Added NUI's cursor position getter

---

code/client/clrcore/Debug.cs

* This is to match the behavior of System.Diagnostics.Debug.WriteLine which doesn't try to format the string unless you provide additional arguments. This was causing errors if you had unescaped curly brackets in your string and were expecting the System.Diagnostics.Debug.WriteLine behavior. e.g. `Debug.WriteLine("{test}")`
This resolves issues like this https://forum.fivem.net/t/c-debug-writeline-without-parameters-still-tries-to-format-the-string/97667

clrcore: Adds Debug.WriteLine overload without formatting arguments

---

code/client/clrcore/RemoteFunctionReference.cs

* The error parameter will be missing from the array when there is no error.
This fix allows you to use networked callbacks in C#. You just need the lua sessionmanager resource running. Also for the example below you also need an empty lua client_script inside the sessionmanager. Since the callbacks are handled via scheduler.lua when the resource name is sessionmanager.
```
class ClientScript : BaseScript
{
public ClientScript()
{
TriggerServerEvent("SomeEvent", new Func<int, int>((arg) =>
{
return arg * 2;
}));
}
}
class ServerScript : BaseScript
{
public ServerScript()
{
this.EventHandlers.Add("SomeEvent", new Action<dynamic>(OnSomeEvent));
}
private async void OnSomeEvent(dynamic cb)
{
var val = await cb(10);
Debug.WriteLine("new val: " + val);
}
}
```

clrcore: Fixes remote function index out of bounds exception

---

ext/cfx-ui/src/assets/locale-en.json

As mentioned in #98, you don't want to remove the "Ошибка". And that's OK. But on the other hand it decreases the usability of this statement. So I thought that a good way will be not touching the word "Ошибка" and leaving it as it is, and adding next to it an English "Error" in brackets.
Case 1: Someone understands the meaning of "Ошибка", so he reads it and moves his eyes below, to the description. Without paying attention to what is in brackets.
Case 2: Someone doesn't understand the meaning of "Ошибка", so he reads it and thinks "What's this?? Idk. Maybe it's a mistake in translation. Anyway, let's continue reading.", then he moves his eyes to the next word, which is in brackets – "Error". He understands it, so he moves his eyes below, to the description.
I think this is a good …

Addition of "Error" in brackets next to "Ошибка"

---

code/components/citizen-scripting-mono/src/MonoComponentHost.cpp

Small PR to fix linux build.
MonoGCEvent was refactored to MonoProfilerGCEvent since mono-5.8.0.103 (https://github.com/mono/mono/commit/ea4e4a9ef6fc42570a23026adbe826cf7248290e)

citizen:scripting:mono: use new profiler API

---

code/components/http-client/src/HttpClient.cpp

* This specifically would happen when closing the dialog after trying to connect to a server that isn't online.
This fixes the si-680d1ad23f4a42eca4195bac5be60f3b crash.

http-client: fixes crash when closing the connection failed, failed handshake dialog

---

data/shared/citizen/scripting/v8/timer.js

this fixes errors like `Unhandled error TypeError: Cannot read property '_destroySSL' of undefined`, this error was being thrown because https://github.com/citizenfx/node/blob/93ebc8f2c1af6818bc7c94bdb65671a55ae523e5/lib/_tls_wrap.js#L407
was passing "this" as an argument to setImmediate, but setImmediate wasn't passing the argument along to the destroySSL function.

Fix Unhandled TypeError error (add ability to pass arguments to setImmediate and setTimeout callbacks)

---

code/components/discord/src/DiscordPresence.cpp
ext/natives/codegen_cfx_natives.lua

this is useful for people who want to change fivem's rich presence image, it can be set from scripts using natives and also from the CitizenFX.ini file (DiscordId and DiscordImage)
P.S. this is my real first time doing anything with cpp, i have probably overcomplicated some things, if you'd like for me to change anything, just review the commit and i will try my best to fix it :)

discord: add ability to use custom applications for Rich Presence

---

.travis.yml

Travis builds are triggered by tag and git does not store the branch from which a commit was tagged.
This finally fix the FXS version for travis builds.
Old (wrong) version:
```json
"server": "FXServer-v1.0.0.750 940 linux"
```
new one:
```
"server": "FXServer-master v1.0.0.750 linux"
```

ci: fix travis git env variables

---

data/shared/citizen/scripting/v8/console.js

this didnt seem to be fixed with commit 15fd5d3eeaf687544ed5c64e1dc721bab6c04914 which was fixed only null values, leaving undefined values unhandled.

v8: fix console failing on undefined values

---

code/client/clrcore/External/Weapon.cs
code/client/clrcore/External/WeaponCollection.cs

`HAS_PED_GOT_WEAPON` has 3 parameters: `Ped`, `WeaponHash`, `bool`. The 3rd parameter is always false. This should fix `WeaponCollection#HasWeapon(WeaponHash)` from always returning false.

clrcore: Add missing parameter in HAS_PED_GOT_WEAPON calls

---

code/client/clrcore/External/Model.cs

Checks the enum values to see if the model hash matches that of any defined in `PedHash`. Not the most dynamic solution (i.e. addon ped models will still return false), but better than always returning `false`.

clrcore: Fix Model.IsPed always returning false

---

code/client/clrcore/External/World.cs

- Reduces the amount of native calls
- Higher Accuracy:
```C#
var pointA = new Vector3(0f, 0f, 0f);
var pointB = new Vector3(1000f, 1000f, 1000f);
GET_DISTANCE_BETWEEN_COORDS(pointA.X, pointA.Y, pointA.Z, pointB.X, pointB.Y, pointB.Z, 1):
1732.051
Math.Sqrt(pointB.DistanceToSquared(pointA)):
1732.05080756888
```

clrcore: Change GetDistance method from native call to Vector3 euclidean distance method

---

data/client/citizen/common/data/ui/pausemenu.xml

Disable the ped info for custom frontend menus (CORONA_), this does not remove the ped info from the normal pause menu.
Before https://www.vespura.com/hi/i/2018-11-08_12-00_32792_208.png
After: https://www.vespura.com/hi/i/2018-11-08_12-24_5f58b_209.jpg

Disable the ped info for custom frontend menus (CORONA_), this does not remove the ped info from the normal pause menu.

---

code/components/discord/src/DiscordPresence.cpp

This adds more functionality and flexibility for users to use Discord Rich Presence. They can now set a small "badge" as well as hover text for each image. By default, these three additions are empty.
**Small Image Asset**
Native: _SET_DISCORD_RICH_PRESENCE_ASSET_SMALL_
**Large Image Asset Hover Text**
Native: _SET_DISCORD_RICH_PRESENCE_ASSET_TEXT_
**Small Image Asset Hover Text**
Native: _SET_DISCORD_RICH_PRESENCE_ASSET_SMALL_TEXT_

Discord: Add ability to add a small image asset as well as set hover …  …text for small and large image assets.

---

code/client/clrcore/External/World.cs

I realized that clrcore was missing marker types after the natives documentation was updated. 
See https://github.com/citizenfx/natives/commit/dce7ff110d194c961720632ba6488ab63e5aa3f0
This adds the missing marker types to the `MarkerType` enum of clrcore.
Added types:
* DollarSign
* HorizontalBars
* WolfHead
* QuestionMark
* PlaneSymbol
* HelicopterSymbol
* BoatSymbol
* CarSymbol
* MotorcycleSymbol
* BikeSymbol
* TruckSymbol
* ParachuteSymbol
* SawbladeSymbol

clrcore: Updated MarkerType enum to reflect changes to natives documentation

---

data/shared/citizen/scripting/v8/timer.js

As a follow up to https://github.com/citizenfx/fivem/pull/171#issuecomment-453018520
This PR introduces:
1. New global function `clearTick` that you can use to halt your ticker execution, accept `tickerId` return from `setTick`.
2. Runtime will now wait for ticker to resolve (if it returns a promise, e.g. is async function) before firing it again.
The latter, *possibly*, can break backwards compatibility, but doubtfully that anyonehas been relying on old behavior, thus I believe we can safely assume previous behavior as a bug and just fix it.
```js
setTick(async () => {
// Previously this whole ticker would fire on each tick and spawn new promise each time
// In this PR runtime won't call this ticker again until it got resolved
await longTakingOp();
});
```

citizen:scripting:v8 add clearTick and waiting for ticker to resolve

---

docs/building.md

Fixed assumption that the developer wishing to build has MSYS2 already. This is not always the case.

Fixed Environmental Assumption

---

code/vendor/node.lua

~It's better to have a slow build for a while rather than nothing~
Edit: fixed the issue with a premake filter
Generated Makefile part:
```makefile
../../../../vendor/node/src/node_javascript.cc: ../../../vendor/node_js2c.py
$(SILENT) python /src/code/vendor/node_js2c.py /src/vendor/node
$(OBJDIR)/node_javascript.o: ../../../../vendor/node/src/node_javascript.cc
@echo $(notdir $<)
$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
```
Generated vcxproj:
```vcxproj
<ItemGroup>
<ClCompile Include="..\..\..\..\vendor\node\src\node_javascript.cc" />
</ItemGroup>
<ItemGroup>
<CustomBuild Include="..\..\..\vendor\node_js2c.py">
<FileType>Document</FileType>
<Command>python /src/code/vendor/node_js2c.py /src/vendor/node</Command> …
```

build: fix node prebuild command

---

code/client/clrcore/External/Game.cs
code/client/clrcore/External/MpPedDataStructs.cs

Add a `AltPropVariationData` struct, and `Game.GetAltPropVariationData()` function.
These are used to get the alternate component for things like helmets with goggles/visors. One being the toggled up version, and the other being the toggled down version. Including prop texture variant.

Add more MP character data structs

---

code/client/clrcore/External/Game.cs
code/client/clrcore/External/Weapon.cs
code/client/clrcore/External/WeaponComponent.cs

Add 2 new weapon struct native wrappers
- `Game.GetWeaponHudStats()`
- `Game.GetWeaponComponentHudStats()`
Struct info: 
```cs
int hudDamage, int hudSpeed, int hudCapacity, int hudAccuracy, int hudRange
```
Used for things like [this](https://d.fivem.dev/2019-03-24_23-54_9eb75_976.gif).

Add 2 new weapon struct native wrappers

---

code/client/clrcore/InternalManager.cs

This error tends to just cause confusion since I18N is an optional library. This does suppress the error message when attempting to load I18N. I'm fine with changing this to a print out "Exception loading assembly I18N". However the full stack trace is where I think the confusion comes from. Also the change to a NotImplementedException will make sure this error only shows up once.

clrcore: Disable I18N and suppress error if I18N isn't found

---

code/client/launcher/UpdaterUI.cpp

The UpdateUI is not correctly scaled by the DPI setting, so the window may be clipped and the text is too small in the HiDPI environment (mine is 200%), looking like:
My patch fixes this problem, making both non-client and client area scaled properly:
This patch also responds to WM_DPICHANGED message, so the window and the text and button on it will be correspondingly scaled once the DPI is changed.
What it looks like under 200%:
... and what it looks like under 150% after WM_DPICHANGED is processed:

Fix DPI scale issue in UpdateUI

---

code/components/gta-core-five/component.json
code/components/gta-core-five/src/SetCursorLocation.cpp
code/components/rage-input-five/include/InputHook.h
code/components/rage-input-five/src/InputHook.cpp

Wasn't sure the best place to put the native override, so let me know if it should be placed elsewhere or if another approach should be taken to fix SetCursorLocation.

rage:input/gta:core: fixes SetCursorLocation native by temporarily re-enabling SetCursorPos during native invocation

---

code/components/handling-loader-five/src/HandlingLoader.cpp

set: Fixed condition that wouldn't have allowed to set 0.9f as value
get: Changed logic to match the one used for the set
fDriveBiasFront and +4 (fDriveBiasRear) are either one 1.0f and the other 0.0f or both are a value among 0 and 1 (whose sum is 1.0f) but stored doubled

handling-loader-five: Fix for fDriveBiasFront get/set

---

code/components/gta-streaming-five/src/PopulationCreationHooks.cpp

An additional parameter was added to GTA's createPopulationPed at some point. You can see an example of it being passed at 0x1406DB35B.

gta-streaming-five: fixes g_createPopulationPed parameter count

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp

Both CFX and VEHICLES namespaces have a native called GET_VEHICLE_ACCELERATION so I've changed the name for the extra-native and on purpose didn't add an alias.

Rename vehicle extra-native which somehow has the same name of a native

---

code/client/clrcore/External/World.cs

`IntersectOptions` is considered a bit flag according to the [documentation](https://runtime.fivem.net/doc/natives/#_0x377906D8A31E5586). This change just properly adds the `Flags` attribute to the enum so it could have bit operations done on it without warnings.

clrcore: Add Flags attribute to IntersectOptions

---

data/client/citizen/common/data/gameconfig.xml

I experienced error messages in log and even crashes due to CNetworkRopeWorldStateData limit (20) and other players reported to me too.
This is not my log, but it shows the problem: https://pastebin.com/9bzRENKD

Increased CNetworkRopeWorldStateData limit

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
code/components/handling-loader-five/include/HandlingLoader.h

Commit has only been tested locally, and may be programmed a bit too
defensively.

handling-loader-five: fix vehicle handling memleak

---

code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp

Tested and working properly.
I did not added `GET_PED_CAUSE_OF_DEATH` because for some unknown reason the returned value in the synctree does not match what should be returned even though the order seems fine.
I get 1891351 instead of 3452007600 for `weapon_fall`

onesync: complete CPedHealthDataNode

---

ext/natives/codegen_out_js.lua
ext/natives/codegen_out_lua.lua

Example returns:
```js
* @return 0 = None
*      1 = Unlocked
*      2 = Locked
*      3 = Locked for player
*      4 = Stick player inside (Doesn't allow players to exit the vehicle with the exit vehicle key.)
*      7 = Can be broken into (Can be broken into the car. If the glass is broken, the value will be set to 1)
*      8 = Can be broken into persist
*      10 = Cannot be tried to enter (Nothing happens when you press the vehicle enter key).
```
```lua
-- @return 0 = None
--      1 = Unlocked
--      2 = Locked
--      3 = Locked for player
--      4 = Stick player inside (Doesn't allow players to exit the vehicle with the exit vehicle key.)
--      7 = Can be broken into (Can be broken into the car. If the glass is broken, the value will be set to 1)
--      8 = Can be broken into …
```

ext/natives: js/lua multi-line return types

---

.travis.yml
code/Rockerfile
code/tools/ci/build_server_2.sh

Using 24 job slots for Travis is inefficient and uses too much RAM.

build/linux: set the number of job slots

---

data/shared/citizen/scripting/v8/console.js

This will prevent `Converting circular structure to JSON` error when calling `console.dir()`.

prevent circular reference error in console.dir()

---

code/components/extra-natives-five/src/InterfaceExtraNatives.cpp

This natives will allow people to edit mapzoomdata.meta info in runtime. Which adds an ability to use a hacky way to stream maps from the server. Since there's no any other way to do that atm (and I'm not able to do something better), I decided to PR this. However, I did this because I actually wanted to edit zoomlevels :P Not sure if this PR is ready to production so I'm open to suggestions.
https://gfycat.com/wateryecstaticdungbeetle
https://github.com/citizenfx/natives/pull/171

Implement new MapZoomData natives

---

code/components/extra-natives-five/src/TimeExtraNatives.cpp

This native is allowing to set what is game minute in real milliseconds. Default is 2000 (real ms) per 1 in-game minute. For example, changing value to 1000 will speed up in-game clock in 2 times.
https://gfycat.com/ColdGregariousBrant
https://github.com/citizenfx/natives/pull/175

Native for overriding ms per game minute value

---

ext/natives/codegen.lua
ext/natives/codegen_out_cs.lua

Handles, for example, ``<param name="value">`` while the function is parameterized as ``_value``

ext/natives: ensure langwords are handled in docs

---

code/client/launcher/Bootstrap.cpp

This fixes losing cmdline args, such as +connect, when the client updates.

Fix: cmdline args were not passed when bootstrapping

---

code/components/gta-streaming-five/src/PatchWeaponLimits.cpp
data/client/citizen/common/data/gameconfig.xml

This PR is increasing weapon components pool (CWeaponComponentInfo) limit to 1024 (configurable).
P.S. - Жожа, привет.

Patch weapon components limit

---

data/client/citizen/common/data/gameconfig.xml

This increases MaxVehicleModelInfos from 620 to 1024 and MaxExtraVehicleModelInfos from 1024 to 2048 so more vehicles can be streamed.

gameconfig: increase MaxVehicleModelInfos

---

docs/building.md

As premake5 is included with ci tools (for build.ps1) it is no longer needed to download it separately

Updated building.md

---

code/components/citizen-server-monitor/src/MonitorInstance.cpp

This is necessary due to the fact that `trace()` is async and its possible for resources to send sync messages, effectively cutting this message in half.

Removed second monitor mode banner message

---

code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp

Useful for some server/entities stuff.
`HAS_VEHICLE_BEEN_OWNED_BY_PLAYER`
`HAS_ENTITY_BEEN_MARKED_AS_NO_LONGER_NEEDED`
This one only works with vehicle since ped/object game state nodes still need to be made.

server/onesync: three new 'state' natives

---

data/client/citizen/common/data/gameconfig.xml

This increases FragmentStore from 24000 to 48000 so more vehicle modkits can be streamed.

gameconfig: increase FragmentStore

---

code/components/citizen-legacy-net-resources/src/ResourceNetBindings.cpp
code/components/citizen-server-impl/src/ServerResources.cpp

This fixed the bug causing latent events' name to stick around after using a longer name

Added null-terminator to end of event name for latent events

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp

Added:
```c
float GetVehicleWheelTireColliderSize(Vehicle vehicle, int wheelIndex);
float GetVehicleWheelTireColliderWidth(Vehicle vehicle, int wheelIndex);
float GetVehicleWheelRimColliderSize(Vehicle vehicle, int wheelIndex);
void SetVehicleWheelTireColliderSize(Vehicle vehicle, int wheelIndex, float value);
void SetVehicleWheelTireColliderWidth(Vehicle vehicle, int wheelIndex, float value);
void SetVehicleWheelRimColliderSize(Vehicle vehicle, int wheelIndex, float value);
```
Those natives will work well with previously added visual wheel size/width SETTERS.
PR in natives repo for those natives: https://github.com/citizenfx/natives/pull/252

extra-natives/five: +GET/SET wheel collider stuff

---

code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp

1) Fixed `GET_ENTITY_ROTATION` and `GET_ENTITY_HEADING` when target entity is a ped/player. (https://forum.cfx.re/t/getentityheading-doesnt-work-on-server-side/1056285)
2) Changed `GET_ENTITY_HEADING` bounds from `-180f -> 180f` to `0f -> 360f` since clientside native uses that.
3) Added `GET_PED_DESIRED_HEADING` native.

Improvements in rotation/heading serverside natives

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp

Fixes regressions introduced in https://github.com/citizenfx/fivem/pull/397
https://forum.cfx.re/t/getvehiclecurrentrpm-not-working-since-last-client-update/1093214
Related natives:
```cpp
GET_VEHICLE_CURRENT_ACCELERATION
GET_VEHICLE_CURRENT_RPM
SET_VEHICLE_CURRENT_RPM
```

Fix oversight in acceleration and current rpm offsets

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp

Fixes another regressions introduced in https://github.com/citizenfx/fivem/pull/397
https://forum.cfx.re/t/isvehicleenginestarting-native-always-returns-false-after-update/1094110
Related natives:
```cpp
IS_VEHICLE_WANTED
IS_VEHICLE_ENGINE_STARTING
```

Fix oversight in IsEngineStarting offset

---

code/components/extra-natives-five/src/DensityNatives.cpp

`GET_RANDOM_VEHICLE_DENSITY_MULTIPLIER` is using the same address as `GET_VEHICLE_DENSITY_MULTIPLIER`
https://github.com/citizenfx/natives/pull/271

Add getters for density natives

---

code/components/gta-net-five/src/MumbleVoice.cpp
code/components/voip-mumble/include/MumbleClient.h
code/components/voip-mumble/include/MumbleClientImpl.h
code/components/voip-mumble/include/MumbleClientState.h
code/components/voip-mumble/src/MumbleClient.cpp
code/components/voip-mumble/src/MumbleClientState_User.cpp

Re-referenced to https://github.com/citizenfx/fivem/pull/404 with the requested changes. 
Couldn't get it to rebase properly.

Mumble volume override by server ID

---

code/components/gta-net-five/src/MumbleVoice.cpp
code/components/voip-mumble/include/MumbleClient.h
code/components/voip-mumble/include/MumbleClientImpl.h
code/components/voip-mumble/include/MumbleClientState.h
code/components/voip-mumble/src/MumbleClient.cpp
code/components/voip-server-mumble/component.json
code/components/voip-server-mumble/include/ServerMumbleVoice.h
code/components/voip-server-mumble/src/ServerMumbleVoice.cpp

`MUMBLE_CREATE_CHANNEL` is a server-side native to create persistent mumble channels.
This would make the "grid channels" better as you do not have to worry about non-existing channels.

mumble: implement new natives

---

code/components/citizen-resources-gta/src/TextChangingFunctions.cpp
code/components/gta-core-rdr3/include/CustomText.h
code/components/gta-core-rdr3/src/CustomText.cpp

Backported code allowing people to use `ADD_TEXT_ENTRY` and `ADD_TEXT_ENTRY_BY_HASH` natives in RedM.

Text natives for RedM

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp

This fixes the crash when GetHashKey gets called with a nil value on the server side.

fix: GET_HASH_KEY crash on server with null value

---

code/components/font-renderer/src/GtaGameInterface.cpp

- Adjust the position of the emoji to always be in the corner of the screen.
- Adjust the alpha channel of the text color. I feel like it's much more soft and nicer on the eyes.

Adjust position of emoji on left-side of screen; Adjust alpha color of text

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp

Change how entities are iterated through in the main thread loop to improve performance. See commit for more details.

[OneSync] Improve entity iteration logic

---

docs/building.md

Yarn & NodeJS are required to generate natives docs

docs: building update requirements

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp

When the first set of ifs are true, checking g_entityCreationList
can be skipped as the result will not be changed.
Second if changed to direct return instantly breaks out of the loop.

Optimize ValidateEntity function

---

ext/native-decls/GetVehicleWheelRimColliderSize.md
ext/native-decls/GetVehicleWheelSize.md
ext/native-decls/GetVehicleWheelTireColliderSize.md
ext/native-decls/GetVehicleWheelTireColliderWidth.md
ext/native-decls/GetVehicleWheelWidth.md
ext/native-decls/SetVehicleWheelRimColliderSize.md
ext/native-decls/SetVehicleWheelSize.md
ext/native-decls/SetVehicleWheelTireColliderSize.md
ext/native-decls/SetVehicleWheelTireColliderWidth.md
ext/native-decls/SetVehicleWheelWidth.md

This removes useless aliases for these extra natives
* [GetVehicleWheelWidth](https://github.com/citizenfx/fivem/blob/master/ext/native-decls/GetVehicleWheelWidth.md)
* [GetVehicleWheelSize](https://github.com/citizenfx/fivem/blob/master/ext/native-decls/GetVehicleWheelSize.md)
* [GetVehicleWheelTireColliderWidth](https://github.com/citizenfx/fivem/blob/master/ext/native-decls/GetVehicleWheelTireColliderWidth.md)
* [GetVehicleWheelTireColliderSize](https://github.com/citizenfx/fivem/blob/master/ext/native-decls/GetVehicleWheelTireColliderSize.md)
* [GetVehicleWheelRimColliderSize](https://github.com/citizenfx/fivem/blob/master/ext/native-decls/GetVehicleWheelRimColliderSize.md)
* [SetVehicleWheelWidth](https://github.com/citizenfx/fivem/blob/master/ext/native-decls/SetVehicleWheelWidth.md) …

native-decls: remove useless aliases

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp

Seems to work fine when tested with 2 players.
Example usage:
```lua
AddEventHandler("clearPedTasksEvent", function(sender, data)
print(sender, GetPlayerName(sender), json.encode(data))
-- 128, SloPro, { "pedId": 1, "unk1": true }
end)
```
Can be cancelled to prevent syncing.

onesync: add CClearPedTasksEvent server event

---

code/client/citicore/StructuredTraceImpl.cpp
code/shared/StructuredTrace.h

Possibly standardize this across all nlohmann::json::dump invocations? e.g., citizen-game, etc.
Initially reported by Willemde20

fix: gracefully handle invalid UTF-8 sequences

---

code/components/gta-net-five/src/MumbleVoice.cpp
ext/native-decls/MumbleIsConnected.md
ext/native-decls/MumbleSetServerAddress.md

This has been tested with the mumble server component removed and using two external grumble servers

feat(mumble): support external voice server

---

code/components/gta-core-rdr3/src/GameReloading.cpp

This should fix a disconnection crash introduced in a 1311.12 port.

Fix RedM game reloading crash

---

ext/ui-build/data/root.html

This will only re-focus if we tabbed to the body element, and not a child iframe.

fix(nui): only refocus iframe if we are in the parent body

---

ext/cfx-ui/src/app/servers/connecting-popup.component.ts

This typo shows up when joining a server using `fivem://connect/cfx.re/join/{token}`.
Example:

Fix a typo on the UI

---

code/client/clrcore/BaseScript.cs
code/client/clrcore/External/Entity.cs
code/client/clrcore/External/Player.cs
code/client/clrcore/Server/Entity.cs
code/client/clrcore/Server/ServerWrappers.cs
code/client/clrcore/StateBag.cs

Based on lua:
```cs
// Server
Ped ped = Players[source].Character;
ped.State["test"] = new { ok = "yes" };
GlobalState["mode"] = "open";
// Client
Ped ped = LocalPlayer.Character;
Debug.WriteLine("test:" + ped.State["test"].ok);
Debug.WriteLine("mode:" + GlobalState["mode"]);
// Set allows replicating from client to server
ped.State.Set("test", new { ok = "set from client" }, true);
```

"State bag" support for C#

---

data/client_rdr/citizen/common/data/control/settings.meta

Some controls was removed from settings.meta for specific contexts when RedM was updated to 1311.12. To keep a backward compatability we adding these controls back.

Add removed controls back for RedM

---

data/client/citizen/common/data/gameconfig.xml

A few months back I hit this limit with a bunch of models with cloth physics (yld files) seems I am back at that roadblock again (this time with only 4 models that have cloth physics). The current value of 60 does seem a bit low so increasing this doesn't seem to do much harm at 600. Probably can be tweaked in the future if necessary.
(redid this PR because the last one was absolutely horridly confusing)

Increase "ClothStore" poolsize from 60 to 600

---

code/components/citizen-resources-client/src/ResourceCacheDeviceV2.cpp

hacky way to prevent cache device looping and exiting after 4 times since it doesn't have a reference hash:)

temporary fix for REGISTER_SOMETHING_FROM_URL native

---

code/components/extra-natives-five/src/PlayerNatives.cpp
code/components/extra-natives-five/src/TimeExtraNatives.cpp

Fixes `SET_MILLISECONDS_PER_GAME_MINUTE` and `GET_PLAYER_WEAPON_DEFENSE_MODIFIER`, as promised.

Update some extra-natives patterns for b2060

---

code/components/extra-natives-five/src/InteriorExtraNatives.cpp

TLDR: R* added some weird flag field into CInteriorProxy class struct which is moved interior inst pointer to +8 bytes (flag + 4 bytes of padding), they also removed 8 bytes of padding after inst pointer field, so other interior proxy fields wasn't affected. 
Also contains various small fixes such as:
- Fixed an issue when missing proxy->inst->mloModel caused native execution failures.
- Better structs.
- Fixed typos.

Fix interior extra natives for b2060

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
code/components/gta-streaming-five/src/UnkStuff.cpp
ext/native-decls/ResetFlyThroughWindscreenParams.md
ext/native-decls/SetFlyThroughWindscreenParams.md

Preview: https://gfycat.com/tautgenerousfiddlercrab
Changed params: https://gfycat.com/lametemptingiberiannase
Can be disabled using `SET_PED_CONFIG_FLAG` and 32 flag set to false.
Natives:
```cpp
BOOL SET_FLY_THROUGH_WINDSCREEN_PARAMS(float vehMinSpeed, float unkMinSpeed, float unkModifier, float minDamage);
void RESET_FLY_THROUGH_WINDSCREEN_PARAMS();
```

Patch fly through windscreen in netgames + extra natives

---

code/components/gta-net-five/src/MumbleVoice.cpp

add audio context native using server player id instead of client player id as argument

add GET_AUDIOCONTEXT_FOR_SERVERID as per GET_AUDIOCONTEXT_FOR_CLIENT

---

code/components/gta-net-five/src/MumbleVoice.cpp

GetPlayerNameFromServerId already has the correct format for GetAudioContext and does not need formatted

fix double server id in getAudioContextByServerId

---

code/components/extra-natives-five/src/VisualSettingsNatives.cpp
code/components/extra-natives-rdr3/component.lua

This PR backporting `SET_VISUAL_SETTING_FLOAT` native from FiveM to RedM.

Visual settings overriding native for RedM

---

code/components/gta-net-five/src/MumbleVoice.cpp
code/components/voip-mumble/include/MumbleClient.h
code/components/voip-mumble/include/MumbleClientImpl.h
code/components/voip-mumble/src/MumbleClient.cpp
ext/native-decls/MumbleSetAudioInputDistance.md
ext/native-decls/MumbleSetAudioOutputDistance.md

Allows to individually set Mumble's input / output distance since `NetworkSetTalkerProximity` forces both to be on the same distance. This shall allow players to talk in a different distance than what they can hear (useful for roleplay proximity voice so for example people can whisper but still hear people shouting in a distance).

feat: MUMBLE_SET_AUDIO_OUTPUT_DISTANCE & MUMBLE_SET_AUDIO_INPUT_DISTANCE

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/InitConnectMethod.cpp
code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
code/components/citizen-server-impl/src/state/ServerRPC.cpp
vendor/citizen_util/include/citizen_util/shared_reference.h

Required client changes were added in the following commits already:
* 13180f79624f47b5760ad9dcdd27c60166a7a248 (feat(onesync): NAK rewrite, initial client patchset)
* 4ae35f223b56125b0e38216df2dd642abda035a4 (fix(onesync/client): fix some cases of 0-length node writes in WriteTreeCfx)
Server-side logic is pending some testing by users, but here's a summary:
* No more automatic repeat request (ARQ), clients will explicitly request a resend of a full packet, or of a certain entity's state.
* A number of tweaks and bug fixes related to this, such as:
* ServerRPC null pointer check (might be able to be moved out?)
* World grid 'cooldown' timer, to prevent population spawning before a client can be made aware of what's going on around them.

feat(onesync): NAK rewrite, server side

---

code/components/net-base/src/NetAddress.cpp

Resource HTTP handlers don't work on IPv6 without this.
https://github.com/citizenfx/fivem/blob/4c14df4db47d77d97918921d2a56a8c69664684b/code/components/citizen-server-impl/src/ResourceHttpHandler.cpp#L92-L100

fix(net): IPv6 support for 'NoResolution' lookup type when resolving peer addresses

---

code/components/gta-net-five/src/MumbleVoice.cpp

instead of false when player get suddenly disconnected and cannot reconnect. e.g. murmur server is down

(voip/mumble): fix MumbleIsConnected returning 1

---

prebuild_natives.cmd

Using a custom LUA_CPATH which doesn't search the current directory would break the prebuild script.

Fix(prebuild): Clear LUA_CPATH

---

ext/natives/codegen_out_dts.lua

This fixes native typing TS documentation:
Sample natives that has this issue:
https://runtime.fivem.net/doc/natives/?_0x2975C866E6713290
GetEntityPlayerIsFreeAimingAt
```
// GetEntityPlayerIsFreeAimingAt
BOOL GET_ENTITY_PLAYER_IS_FREE_AIMING_AT(Player player, Entity* entity);
/**
* Returns TRUE if it found an entity in your crosshair within range of your weapon. Assigns the handle of the target to the *entity that you pass it.
* Returns false if no entity found.
*/
declare function GetEntityPlayerIsFreeAimingAt(player: number, entity: number): number;
```
Other examples, just runtime links:
https://runtime.fivem.net/doc/natives/?_0x2E1202248937775C
https://runtime.fivem.net/doc/natives/?_0xDC16122C7A20C933
As you can see natives that has pointers in the declaration, are supposed to be …

Fix codegen for TS for natives that return values by pointers

---

code/client/clrcore/ClientScript.cs
code/client/clrcore/InternalManager.cs
code/client/clrcore/ServerScript.cs

```
This change adds ClientScript and ServerScript classes that are present
in the respective environments to differentiate client and server sided
scripts. This also allows the C# and F# compilers to unambiguously link
against the correct libraries when referencing both assemblies.
In addition, we handle an exception that is thrown when loading types
with missing assemblies, e.g. ServerScript is missing on the client.
See https://forum.cfx.re/t/2006775
```

feat(clr): add ClientScript and ServerScript, allow missing types

---

ext/cfx-ui/src/app/settings/settings.component.scss

Noticed the lack of margin for the `fa-road` icon here, it uses `fa`, not `fab`, so that's why the `margin-right` doesn't get applied.
Before:
After:

fix: applies the same margin-right to 'fa' as 'fab'

---

ext/cfx-ui/src/app/settings.service.ts

- Fixes the 'show streaming progress' setting displaying as off when actually enabled
~~- Changed the way default values are set in `DisplaySetting` so that the low-performance mode correctly shows as 'off' by default.~~ _Just realised what I did is a complete non-solution so I've reverted it_

Small fixes in the settings menu

---

code/client/citicore/console/Console.Variables.cpp

SetValue triggers this event before the convar is registered, so it can't be found and the SendConvar call is skipped.
https://github.com/citizenfx/fivem/blob/34069da52f788a6e21c7ae2e9fc6d84dda932abe/code/components/nui-core/src/NUIConsole.cpp#L41-L49
This results in convars not being sent to the NUI when first created, unless this call in the UI happens *after* their creation. https://github.com/citizenfx/fivem/blob/446cb2c9d640a3bf1954caeec83a1ef8a2ae028b/ext/cfx-ui/src/app/game.service.ts#L328
This happens occasionally but not most of the time. Convars such as `ui_streamerMode` which are created by `seta` in fivem.cfg often don't reach the UI (unless they're modified again). Hence the bug described here https://forum.cfx.re/t/convar-ui-blurperfmode-is-not-honored-on-launch-and-blur-effe …

fix(console): register new variables before setting their value in the set command

---

code/client/clrcore/Server/Entity.cs

Fixes invalid player returned when in an unowned state

tweak(scripting/clr): unowned entities have no owner

---

code/client/clrcore/Server/ServerWrappers.cs

IPv6 addresses are incorrectly extracted as they contain `:`, examples:
- `ip:[::ffff:127.0.0.1]` extracts as `127.0.0.1]`
- `ip:[::1]` extracts as `1]`
Limiting the number of substrings to 2 ensures that everything after `ip:` is kept together

fix(clrcore): correctly extract identifier values containing ':'

---

code/components/gta-streaming-five/src/GameEventHooks.cpp

This appears to be fixed for build 2189.
Tested it, played with it for a bit.
Couldn't find any info as to what exactly was causing the crash before (only found Pichot referencing it somewhere on the forum) but simply reenabled it and tested with it and didn't find any obvious issues with it.
I tested the CEventNetworkEntityDamage and CEventNetworkVehicleUndrivable they appeared to work fine.
Seems to me that some fix somewhere along the road fixed the events.

fix(events): Reenable gameEventTriggered for build 2189

---

code/client/clrcore/External/World.cs

CreateRandomVehicle was returning a non existent Vehicle because the model wasn't loaded
- now return `Task<Vehicle>`
- won't return null if a model doesn't exist
- _`random.Next(maxValue)` return `maxValue - 1`_

fix CreateRandomVehicle

---

data/shared/citizen/scripting/v8/index.d.ts

Created typedefs for typescript statebag.
I've been unable to get NewStateBag to work on arbitrary bags. I'm unsure if this is me being stupid.
It may be worth removing the `NewStateBag` definition for that reason.

Added typescript statebag definitions

---

code/components/glue/src/ConnectToNative.cpp
ext/cfx-ui/src/app/game.service.ts

Force streamer mode value per-session using:
`fivem://connect/127.0.0.1?streamerMode=true` (or `=1`)
Does **not** set the archived variable `ui_streamerMode`.
**Currently only supports FiveM 'cold start'.**
(calling fivem:// when FiveM is closed)
I am not sure how to correctly (and neatly) pass the `streamerMode` value [through the socket to the running FiveM instance](https://github.com/citizenfx/fivem/blob/4fb12d066857851f9619281e2eba7b0271fd0b38/code/components/glue/src/ConnectToNative.cpp#L1196).
Would appreciate guidance if anyone is up for it.

feat(glue): forced streamer mode using `fivem://`

---

data/shared/citizen/scripting/lua/scheduler.lua

This avoids if statements expecting a boolean from a ref passing if a ref is invalid.
This would copy the behaviour of having an error in a ref call, this would probably crash some plugins which lack checking but seems better than having a plugin continue on and causing havok further down the road.

tweak(lua/scheduler): Return nil on invalid ref

---

data/client/citizen/common/data/gameconfig.xml

Many people are actually getting this crash.
Some people started to manually edit this field and are not experiencing any side-effects, I believe it could be fine to just increase it

fix(gameconfig): increase AttachmentExtension pool

---

code/components/citizen-server-impl/include/state/SyncTrees_Five.h

#595 re-opening of my old pr as i had deleted accidentally the branch so i was unable to commits new changes.

fix(onesync): typo in CPedHealthDataNode

---

data/shared/citizen/scripting/lua/scheduler.lua

- useful if you need/want to remove the EventHandler later.

fix(scheduler): return event handler

---

code/components/gta-streaming-five/src/PatchDecalLimits.cpp

Increasing decal def (see decals.dat) limit to 512.
Tested on 1604, 2060 and 2189 using `replace_level_meta` for loading custom `decals.dat`

Patch decal def limits

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp

Currently SET_VEHICLE_AUTO_REPAIR_DISABLED only disables auto-repair for the player that has network control of the vehicle. When the vehicle extras sync between players, auto-repair is called from a different location, which isn't disabled.

tweak(extra-natives-five): disable auto-repair on extra sync

---

ext/cfx-ui/src/app/servers/components/filters/server-filter.component.scss

Users on Safari (and maybe other WebKit browsers) aren't able to input text to the server search box because it's inheriting `user-select: none`, so this override should resolve that.

Fix server list filter input on Safari

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/SetPlayerCullingRadius.md

This PR adds the ability to set a players culling radius on onesync infinity with the following native:
SET_PLAYER_CULLING_RADIUS(playerSrc,radius)
This also decides the priority of which culling distance to use in the following order, thanks to @PichotM for the idea. example:
- entity radius if set by SET_ENTITY_DISTANCE_CULLING_RADIUS
- player radius if set by SET_PLAYER_CULLING_RADIUS
- default radius (424.0f)

feat(onesync): add SET_PLAYER_CULLING_RADIUS native

---

code/client/clrcore/EventHandlerDictionary.cs
code/client/clrcore/InternalManager.cs
code/client/clrcore/Server/ServerWrappers.cs
code/components/citizen-server-impl/src/ClientRegistry.cpp
code/components/citizen-server-impl/src/GameServer.cpp
code/components/citizen-server-impl/src/InitConnectMethod.cpp
data/shared/citizen/scripting/lua/scheduler.lua
data/shared/citizen/scripting/v8/main.js

~~playerJoining is emitted by the server and is considered a net event but wasn't added to the safe net events whitelist for Lua or JS.~~
Server only events which are internally considered net events (like playerConnecting, playerDropped and playerJoining) are now handled separately from proper network events and cannot be triggered by clients unless the event is explicitly registered as a network event.
This fixes issues with the playerJoining event and stops malicious clients from triggering playerConnecting or playerDropped themselves.

fix(scripting): rework server-internal events 

---

code/components/citizen-server-impl/include/state/SyncTrees_Five.h

Should fix related server-side natives like `IS_PLAYER_USING_SUPER_JUMP`, `GET_PLAYER_INVINCIBLE` and so on.

Fix CPlayerGameStateDataNode for 2060/2189

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp

For sync nodes, the driver seat index starts at 1, and so on
This fixes the compatibility with the game seat index that starts at -1 for the driver

fix(onesync-natives): compatibility with game seat indexes

---

code/components/voip-mumble/include/MumbleAudioOutput.h
code/components/voip-mumble/src/MumbleAudioOutput.cpp

This is my quick fix for this issue:
https://forum.cfx.re/t/fivem-voice-chat-lags-behind/2579415/
I believe the nativeAudio end does actively poll, so that's what I've configured on the other end. This might be a candidate for utilizing multiple cores, but maybe that's not worth the effort.

fix(voip/mumble): actively poll the jitter buffer in both modes

---

code/components/voip-mumble/include/MumbleAudioOutput.h
code/components/voip-mumble/src/MumbleAudioOutput.cpp

This is my second take on solving the problem within #697, [referencing this forum post](https://forum.cfx.re/t/fivem-voice-chat-lags-behind/2579415), whereby the jitter buffer hoards more and more packets over time in XA2 audio mode.
I've tested this locally, between my PC and my laptop.

fix(voip/mumble): add jitter buffer management to XA2 path

---

code/client/citigame/Launcher.cpp
code/components/asi-five/src/Component.cpp

1. Forces updating or removal of silently crashing gears.asi versions.
2. Exports a new 'GetGameVersion' function allowing mods to reliably check the version of the currently running game.

Patches for "GTAVManualTransmission"

---

data/shared/citizen/scripting/v8/index.d.ts

`global.getPlayers()` returns an array of strings not numbers.
`global.source` is being parsed as an integer during net events in `main.js`

fix(scripting/v8): fixed getPlayers() & source type definition

---

data/shared/citizen/scripting/v8/index.d.ts
data/shared/citizen/scripting/v8/main.js

This PR aims to establish further feature parity between the Lua & v8 ScRT, it adds a simple global helper function, `SendNUIMessage`, that will automatically JSON encode its passed argument, just as its Lua counterpart does. 
I wasn't sure how you would have wanted this cased as there is a mix between PascalCase and CamelCase for globals, so stuck with the PascalCase Lua format.

feat(scripting/v8): Add SendNUIMessage as helper function

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/GetPedScriptTaskCommand.md
ext/native-decls/GetPedScriptTaskStage.md
ext/native-decls/GetPedSpecificTaskType.md

Add parsing for the CPedTaskTreeDataNode and adds three getter natives for tasks

feat(onesync): ped task tree node parsing and natives

---

data/shared/citizen/scripting/lua/scheduler.lua
data/shared/citizen/scripting/v8/index.d.ts
data/shared/citizen/scripting/v8/main.js

I noticed that there wasn't a GetPlayerTokens helper, equivalent to GetPlayerIdentifiers, and figured it might be similarly helpful.

feat(scripting): Add GetPlayerTokens helper

---

code/components/nui-core/include/NUIClient.h
code/components/nui-core/src/NUIClient.cpp

prevent opening new windows from NUI as these break input focus (target="_blank")
prevent navigation of the root NUI away from the root page (shift clicking links)

fix(nui/core): prevent actions that would break nui

---

code/components/extra-natives-five/src/NativeEdits.cpp
ext/native-decls/SetRopesCreateNetworkWorldState.md

Unlike other natives which implement world state, ADD_ROPE does not have a parameter to whether you want the rope networked. Instead it relies on a net game check whether to create an underlying CNetworkRopeWorldStateData. As network world state is currently not implemented, this leads to a memory leak and pool being filled upon multiple rope creations. This native aims to solve two problems:
- Prevent the issue aforementioned
- Maintain backwards compatibility for future, as if world state was to be implemented, all ropes (which people assumed to be non-networked) would suddenly be networked without this

feat(natives/five): network world state control for ropes

---

code/components/gta-net-five/src/CloneExperiments.cpp

This should fix weird behavior of ped overlay natives when state awareness (aka OneSync) is enabled.

Pass real net object owner id for ped overlay natives for RDR3

---

code/tools/fxd/get-chrome.ps1

On an fresh install the folder code/build/ doesn't exist and so curl needs to create the missing folders

fix(dev/fxd): create missing dirs on download

---

code/components/gta-net-five/src/CloneExperiments.cpp

Due to the way how we handle net game events, there's some edge cases when the game can overflow the `netGameEvent` pool. This limit shouldn't affect casual gameplay scenarios.

Prevent ped speech events from overflowing net game event pool in RDR3

---

ext/cfx-ui/src/app/nav/app-nav.component.scss

I've done some changes for the nav buttons. 
- Added active route styles.
- Removed focus from the nav buttons
Here's how the active style looks like:
Reason for removing the focus was because if you did not clickaway, the selected nav button would overlap the other ones you tried to select, hiding some of the text.
**Before:**
**Now:**

tweak(ext/cfx-ui): active route style for nav buttons

---

code/components/voip-mumble/src/MumbleDataHandler.cpp

Reading mumble prefix when not enough data are available will lead to crashes due to memory corruptions
Fix taken from reference mumble client:
https://github.com/mumble-voip/mumble/blob/464fc4a36dd53bc5f7af47b09a30fe885512d9bd/src/Connection.cpp#L118
Tested and approved :)

fix(voip-mumble): don't read mumble prefix if not enough data

---

ext/cfx-ui/src/styles/global.scss

Minuscule change, but apparently some people prefer clicking and dragging rather than using filters and scroll wheels. This just makes the scrollbar slightly wider (3px increase to 5px) so it's easier to click when it's not up against the side of the monitor (i.e. blocking mouse movement from going all the way to the right)

tweak(cfxui): make scrollbar slightly wider

---

code/components/extra-natives-five/src/GamerTagNatives.cpp
ext/native-decls/SetMpGamerTagsUseVehicleBehavior.md
ext/native-decls/SetMpGamerTagsVisibleDistance.md

Adds:
SET_MP_GAMER_TAGS_VISIBLE_DISTANCE to be able to set the maximum distance at which gamer tags are displayed.
SET_MP_GAMER_TAGS_USE_VEHICLE_BEHAVIOR to toggle whether gamer tags should act differently when in a vehicle

feat(natives/five): gamer tags visibility and behavior natives

---

code/components/extra-natives-five/src/GamerTagNatives.cpp

This fixes an issue (from #770) with the newer gamer builds having tags on top of each other when using default game behavior. In 1604, RAX is unused beyond the detour so does not require the original value back. However, in 2060+ RAX is used after and thus its original value (ped pointer from RBX) must be restored. Tested on all game builds with multiple players in and out of vehicles.

fix(natives/five): gamer tags on top of each other

---

code/components/scripthookv/src/VishCompat.cpp
code/components/scripthookv/src/VishRenderer.cpp

Sorry for increasing your review workload.
Here are a few changes to improve compatibility and closer resemble a few minor things that scripts for ScriptHookV may rely on:
- Return the ScriptHookV version number
- Match the rotation of `drawTexture`
I'm kind of at wit's end about the version number thing and FiveM's `GetGameVersion`.
On one hand, Alexander Blade's decision to *randomly* assign numbers where builds already are a thing baffles me, but at least there was consistency *until* `1.0.1734.0` which they forgot/were too late with, and just *skipped* it, but did not skip adding the version number, breaking the pattern. Then the initial Epic Games patch `1.0.1868.4` had its own separate `eGameVersion` number, but *not* the subsequent one, once again breaking the pattern. It's …

fix(vish): Improve compatibility for ScriptHookV-targeting scripts

---

code/components/scripthookv/src/VishCompat.cpp

Should resolve startup crashes introduced in #773, caused by incorrect return type.

Correct return type for getGameVersion export in ViSH

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp

Since 2372 the first unsigned int got removed from the buffer.

fix(onesync): CWeaponDamageEvent for 2372

---

ext/cfx-ui/src/app/servers/components/detail/servers-detail.component.html
ext/cfx-ui/src/app/servers/components/detail/servers-detail.component.ts
ext/cfx-ui/src/app/servers/components/list/servers-list-item.component.html
ext/cfx-ui/src/app/servers/components/list/servers-list-item.component.scss
ext/cfx-ui/src/app/servers/components/list/servers-list-item.component.ts
ext/cfx-ui/src/app/servers/servers.service.ts

Users can't be expected to understand the periodic table or the fact server subscriptions are named after elements.
See the following (real) support questions:
> what do all the little tag abbreviation means in the server list? like Pt
> In the server browser some servers have "AG" or a "PT" icon in front of it... does PT means that they have the patreon sub?
> another thing, why some servers aren't portuguese but they show as PT list
This might be helpable with minimal impact by adding a tooltip:
This changeset adds such a tooltip to the server list as well as the detail page.

Add tooltips explaining premium levels in cfx-ui

---

code/components/nui-core/src/NUIInitialize.cpp
code/components/nui-core/src/NUIWindow.cpp

See #793, this moves the SDK guest into a `nui-storage-fxdk-guest` directory.

fix(nui/core): add SDK guest storage directory

---

code/client/clrcore/PlayerList.cs

This saves around 50-100 microseconds (usec) on the 3970X with vMenu on a server with a single player online.

tweak(scripting/csharp): use GetActivePlayers for PlayerList

---

ext/cfx-ui/src/app/servers/components/detail/servers-detail.component.ts

Fixes #808, see also https://forum.cfx.re/t/4483453 for initial report.
Old behavior is retained for the non-embedded web environment in case of deeplinking.

fix(ext/cfx-ui): tie server detail back button to back action

---

ext/cfx-ui/src/styles/variables.scss

Closes #816. Unsure if this is the correct art direction, but it looks fine on the pages I could find using this style.

fix(ext/cfx-ui): make pageHeader have the same margin as server filters

---

code/components/gta-net-five/src/ClientRPC.cpp

Fixes #798, hopefully.
Untested, should do this before merging.

fix(gamestate/client): client RPC SEH wrapper

---

code/components/gta-streaming-five/src/CacheLoader.cpp

Closes #825.
Some dead code directly related to this was removed as well.
> [     21953] [         fivem]             MainThrd/ LoadScreenFuncs::OnEnd: Instrumented function 0x140dd2b10 (2) took 162msec
> [     22797] [         fivem]             MainThrd/ LoadScreenFuncs::OnEnd: Instrumented function 0x1408f5b5c (53) took 849msec
> [     24625] [         fivem]             MainThrd/ Loading content XML: dlc_patchDay23NGCRC:/content.xml
> [     25141] [         fivem]             MainThrd/ LoadScreenFuncs::OnEnd: Instrumented function 0x1407e3f7c (56) took 2346msec
> [     25266] [         fivem]             MainThrd/ LoadScreenFuncs::OnEnd: Instrumented function 0x14092011c (24) took 83msec
> [     25453] [         fivem]             MainThrd/ LoadScreenFuncs::OnEnd: Instrumented …

fix(streaming/five): re-enable cache loader hook for 2189+

---

code/components/voip-server-mumble/src/conf.cpp
code/components/voip-server-mumble/src/messagehandler.cpp

Add: "mumble_adminPass" convar to be able to become mumble admin and kick/ban users
Disable text channels
Enable bans (until server restart)

Feat: Enable mumble bans + disable text + admin pass convar

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/GetEntitySpeed.md

Currently doesn't work on peds as it seems they don't seem to have a CPhysicalVelocityDataNode

feat(onesync): add GET_ENTITY_SPEED native

---

code/components/nui-core/include/CefOverlay.h
code/components/nui-core/src/CefInput.cpp
code/components/nui-resources/src/ResourceUIScripting.cpp
ext/native-decls/IsNuiFocusKeepingInput.md
ext/native-decls/IsNuiFocused.md

It allows to easily detect when some external resource already took NUI focus and not to start our own focus-aimed actions in that case.

NUI_HAS_FOCUS native

---

code/components/extra-natives-five/src/GamePrimitives_Outlines.cpp

fix(extra-natives/five): don't try to call drawhandler for CObject with CDummyObject

---

code/client/citicore/PatternCache.cpp

- Don't load hints for ChromeBrowser.
- Delete oversized hint files.
See https://forum.cfx.re/t/4579322 for a related user report.

fix(core): mitigations for systems affected by bdbfb32b6eab7c5707882770bab123194c31384c

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/NetworkGetFirstEntityOwner.md

It's hard to keep a grudge against even the abusers who use this call, even though it's not having any actual valid use cases, and using it for such a thing would be wrong... it's somehow become part of the ecosystem.
Fixes #884, again.

feat(onesync): re-add NETWORK_GET_FIRST_ENTITY_OWNER

---

code/components/citizen-resources-core/include/ResourceManagerConstraintsComponent.h
code/components/citizen-resources-core/src/ResourceDependencyLoader.cpp
code/components/citizen-resources-core/src/ResourceManagerConstraintsComponent.cpp
code/components/citizen-server-impl/src/ServerResources.cpp

Meta-dependencies starting with `/` to check for environment constraints before starting a resource.
Example:
```lua
dependencies {
'/server:4000',
'/server:999999',
'/server:696969',
'/policy:subdir_file_mapping',
'/policy:meow',
'/onesync',
'/gameBuild:h4',
'/native:0xE27C97A0',
'/native:0xDEADBEEF',
}
```
Output example:
```text
[    c-resources-core] Resource 'constraint' can't run:
[    c-resources-core]   1. server needs to be 999999 or higher
[    c-resources-core]   2. server needs to be 696969 or higher
[    c-resources-core]   3. policy(meow): you do not have access to the 'meow' policy
[    c-resources-core]   4. gameBuild(h4): sv_enforceGameBuild needs to be at least 2189 (current is 1604)
[    c-resources-core]   5. native(0xDEADBEEF): native 0xDEADBEEF isn't supported
[ …
```

feat(resources): dependency constraints

---

code/components/citizen-resources-client/src/KVScriptFunctions.cpp
ext/native-decls/kvp/external/GetExternalKvpFloat.md
ext/native-decls/kvp/external/GetExternalKvpInt.md
ext/native-decls/kvp/external/GetExternalKvpString.md
ext/native-decls/kvp/external/StartFindExternalKvp.md

Allows getting KVP data from resources other than the current one.
Example:
```lua
print(GetExternalKvpString('vMenu', 'mp_ped_a but off by one'))
```
Requested:
> Is there a way to get KVPs from a resource without making a resource with its name? I want to seamlessly import stuff from vMenu (vehicle mods etc) without loading vMenu itself on the server. Am I basically forced to name a resource vMenu and then use it to fetch the info?

feat(resources/client): external KVP commands

---

code/components/gta-core-five/src/DisableCameraShake.cpp
ext/cfx-ui/src/app/settings.service.ts
ext/cfx-ui/src/assets/languages/locale-en.json

Allows users to turn camera shake off, both while driving a vehicle and running (third person only).
Mainly a QOL change for people suffering from motion sickness due to camera shake.
Currently requires a game restart to take effect if changed manually in F8 console (eg. seta "cam_disableCameraShake" "true") as forcing value changes on address while game is running caused crashes (unsure why, works fine in base game), however, changing it in FiveM launcher settings works properly, so I went with that solution and hook on first load. Haven't had any issues doing it that way.

Add camera shake override setting

---

code/client/launcher/CrossBuildLaunch.cpp
code/client/launcher/ExecutableLoader.Snapshot.cpp
code/client/launcher/GameCache.cpp
code/client/launcher/StdInc.h
code/client/launcher/premake5.lua
code/client/shared/CfxSubProcess.h
code/client/shared/CrossBuildRuntime.h
code/components/extra-natives-rdr3/src/NativeFixes.cpp
code/components/font-renderer/src/GtaGameInterface.cpp
code/components/gta-core-rdr3/src/EntityDeletionHacks.cpp
code/components/gta-net-five/src/CloneExperiments.cpp
code/components/gta-net-five/src/CloneManager.cpp
code/components/gta-net-five/src/CloneObjectManager.cpp
code/components/gta-net-rdr3/include/netObjectMgr.h
code/components/gta-net-rdr3/src/CoreNetworking.cpp
code/components/gta-net-rdr3/src/netObject.cpp
code/components/gta-streaming-rdr3/src/Streaming.cpp
code/components/net/src/NetLibrary.cpp
code/components/rage-graphics-rdr3/src/GfxSpec.cpp
code/components/rage-nutsnbolts-rdr3/src/FrameHook.cpp
code/components/ros-patches-five/src/ros/Entitlements.cpp
data/client_rdr/citizen/common/data/gameconfig.xml
ext/native-decls/GetGameBuildNumber.md

Used build: 1436.26 (latest at this moment).
Re-implemented most popular removed natives for backward compatibility
DLSS works with some minor manual tweaks.

Add crossbuild support of b1436 for RedM

---

code/client/citicore/SEHTableHandler.Win32.cpp
code/components/ros-patches-five/src/ros/LoopbackTcpServer.cpp

Still requires removing adhesive.dll, but at least the game itself doesn't break anymore.

fix(game/five): support basic functionality on ARM64 again

---

code/components/gta-core-five/src/CrashFixes.TrailerAttachment.cpp

Bug mainly affects 2372 as bad-luck pointer instead of a nullptr.
Repro (client script, assumes entity lockdown disabled):
```lua
RequestModel('tanker')
RequestModel('a_m_m_skater_01')
LoadAllObjectsNow()
local pos = GetEntityCoords(PlayerPedId())
local trailer = CreateVehicle(`tanker`, pos, 0.0, true, false)
local ped = CreatePed(23, `a_m_m_skater_01`, pos, 0.0, true, false)
AttachEntityToEntity(trailer, ped, 0)
```
followed by blowing up the trailer with an RPG.

fix(game/five): resolve game bug where trailer attachment could make game crash

---

code/components/citizen-devtools/include/ResourceMonitor.h
code/components/citizen-devtools/src/ResourceMonitor.cpp
code/components/citizen-devtools/src/ResourceTimeWarnings.cpp

This leads to longer GC pauses with Mono stuff in use, when in most cases this information is fairly useless.
Also closes #688.

tweak(devtools): don't get memory metrics during normal gameplay

---

code/components/citizen-server-impl/src/ResourceStreamComponent.cpp

This should fix the case where stream_cache contains 'old' versions of streaming assets, slightly related to #859.

fix(server/impl): delete stream hash pairs for resource restarts

---

code/components/extra-natives-five/src/RuntimeAssetNatives.cpp

fix(extra-natives/five): validate CREATE_RUNTIME_TEXTURE size

---

code/components/citizen-server-impl/include/ClientRegistry.h
code/components/citizen-server-impl/src/ClientRegistry.cpp
code/components/citizen-server-impl/src/GameServerNet.ENet.cpp
code/components/citizen-server-impl/src/InitConnectMethod.cpp
code/components/net/include/NetLibrary.h
code/components/net/include/NetLibraryImplBase.h
code/components/net/src/NetLibrary.cpp
code/components/net/src/NetLibraryImplV2.cpp
vendor/citizen_enet/include/enet/enet.h
vendor/citizen_enet/src/host.cpp
vendor/citizen_enet/src/protocol.cpp

**DO NOT MERGE UNTIL RIGHT BEFORE A PRODUCTION RELEASE**: this changes the minimum net protocol version leading to confused server owners.
We use the `data` field in enet_host_connect to pass a derivative of the connection token, which then is checked *early* in ENet connectivity (before allocating a temporary peer).
This should mitigate the scenario where fake peers either spam UDP packets to not get acknowledged, or acknowledge without ever sending an initial connection.

fix(net): prevent enet connection without connection token

---

code/components/extra-natives-five/src/NuiAudioSink.cpp

This *should* add 64 extra slots (in case there's 128+ audio entities trying to be created at the same time). See https://forum.cfx.re/t/3776013/12.

fix(audio/five): add 2 extra allocation buckets

---

code/components/gta-core-five/src/GameInput.cpp

Internally, this does an `rbind` for `~!command` to mark it as the secondary key binding for UI persistence.

feat(input/five): secondary binding support for keys

---

code/components/gta-core-five/src/GameInput.cpp

These will still conflict a little bit with navigation keys (e.g. binding `A` is a pain), but they seem to work.
Also fixes a crash when unbinding a controller key.

feat(input/five): allow binding custom controls to pad buttons

---

code/components/citizen-server-impl/src/GameServerNet.ENet.cpp
code/components/net/src/NetLibraryImplV2.cpp

- Fixes a potential workaround for the ENet peer data mitigation.
- Fixes m_peerHandles not getting cleaned on 'unclean' disconnect.
- Fixes `quit` command not gracefully closing the server-side ENet peer.

ENet peer fixes, run 2

---

code/components/ros-patches-five/src/LegitimacyChecking.cpp

This should fix some edge cases where users are signed in to a Steam account with borrowed RDO/RDR copy, but they're actually only intending to use a R* store copy.

fix(ros): don't try to use a Steam ticket if the app is borrowed

---

code/client/citicore/console/Console.Base.cpp
code/components/citizen-server-monitor/src/MonitorInstance.cpp

This is annoying since Windows Terminal started accepting this flag as well, despite it not being of any use.

tweak(server/impl): move QuickEdit disable to monitor

---

code/server/launcher/src/Server.cpp

A user was trying to use this switch and was surprised to find the Node.js version without any further annotations.

feat(server/launcher): --version and --help arguments

---

code/components/glue/src/GtaNui.cpp
code/components/rage-graphics-rdr3/src/GfxSpec.cpp

Fixes this little issue reported to occur on D3D12:

RedM sampler state fix

---

code/components/citizen-server-impl/include/ClientRegistry.h
code/components/citizen-server-impl/src/GameServerNet.ENet.cpp
code/components/net/src/NetLibrary.cpp

1. Timeout with '23ms' showing instead of `quit` message.
2. A crash observed while implementing the earlier fix.
3. Something led to stray clients showing in `svgui`'s player list.

Assorted quit fixes

---

code/components/citizen-server-impl/include/Client.h
code/components/citizen-server-impl/include/GameServerNet.h
code/components/citizen-server-impl/include/ServerEventComponent.h
code/components/citizen-server-impl/src/ClientRegistry.cpp
code/components/citizen-server-impl/src/GameServer.cpp
code/components/citizen-server-impl/src/GameServerNet.ENet.cpp
code/components/citizen-server-impl/src/ServerResources.cpp
code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/components/citizen-server-impl/src/state/ServerRPC.cpp

'Reconnecting' flow has been removed a long time ago, and some of this code was hitting perf-related issues on large servers.

tweak(server/impl): remove unused reliable replay logic

---

code/tools/ci/build_server_2.sh
code/tools/ci/build_server_proot.sh

The JS ecosystem expects deprecated hashes like 'md4' to exist and of course these are removed in OpenSSL 3.

fix(build/linux): update base alpine, force openssl 1.1

---

code/components/gta-net-five/src/CloneExperiments.cpp

```
local playerid = NetworkGetPlayerIndexFromPed(target)
print(playerid)
print(NetworkIsPlayerActive(playerid))
print(GetPlayerServerId(playerid))
```
before
after

fix(rdr3) improve hook for NETWORK_GET_PLAYER_INDEX_FROM_PED native 

---

code/components/citizen-scripting-v8/src/V8ScriptRuntime.cpp

fix(scripting/v8): don't use V8PushEnvironment on client Destroy

---

code/client/launcher/ExecutableLoader.cpp

This should make 2060, 2189 and 2372 a little less annoying to debug.
Data generated by pushing/pulling local 323/1604 db to a [lumen](https://github.com/naim94a/lumen) instance for lack of time to bother with a full bindiff/diaphora rename. May not contain all data PR'd to dumb_1604.txt at this time.

tweak(game/five): add a minimal debug export

---

.gitmodules

fix(vendor): move libuv to a fork for downlevel compatibility

---

code/client/launcher/CrossBuildLaunch.cpp

Another case of bandwidth/download time saving.

tweak(client/launcher): use b2372 as 'default' for new installs

---

code/components/citizen-scripting-v8/src/V8ScriptRuntime.cpp

https://forum.cfx.re/t/linux-chat-resource-not-starting-i-think-due-to-webpack/4761026/4

fix(scripting/v8): use icudtl path for linux fxnode too

---

code/components/nui-resources/src/ResourceUIScripting.cpp
ext/ui-build/data/root.html

Fixes a few common UI gotchas:
1. https://forum.cfx.re/t/problem-with-chat-console-input/4764187 - keep-input resources conflicting with focus resources
2. Some fixes for UI focus getting lost on the browser side when unfocusing, starting or restarting a new resource. ~~This still doesn't handle the case where two resources unfocus after one another, nor does it handle the case where the last unfocused resource is actually _not_ the currently-focused resource: this _might_ need fixing before merging (i.e. keeping an actual focus stack with _only_ focused frames, and the Z order list separately).~~

NUI focus tweaks

---

code/components/rage-formats-x/include/convert/gtaDrawable_five_rdr3.h

emissive legacy shader doesn't do anything in rdr3, so it's mapped to emissivestrong

formats:convert small touch-ups for shaders

---

code/components/gta-streaming-five/src/UnkStuff.cpp

For some reason R* was overriding tint value field with interior proxy pool index. Looks like a bug caused by mistyping. This bug was only affecting interior `CEntityDef`s.
Before fix:
After fix:

Fix a bug causing tintValue to be ignored for interior entities

---

code/components/citizen-server-impl/include/ClientDeferral.h
code/components/citizen-server-impl/src/ClientDeferral.cpp
code/components/citizen-server-impl/src/InitConnectMethod.cpp

Prevents resources from having to manually resend a deferral message to not have the TCP conn time out.

tweak(server/impl): periodically send a deferral refresh to prevent timing out

---

code/components/conhost-v2/src/DrawPerf.cpp

AMD driver authors didn't read 'deci-Celsius' at one point and instead give callers milli-Celsius. Thanks, AMD!

fix(conhost/v2): drawperf gpu temp won't exceed Sol's surface temperature

---

code/components/conhost-v2/src/ConsoleHostImpl.cpp

Console font has much more glyphs than FiveM loads. It's enough to enable them to allow fully localized console output for many European languages:

feat(conhost): load extra glyph ranges to allow localized console output

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/GetEntityAttachedTo.md

Adds the equivalent of [GET_ENTITY_ATTACHED_TO](https://docs.fivem.net/natives/?_0x48C2BED9180FE123) to the server

feat(onesync): entity attached to native

---

code/components/conhost-v2/src/ConsoleHostImpl.cpp
code/components/glue/src/GtaNui.cpp
code/components/nui-core/src/CitizenNUIBackground.cpp
code/components/nui-core/src/NUIClient.cpp
code/components/nui-core/src/NUIRenderCallbacks.cpp

This PR includes two changes:
- b015dcc5433560287261deaec27cd49645aa44b0 implements something similar to #1109, replaces the default arrow cursor in NUI contexts with the citizen_cursor, though keeping the hardware cursor rendering for it.
- 3f8a1d129426b551cc9c9c8a7b0d5e11b9182dee *may* help with https://forum.cfx.re/t/cursor-invisible-after-opening-f8-console/4768705/27, I'm unable to actually repro the issue there so it might not fix it, however this flag being added doesn't break any existing behavior.
Bug fix and user request.
No breaking issues are expected. This does not change any public API either.

Assorted cursor fixes

---

code/components/gta-net-five/src/MumbleVoice.cpp
ext/native-decls/MumbleClearVoiceChannel.md
ext/native-decls/MumbleSetVoiceChannel.md

After some testing with the recent Disquse PR, it seems there are no equivalent for some natives present in gta5 :
- NetworkClearVoiceChannel (0xE036A705F989E049)
- NetworkSetVoiceChannel (0xEF6212C2EFEF1A23)
These natives simply don't exist in RDR3 so there is no way to move the mumble client to any other channel (from my understanding).
These natives can be added back simply with this PR.
If Disquse has other plans for these natives, or if you think this is not the right way to implement this, feel free to close this PR as I was just trying to help with my minimal knowledge :)

Add mumble channel natives for rdr3 compatibility

---

code/client/shared/EventCore.h
code/client/shared/Utils.cpp
code/components/citizen-devtools/include/ResourceMonitor.h
code/components/citizen-devtools/src/ResourceMonitor.cpp
code/components/citizen-devtools/src/ResourceTimeWarnings.cpp
code/components/citizen-resources-core/include/Resource.h
code/components/citizen-resources-core/include/ResourceEventComponent.h
code/components/citizen-resources-core/include/ResourceImpl.h
code/components/citizen-resources-core/include/ResourceManagerImpl.h
code/components/citizen-resources-core/src/Resource.cpp
code/components/citizen-resources-core/src/ResourceEventComponent.cpp
code/components/citizen-resources-core/src/ResourceManager.cpp
code/components/citizen-resources-gta/src/ScriptHandler.cpp
code/components/citizen-scripting-core/include/PushEnvironment.h
code/components/citizen-scripting-core/include/ResourceScriptingComponent.h
code/components/citizen-scripting-core/include/fxScripting.idl
code/components/citizen-scripting-core/src/Profiler.cpp
code/components/citizen-scripting-core/src/ResourceScriptingComponent.cpp
code/components/citizen-scripting-core/src/ScriptHost.cpp
code/components/citizen-scripting-lua/include/LuaScriptRuntime.h
code/components/citizen-scripting-lua/src/LuaScriptRuntime.cpp
code/components/citizen-scripting-mono/include/MonoThreadAttachment.h
code/components/citizen-scripting-mono/src/MonoComponentHost.cpp
code/components/citizen-server-fxdk/include/SdkIpc.h
code/components/citizen-server-fxdk/src/SdkIpc.cpp
code/components/citizen-server-impl/src/ServerResources.cpp
code/components/citizen-server-impl/src/ServerWatchdog.cpp
code/components/gta-net-five/src/ClientRPC.cpp
code/components/scripting-server/include/ScriptEngine.h
data/shared/citizen/scripting/lua/scheduler.lua

Removes `OnTick` for resources itself, instead handling this in manager scope. Also, implements native 'bookmarks' for Lua scheduling instead of doing this in the HLL.
Closes #1153 once merged - perhaps-WIP currently.
Servers often have hundreds of (mostly idle) Lua resources. Profiling showed around 30-40% of script frame time spent on servers like Tycoon (see #1153) was overhead.
* Earlier versions of this patch set went down from 1.5 msec of script time to <0.2 msec of script tick time in a contrived setup (200 resources each having a single Wait(5000) no-op loop + chat/spawnmanager/mapmanager as used in basic-gamemode)
* Tycoon went down from 5.8 msec of script time to 4.0 msec of script time.
* The queue bits aren't micro-optimized, needs profiling later on.
* Can join and play on …

'Tickless' resources

---

code/premake5.lua

Remove Visual Studio warnings about using relative file paths in .csproj.user.

Add premake override for csproj.user files

---

data/client_rdr/citizen/common/data/gameconfig.xml

Should resolve script handler pool crashes in RedM (`CGameScriptHandler` a.k.a. 0x1182232C).

Increase script handler pools size for RDR3

---

code/components/citizen-server-impl/src/ServerResources.cpp

start/stop/ensure accepts non-existent resource category names without a response.
To fix this, the category is now retrieved using `find`. If it doesn't exist, a message is returned.
Closes #1159

Indicate invalid resource categories for start/stop/ensure

---

code/components/gta-streaming-five/src/LoadStreamingFile.cpp

This change will allow to mount new data file types introduced in b2545:
`CARCOLS_GEN9_FILE`
`CARMODCOLS_GEN9_FILE`
`COMMUNITY_STATS_FILE`

Update data file types count for FiveM b2545

---

data/shared/citizen/scripting/v8/index.d.ts
data/shared/citizen/scripting/v8/main.js

As title says, this PR add missing `LocalPlayer` alias for `Player(-1)` in V8 script runtime.
Like in Lua scrt https://github.com/citizenfx/fivem/blob/6e1f04ed2739b3927a77fb437b4338a23d187efa/data/shared/citizen/scripting/lua/scheduler.lua#L1079-L1081

tweak(scripting/v8): Add missing LocalPlayer state bag alias

---

code/components/citizen-resources-gta/src/GameEventFunctions.cpp
code/components/gta-streaming-five/component.json
code/components/gta-streaming-five/include/EntitySystem.h
code/components/gta-streaming-five/src/GameEventHooks.cpp
code/components/handling-loader-five/component.json

This update will re-enable the hooking for the missing game events and retrieves all entities associated with it.
I've created separate scripting events that are being called, this, to allow fitting arguments to be passed to scripts and not to break existing listeners. They are called "gameEventEmit" and "gameEventReact" respectively as there are 3 game event versions; 1 that's already handled with "gameEventTriggered", 1 that sends an event to nearby entities (like when an event just occured), and the last 1 by who entities react to previous events (e.g.: CEventShockingDeadBody).
Events like CEventShocking*, CEventPotentialWalkIntoVehicle, and CEventPotentialGetRunOver already retrieve the world position.
To support more events' data retrieval we would need to analyze the event data and …

feat(streaming-five): Add support for other Game Events (Emitting and Reacting)

---

data/shared/citizen/scripting/lua/scheduler.lua
data/shared/citizen/scripting/v8/main.js

I was having a look at Citizen.Await / promises and noticed some weird hack, despite promises exposing state and value (maybe based on some old code?). I didn't experience any unexpected behaviour with this change to the implementation.
Change to main.js returns the actual error message, rather than an empty object in the Lua runtime.

tweak(scripting/lua): Citizen.Await promise handling

---

code/components/citizen-resources-gta/src/GameEventFunctions.cpp
code/components/gta-streaming-five/component.json
code/components/gta-streaming-five/include/EntitySystem.h
code/components/gta-streaming-five/src/GameEventHooks.cpp

This update will re-enable the hooking for the missing game events and retrieves all entities associated with it.
- Better design that follows the game's event system, which fixes the crashing of previous version https://github.com/citizenfx/fivem/pull/1195.
- All events will now get the associated entity, even those missing in previous version.
- Previous Emit/React versions merged, event names are now the same as the game event name itself, e.g.: "CEventShockingSeenNiceCar".
- Right now only CEventShocking* reads the position of the event and puts it in the args parameter.
Example usage (Lua):
```lua
AddEventHandler("CEventShockingGunshotFired", function(entities, eventEntity, args)
print("CEventShockingGunshotFired", json.encode(entities), eventEntity, json.encode(args));
end);
```

feat(streaming-five): Add support for other Game Events (fixed)

---

code/components/debug-net/src/NetDebug.cpp

**Summary:**
- Move the netgraph along the screen resolution if it ever changes. This should solve the following issue: 
- #955 
**Changes:**
- Changed `ConHost::OnDrawGui.Connect` to use internal screen resolution
instead via: `GetGameResolution`
- Removed some rectangle code in `NetOverlayMetricSink::DrawBaseMetrics`
which doesn't seem to be used.

tweak(debug-net/netgraph): Respect screen resolution

---

code/components/extra-natives-five/src/WeaponExtraNatives.cpp
ext/native-decls/GetWeaponAnimationOverride.md

Adds a getter for [SET_WEAPON_ANIMATION_OVERRIDE](https://docs.fivem.net/natives/?_0x1055AC3A667F09D9), tested across all game builds (1604, 2060, 2189 and 2372).

feat(extra-natives-five): add GET_WEAPON_ANIMATION_OVERRIDE

---

code/components/citizen-server-impl/include/state/SyncTrees_RDR3.h

Idk if it's the right way to do this. I was used fivem SyncTrees as example.I did this becouse i wanted to use entityCreating event to block spawning some vehicles but GET_ENTITY_MODEL and GET_ENTITY_POPULATION_TYPE wasnt here
```
AddEventHandler('entityCreating', function(entity)
print(entity)
print(GetEntityTypeName(GetEntityType(entity)))
print(GetPopulationTypeName(GetEntityPopulationType(entity)))
print(GetEntityModel(entity))  
end)
function GetPopulationTypeName(type)
for k, v in pairs(entityPopulationTypes) do
if v == type then
return k
end
end
end
function GetEntityTypeName(type)
for k, v in pairs(entityTypes) do
if v == type then
return k
end
end
end
```

feat(server/impl): update data node structs for RDR3

---

ext/sdk/README.md
ext/sdk/resources/sdk-root/shell/src/resource-templates/csharp/descriptor.tsx
ext/sdk/resources/sdk-root/shell/src/resource-templates/descriptors-list.ts
ext/sdk/resources/sdk-root/shell/src/resource-templates/empty/descriptor.tsx
ext/sdk/resources/sdk-root/shell/src/resource-templates/js/descriptor.tsx
ext/sdk/resources/sdk-root/shell/src/resource-templates/lua/descriptor.tsx
ext/sdk/resources/sdk-root/shell/src/resource-templates/scaffolders-list.ts
ext/sdk/resources/sdk-root/shell/src/resource-templates/ts/descriptor.tsx
ext/sdk/resources/sdk-root/shell/src/resource-templates/ts/scaffolder.ts
ext/sdk/resources/sdk-root/shell/src/resource-templates/types.ts

Typescript template that uses ESBuild and clean builds using `.fxdkignore`
Updated the README.md to current build steps
Removed unnecessary imports from existing templates

feat(fxdk): Add Typescript resource template

---

ext/sdk/resources/sdk-root/shell/src/resource-templates/ts/scaffolder.ts

Fixes the oops on the manifest trying to use .ts files instead of .js files
The syntax supported by `.fxdkignore` isn't one to one with `.gitignore`, thus the need to use a wildcard after the directory ignore.

fix(sdk): .ts to .js for built files in manifest

---

code/components/gta-net-five/src/CloneExperiments.cpp

Fixes bug introduced in #1329 breaking non-OneSync servers.

Fix missed data size calculator function hook for RedM

---

data/client_rdr/citizen/common/data/gameconfig.xml

This should resolve `rage::scriptHandler::atDScriptObjectNode` pool overflow crashes.

Increase atDScriptObjectNode pool size for RedM

---

code/components/rage-formats-x/include/convert/gtaDrawable_five_rdr3.h

Should help with debugging converted assets in-game.

Set real drawable name when doing five->rdr3 drawable conversion

---

data/client_rdr/citizen/common/data/gameconfig.xml

Should resolve `CScriptEntityExtension` pool crashes.

Increase CScriptEntityExtension pool size for RedM

---

code/components/discord/src/DiscordPresence.cpp

This was requested by @Keyinator in response to @SaSiNO97 being angry
at there being a bug (citizenfx/fivem#1362) leading to the wrong line
being overridden from their viewpoint of 'correct line', curiously about
a day after this bug actually got fixed on the 'Latest' update channel.
At the risk of leading to another complaint at this code (unchanged ever
since 4fc76ead5e0e3336caba31f5327403225512ce1f except for a bug since
ce4d89e1a9770ab0810560f3bfdb0a2d161ac218 that got fixed within a day of
being reported as broken in citizenfx/fivem#1362) 'changing again', this
changes the override to replace the formatted string and not one of the
lines.
It does make one wonder why the override was targeting a line instead of
the full string, and it could indeed be likely that this was due to said …

feat(discord): support newlines in SET_RICH_PRESENCE

---

data/shared/citizen/scripting/v8/main.js

* Fixes: `TypeError: 'set' on proxy: trap returned falsish for key`
Additional info:
On Proxies: If the set() method returns false, and the assignment happened in strict-mode code, a TypeError will be thrown.

fix(scripting/v8): correct return value for proxy setter

---

code/components/gta-streaming-five/src/LoadStreamingFile.cpp

Fixes an issue where if you disconnect (not quit) and rejoin, .ytyp files wouldn't load properly and result into lower LOD map models being shown in the world.
Tested and gives expected results:
- Different .ytyp files (extracted from GTA V directly),
- Altered properties of archetypes in .ytyp files,
- Connect, disconnect, connect, disconnect, connect,
- Connect, disconnect, start single player,
- Altered properties of archetypes in .ytyp files,
- Connect, disconnect, unloading the resource with an altered .ytyp, connect,
- Above but: loading resource with an altered .ytyp
resolves #1340

fix(streaming/five): unload and reload original ytyp

---

code/components/extra-natives-rdr3/src/WeatherNatives.cpp

`SET_WEATHER_OWNED_BY_NETWORK`
Backport of [4ddeb62043d38a70814ec164d9567b9678e0ca6d](https://github.com/citizenfx/fivem/commit/4ddeb62043d38a70814ec164d9567b9678e0ca6d).

Weather ownership native for RedM

---

code/components/steam/src/SteamComponent.cpp

This PR fixes #1397 by only launching the Steam child if the name has actually changed.
The Steam component *should* be refactored at a later date to use the `OnRichPresenceSetTemplate` and `OnRichPresenceSetValue` events however, that requires a dependency inversion (`net` <-> `steam`) which is out-of-scope for this PR.

fix(steam): only update game name on change

---

code/components/voip-server-mumble/src/client.cpp

- fixes https://forum.cfx.re/t/fxserver-crashes-when-mumble-native-mumble-set-player-muted-is-invoked-sporadic/4838208
Fixes oversight in #1087
Getting/Setting a player muted would result in a crash if you manage to hit it right when a client is getting initialized and their username is still null.

fix(mumble): fix server crash when using MumbleSetPlayerMuted or MumbleIsPlayerMuted

---

code/components/citizen-server-impl/src/GameServer.cpp

* Fixes issue where a set of state bag changes (and potentially other callbacks) on start up were simply discarded.
fixes #1384

fix(server/impl): apply all state bag changes on startup

---

data/shared/citizen/scripting/lua/scheduler.lua

The playerTM and entityTM tables weren't available in the scope, since they were used in the definition of the variable itself.
Defining it as local one line before using it fixes this.

fix(statebags): Fix metatables on __unpack

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/shared/state/RlMessageBuffer.h

This (relatively untested) changeset will block REQUEST_CONTROL_EVENT routing based on a configurable policy.
Supported modes for the `sv_filterRequestControl` variable are as follows:
* **-1**: Default, equivalent to `2` at this time, but will also warn in console so users can fix stuff/be told to disable it.
* **0**: Off. Also disables the routing bucket/entity lockdown-based policy.
* **1**: Blocks control requests to entities controlled by players (currently, occupied vehicles only) that have existed for more than `sv_filterRequestControlSettleTimer` milliseconds (default 30000) - hereafter referred to as 'settled'.
* **2**: Blocks control requests to _all_ entities controlled by players.
* **3**: Blocks control requests to all entities controlled by players, and any 'settled' …

Block entity control requests

---

code/components/gta-game-rdr3/include/NetworkPlayerMgr.h
code/components/gta-net-five/src/CloneExperiments.cpp

Also resolved wrong `GetPlayerInfo` getter method of `CNetGamePlayer`, this actually could fix something.

Add diagnostic crash dialogue for GetGamerInfo related crashes for RedM

---

ext/cfx-ui/src/app/servers/servers.service.ts
ext/cfx-ui/src/app/servers/workers/servers.worker.ts

*Fixes the problem that caused us to have data from other games as well, e.g.:*
On rdr3, I have the tags for gta5 and of course there are not so many server on redm:
With this PR we now add the server to the workers *only* if it is the **same** game.
Result:

fix(ext/cfx-ui): was adding servers that aren't the right game

---

code/components/gta-net-five/src/CloneExperiments.cpp
code/components/gta-net-five/src/MumbleVoice.cpp

See `rage::netObject::GetPlayerOwner`. Experimental change - might cause more issues than it was meant to fix, but still would be useful for diagnosis of the specific group of crashes. Shouldn't affect FiveM in any case.
:BlessRNG:

Return nullptr if object player owner wasn't found in RDR3

---

code/components/scripthookv/src/VishCompat.cpp

Add support for b2612 in vish compat

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/components/gta-net-five/src/CloneManager.cpp

This change should resolve https://forum.cfx.re/t/ghosting-player-poisoning-due-to-many-components-weapons-applied-to-player-peds/4868864
Clone creation packets in RedM can be huge (>1200 bytes, more than the current limit), while increasing limit isn't a perfect solution, it should work for most cases. Tested locally with 2 clients, haven't found any issues, however, added a warning message on client informing player that there could be sync issues because of receiving a large packet, just in case.

Increase max sync packet length

---

code/components/citizen-scripting-mono/src/MonoComponentHost.cpp

Will now profile the whole GC run, i.e.: when code is being halted (stop world) and released (start world).

tweak(scripting/mono): profile GC stop/start world

---

code/components/conhost-v2/src/ConsoleHostGui.cpp

If user has scrolled up in the console, he no longer be automatically scrolled down

tweak(conhost): don't auto-scroll if not at the last line

---

code/components/extra-natives-rdr3/src/CameraNatives.cpp
code/components/gta-core-rdr3/src/PoolManagement.cpp

Example usage until merged / native generated
```
local cam = CreateCamWithParams("DEFAULT_SCRIPTED_CAMERA", 420.0, 420.0, 420.0, 420.0, 0.00 , 0.00, 420.00, false, 0)
while true do
Wait(0)
local camRight, camForward, camUp, camPosition = Citizen.InvokeNative(`GET_CAM_MATRIX` & 0xFFFFFFFF, cam, Citizen.PointerValueVector(),  Citizen.PointerValueVector(),  Citizen.PointerValueVector(),  Citizen.PointerValueVector())
print(camRight, camForward, camUp, camPosition)
end
````

feat(extra-natives/rdr3): add GET_CAM_MATRIX and unhashed pools

---

data/shared/citizen/scripting/lua/scheduler.lua

Leftovers from the old way of handling threads.

tweak(scripting/lua): Cleanup unused variables

---

data/client/citizen/common/data/ui/pausemenu.xml

Going through the new pausemenu.xml, these are the only "interesting" changes I have found.
This commit adds Legal and Credit tabs in the GAME header (You need to toggle contexts for one of these to show, can't have both at the same time.)
Also added the 'Display Text Chat' setting item, however, this would not work in older builds and would just appear as blank (https://i.imgur.com/vIpd6q2.png), so It can only be enabled if the 'b2699' context is enabled (With `PauseMenuActivateContext("b2699")`).

Add b2699 Pause Menu tabs

---

code/components/gta-core-rdr3/src/GameInitRage.cpp

Original report: https://forum.cfx.re/t/explosion-natives-no-longer-working-after-1436-31-update/4888502

Skip tunable checks for some natives on b1436 in RedM

---

code/components/extra-natives-rdr3/src/ShapeTestNatives.cpp

This native was/is missing for RDR3. This re-adds it.

feat(extra-natives/rdr3): GET_SHAPE_TEST_RESULT_INCLUDING_MATERIAL

---

code/components/extra-natives-five/src/ModelListNatives.cpp
ext/native-decls/GetAllVehicleModels.md

This native returns all vehicle models that are registered, it also will be unregister any vehicles in resources that get stopped.
This is my first PR relating to C++. I can't promise its perfect.
Test command:
```lua
RegisterCommand("spawnrandomcar", function()
local vehicles = GetAllVehicleModels()
local veh = vehicles[math.random(1, #vehicles)]
RequestModel(veh)
repeat Wait(0) until HasModelLoaded(veh)
local veh = CreateVehicle(veh, GetEntityCoords(PlayerPedId()), GetEntityHeading(PlayerPedId(), true, false)
SetPedIntoVehicle(PlayerPedId(), veh, -1)
end)
```

feat(extra-natives/five): Add GET_ALL_VEHICLE_MODELS native

---

ext/native-decls/GetConvar.md
ext/native-decls/GetConvarInt.md
ext/native-decls/SetConvarReplicated.md

Update `GetConvar`, `GetConvarInt` and `SetConvarReplicated` natives. 
Mainly provides descriptions and usage examples.

fix(native-decls): Update some Convar natives (GET_CONVAR, GET_CONVAR_INT and SET_CONVAR_REPLICATED)

---

code/components/extra-natives-five/src/GraphicsExtraNatives.cpp
ext/native-decls/GetWorldCoordFromScreenCoord.md

This functionality is often provided by the platform on game engines and some SA modifications, also, there are a lot of snippets implementing it out there, so I imagine that it would be a good addition to the platform.
I chose the native name and "namespace" grouping based on the `GET_SCREEN_COORD_FROM_WORLD_COORD` native.
The initial idea was to return just the world coords relative to the screen coords, but I realized that to suit the most common use case, which I imagine is mouse picking, the native would also need to return the normal vector.
If this is not the right way to do it, let me know and I'll make the necessary changes.

feat(extra-natives/five): add GET_WORLD_COORD_FROM_SCREEN_COORD

---

code/components/gta-streaming-five/src/PatchWeaponLimits.cpp
data/client/citizen/common/data/gameconfig.xml

Increased to resolve getting a pool error when adding a lot of weapon components.

tweak(game/five): increase CWeaponComponentInfo limit

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
ext/native-decls/ClearVehicleXenonLightsCustomColor.md
ext/native-decls/GetVehicleXenonLightsCustomColor.md
ext/native-decls/SetVehicleXenonLightsCustomColor.md

This PR implementing natives allowing to use custom (RGB) color for vehicles with xenon lights.
```c
void SET_VEHICLE_XENON_LIGHTS_CUSTOM_COLOR(Vehicle vehicle, int red, int green, int blue);
BOOL GET_VEHICLE_XENON_LIGHTS_CUSTOM_COLOR(Vehicle vehicle, int* red, int* green, int* blue);
void CLEAR_VEHICLE_XENON_LIGHTS_CUSTOM_COLOR(Vehicle vehicle);
```
Testing script: https://pastebin.com/3BUWSm9a

Custom colors for vehicle xenon lights

---

code/components/scripthookv/src/VishCompat.cpp

Just `getGameVersion`, as usual.

Add support for b2699 in vish compat

---

code/components/rage-scripting-rdr3/src/scrThread.cpp

This patch will fix crash during disconnection. REDM-9KX on b1436 and REDM-ED6 on b1491

Fix wrong offset for thread kill hook in RedM

---

code/components/extra-natives-five/src/WeaponExtraNatives.cpp
ext/native-decls/GetWeaponRecoilShakeAmplitude.md
ext/native-decls/SetWeaponRecoilShakeAmplitude.md

These natives will be useful to set a dynamic recoil for each weapon whether you need it or not
Tested on 1604 and 2699, it resets to the default recoil value if you reconnect/connect to another server

Add setter and getter for the recoil amplitude of weapons

---

ext/ui-build/loadscreen/package.json
ext/ui-build/loadscreen/yarn.lock

Building client from node v17 was not possible without manual workarounds because of webpack/webpack#14532, it got fixed in webpack/webpack@dcf3b02aaf407f0fc07354b20af5413296a56e58.

fix(ui-build): supports node v17

---

code/components/extra-natives-five/src/WeaponExtraNatives.cpp

Resolve a typo on GetWeaponDamageModifier's native getter. The function was dereferencing and casting to a type of uint16_t when it should have been a float.
This should resolve issue #1638

fix(extra-natives/five): GetWeaponDamageModifier

---

code/components/citizen-resources-core/include/StateBagComponent.h
code/components/citizen-resources-core/src/StateBagComponent.cpp
code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/components/gta-net-five/src/CloneManager.cpp

* Any client that owns an entity can now create its replicating state bags on the server.
* Clients will queue their state bag changes and send them after getting an ACK from the server (meaning the server now knows of the entity).
* State bag updates to clients are now being sent after the clone creation packets.
* State bag updates are not being sent to clients that just got a call to remove the associated entities.
resolves #1335 
resolves #1304

tweak(server): state bags can now be created by clients and replicated

---

code/components/extra-natives-five/src/DrawImNatives.cpp

Resolve an issue with crosshair convar init state:
Currently, crosshair convars are inited from DoCrosshairDraw's method. This method gets called when the game is done loading, thus overriding any replicated cvars the server is sending via 'setr' unless the client were to rejoin said server without fully closing the client via 'quit'.
To resolve this, we move these convars out of the method.
Looks a bit weird to have all these console variables init'd like this in the global scope, but it resolves the issue. I guess a better solution would be to have these variables declared as a shared pointer and then initializing them in an init method like other things do i.e. `g_use3dAudio` or `g_handbrakeCamConvar`.
If that's a better way to do it, let me know and I'll modify the PR, thanks!

fix(extra-natives/five): Crosshair convars init

---

code/components/citizen-resources-core/include/StateBagComponent.h
code/components/citizen-resources-core/src/StateBagComponent.cpp
code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/src/state/ServerGameState.cpp

* Fixed state bag changes being sent to players that are not in the same network scope.
- State bags no longer being sent to everyone when their target list is empty.
- Global state bag will still send to everyone (old behavior).
* Fixed state bag changes not being sent to players in the same network scope.
* Removed queueing of state bag's target registration, as this became obsolete.
Seems like the issues were (primarily) pre-existing errors that came to light with enabling clients to create state bags.
fixes #1691

fix(server): entity state bag sync with nearby players

---

code/components/citizen-resources-core/include/StateBagComponent.h
code/components/citizen-resources-core/src/StateBagComponent.cpp
code/components/citizen-resources-gta/src/EntityStateBags.cpp
code/components/gta-net-five/src/CloneManager.cpp

* Precreated state bags will get the proper targets on creation
Could be the cause of #1700 and several reports on Discord, but unable to test as I can't reproduce it.

fix(net/five): correct targets for precreated state bags

---

code/components/citizen-devtools/include/ResourceMonitor.h
code/components/citizen-devtools/src/ResourceMonitor.cpp
code/components/citizen-devtools/src/ResourceTimeWarnings.cpp

This will lessen the impact of the current Resource Monitor by removing a noticeable part of the ScRT pre- and post-run overhead.
Rundown of some changes:
* ResourceMonitor
- Removed the `std::unordered_multiset`, really slow for what they do, notoriously so.
- Repurposed the `tbb::concurrent_unordered_map` to take on the multiset's function.
- Only uses a single stopwatch per resource.
- Some branch prediction optimizations.
- Proper and more performant math changes.
* String formatting is at least twice as slow as a simple concatenation.
I've been running these changes for months while working on another project, have had no issues.

tweak(citizen-devtools): improve monitor performance

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
ext/native-decls/GetVehicleDashboardBoost.md
ext/native-decls/GetVehicleDashboardFuel.md
ext/native-decls/GetVehicleDashboardLights.md
ext/native-decls/GetVehicleDashboardOilPressure.md
ext/native-decls/GetVehicleDashboardOilTemp.md
ext/native-decls/GetVehicleDashboardRPM.md
ext/native-decls/GetVehicleDashboardTemp.md
ext/native-decls/GetVehicleDashboardVacuum.md
ext/native-decls/GetVehicleDashboardWaterTemp.md

Set of natives that get the state of the local player's current vehicle's dashboard.
Tested on b2699. The research was done so long ago I don't expect this struct or pattern has or ever will change.
Based on [ikt's GTAVDashHook](https://github.com/E66666666/GTAVDashHook)
I'm not sure how to handle allowing setting values without setting the entire struct so setters are omitted for now.

feat(extra-natives/five): dashboard getter natives

---

code/client/shared/Utils.cpp
code/client/shared/Utils.h
code/components/extra-natives-five/src/RuntimeAssetNatives.cpp
ext/native-decls/CreateRuntimeTextureFromImage.md

Add support for creating runtime textures from base64 data URLs

feat(extra-natives/five): add data URLs support to CreateRuntimeTextureFromImage

---

code/components/gta-net-five/src/CloneExperiments.cpp
code/components/gta-net-rdr3/include/netObject.h
code/components/gta-net-rdr3/src/netObject.cpp

This set of commits will hopefully resolve all the issues and crashes related to reconnect on OneSync servers after disconnection. Was only tested locally with CL2.

Fix RedM reconnection issues and crashes

---

code/components/extra-natives-five/src/EntityExtraNatives.cpp
ext/native-decls/GetPedDecorations.md

Intended usage is to retrieve the currently applied decorations and count if needed.
Tested patterns on 160x, 2372, 2628.
Tested with custom decorations (tattoos)

feat(extra-natives/five): GetPedDecorations

---

code/components/extra-natives-five/src/WaterExtraNatives.cpp
ext/native-decls/CreateDryVolume.md
ext/native-decls/RemoveDryVolume.md

This adds a new native that allows specifying a volume where water collision effects do not apply. This functionality is based on R*' way of disabling water collision under the casino.
This native allows volumes to be defined once and they will persist trough the whole game lifetime.
One question would be if it would be better to move the casino dry volume to this new collection of volumes too?

feat(extra-natives/five): DEFINE_DRY_VOLUME

---

code/components/citizen-scripting-mono/include/MonoComponentHostShared.h
code/components/citizen-scripting-mono/src/MonoComponentHostShared.cpp

Fixes several "stack overflow" issues that happen on locales/code pages that don't support utf8 by default on Windows. Back to using the wide char variant that does support Unicode.
* EXCEPTION_STACK_OVERFLOW at mono-2.0-sgen.dll,
* EXCEPTION_STACK_OVERFLOW at ntdll.dll.

fix(scripting-mono): back to Unicode trusted checks

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
code/components/gta-net-five/src/CloneExperiments.cpp
ext/native-decls/GetEntityFromStateBagName.md

Add a helper function as discussed on the [forums](https://forum.cfx.re/t/allow-statebagchangehandlers-to-be-a-partial-name/4963302/4).

feat: add GetEntityFromStateBagName helper

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
code/components/gta-streaming-five/include/EntitySystem.h

- Fixed wrong vtable method offset which was causing crash when using vehicle mods/extras natives.
- XBR vtable for CMapDataContents.
- GetHandlingData() now return proper struct.

Day one patch for b2802

---

code/components/extra-natives-five/src/RuntimeAssetNatives.cpp
code/components/gta-streaming-five/include/Streaming.h

Fixes #1756
Add forgotten `XBR_VIRTUAL_METHOD` for RDR3.

Resolve runtime texture unloading crash on b2802

---

code/components/extra-natives-rdr3/src/VehicleNatives.cpp
ext/native-decls/SetIgnoreVehicleOwnershipForStowing.md

Normally you'd have to set _SET_PLAYER_OWNS_VEHICLE(0xD0E02AA618020D17) and _SET_PLAYER_HUNTING_WAGON(0x6A4404BDFA62CE2C) to be able to stow carriables in a specific hunting wagon but that only limits ownership to a single player, so what this native does is it disables a couple of the checks related to that.

feat(extra-natives/rdr3): setter to ignore hunting wagon's stowing checks related to ownership.

---

code/client/clrcore/Math/GameMath.cs

Slight error in the calculation. This changed in November from newing up a Vector3 and using Vector.Length, which used to give the correct results.

Fixed vector length calculation in MathUtils.DirectionToRotation

---

ext/natives/codegen_out_native_lua.lua

This was set correctly in "parseArgumentType" from this post: https://forum.cfx.re/t/native-dui-handle-not-working-with-lua-5-4-and-fxv2-oal/4822448/2
but I noticed it still didn't work and figured it's because the PushObject call is still in int32_t as seen below:
```c
int64_t retval = nCtx.GetResult<int64_t>();
LuaArgumentParser::PushObject<int32_t>(L, retval);
```
Changing this to also return a int64_t should fix this issue.

fix(ext/natives): Fix long results for natives

---

code/components/citizen-server-impl/src/PlayerScriptFunctions.cpp

This solution seems a bit more correct, this searches only the start of the string, this shouldn't actually be a problem for now, but could avoid future issues in the case an identifier name would occur in the identifier itself.
This is also a bit more performant than the other solution.

fix(server/impl): Use rfind for GET_PLAYER_IDENTIFIER_BY_TYPE

---

ext/cfx-ui/src/cfx/apps/mpMenu/services/intl/intl.mpMenu.ts

Countries such as `pl` would match the non-expanded locale code in the home page server list only, instead of the consistent (and suggested) locale code `pl-PL`.
This fix makes locale codes without country expand to the language code as country, which *should* be the only case in which these occur in the OS.

fix(ext/cfx-ui): expand languages without country

---

data/shared/citizen/scripting/lua/scheduler.lua

* Errors coming from async ref functions were either sent to the callback or ignored, this muted errors that came from commands as described in #1809, this change will output them if no callback is present.
* Fixes cases where `false` is returned for any false-like value, even if e.g.: `nil` was expected. The fallback value `false`  is still used in case of an error.
resolves #1809

fix(scripting/lua): print error and allow nil returns on ref funcs

---

code/components/extra-natives-five/src/GraphicsExtraNatives.cpp
code/components/extra-natives-rdr3/src/GraphicsNatives.cpp
ext/native-decls/DisableWorldhorizonRendering.md

Implementing a native allowing to disable farlods/worldhorizon rendering (see `farlods.#dd` / `farlods_guarma.#dd`). Available in both FiveM and RedM. This might be useful for custom maps and cases when using island hoppers is not an option.
```c
void DISABLE_WORLDHORIZON_RENDERING(BOOL state);
```

Implement worldhorizon (farlods) rendering toggle native

---

code/components/extra-natives-five/src/NuiTxdSource.cpp

Compensate for changes that were made to a blit shader since b2189, which was mapping colors into the [0 .. 0.6] range. This rendered textures made by `RegisterPedheadshotTransparent` half-ish translucent and unwanted.
Tested on builds: 2189, 2372, 2545, 2612, 2699, 2802.
resolves: #1697

fix(extra-natives-five): translucency issue with ped headshots

---

code/components/gta-streaming-five/include/Streaming.h
code/components/gta-streaming-five/src/LoadStreamingFile.cpp
code/components/gta-streaming-five/src/StreamingFreeTests.cpp
code/components/gta-streaming-rdr3/src/Streaming.cpp

- Fixed custom map data files unloading disconnection crash (`REDM-2D`).
- Backported `DLC_ITYP_REQUEST` proxy mounter.
- Fixed some related patterns and structs.

Various streaming fixes and tweaks for RedM

---

code/components/citizen-scripting-mono/src/MonoComponentHostShared.cpp

Mono required `mono_profiler_install(...)` for `mono_profiler_install_gc(...)` to start throwing events on clients.

fix(scripting/mono): re-enable GC event callback on clients

---

code/components/gta-streaming-five/src/PatchMeshBlending.cpp

https://forum.cfx.re/t/disable-r-drawables-texture-compression/4852361
https://forum.cfx.re/t/mipmap-reduction/4893456
https://imgur.com/a/X38gRgn
Every version from 1604-2802
Used the resource linked in the first forum post
AI Peds + CL1 & CL2
Test script: https://pastebin.com/05TmzWqK
Creates 320 2048x2048 empty BC1 textures as a replacement for mp_headtargets/XXXX_diff_nnn_a_whi.ytd
Could not measure an impact on FPS when rendering 70 freemode peds.
Runtime should not be an issue at all because mip levels are still created starting from the increased scratch texture size and the engine does very efficient caching of the final ped texture composition.
Streaming custom clothing without svadhesive/adhesive doesn't seem to be an option.
I tested it by replacing base game drawables and …

fix(streaming/five): Prevent drawable texture quality degradation due to skin tone blending

---

data/shared/citizen/scripting/v8/index.d.ts

This change allows us to use the advantage of TypeScript's interface extending to add better typings for known exports in a project.
As the interface will be available globally, I called it `CitizenExports` to prevent conflict with other packages.
For example, you could do the following in a TypeScript module file to extend the exports interface:
```ts
declare global {
interface CitizenExports {
coolResource: {
doSomething(parameter: string): void;
}
}
}
```
Then in another file, you would get the auto complete:
```ts
global.exports.coolResource.doSomething('Snaily');
```

tweak(scripting/v8): improve exports typings

---

ext/cfx-ui/src/cfx/common/pages/ServerDetailsPage/ServerDetailsPage.tsx

Previously, when trying to search with an uppercase query, you wouldn't get a result.
This PR fixes this behaviour.
Before this PR:
https://user-images.githubusercontent.com/23613354/223552956-705f79f2-39a6-4fb5-b271-f03139edf10e.mp4
After this PR:
https://user-images.githubusercontent.com/23613354/223552991-bef302d8-5742-46fc-b51c-7b4af71d8d10.mp4

Make player/resource/tag filters in cfx-ui respect uppercase 

---

code/components/gta-streaming-five/src/PatchMeshBlending.cpp

An oversight in the initial PR. If the texture quality is set to "normal" the game will initialize the renderTarget to 256x instead of 512x and therefore also start at a "smaller" mip level.
This is not a guaranteed fix for the reported problem, as I can still not reproduce it. It does however fix incorrect logic.
Related issue: https://github.com/citizenfx/fivem/issues/1911

fix(game/five): PatchMeshBlending support for "nomal" texture quality

---

ext/natives/Makefile

make's target check failed when the `out` folder was already present, ignoring the creation of `out/v2`

fix(build-tools): creation of out/v2

---

code/premake5.lua
code/tools/ci/build_server_2.sh

* Disable mono v2 natives and game libraries for rdr3,
* Use renamed `Native` folder on Linux builds.

fix(build-tools): mono v2 rdr3 and Linux server folder fix

---

code/components/devtools-five/component.json
code/components/devtools-five/include/TimecycleEditor.h
code/components/devtools-five/src/TimecycleEditor.cpp
code/components/extra-natives-five/src/TimecycleNatives.cpp
code/components/gta-game-five/include/Timecycle.h
code/components/gta-game-five/src/Timecycle.cpp
ext/native-decls/CloneTimecycleModifier.md
ext/native-decls/CreateTimecycleModifier.md
ext/native-decls/DoesTimecycleModifierHasVar.md
ext/native-decls/GetTimecycleModifierCount.md
ext/native-decls/GetTimecycleModifierIndexByName.md
ext/native-decls/GetTimecycleModifierNameByIndex.md
ext/native-decls/GetTimecycleModifierStrength.md
ext/native-decls/GetTimecycleModifierVar.md
ext/native-decls/GetTimecycleModifierVarCount.md
ext/native-decls/GetTimecycleModifierVarNameByIndex.md
ext/native-decls/GetTimecycleVarCount.md
ext/native-decls/GetTimecycleVarDefaultValueByIndex.md
ext/native-decls/GetTimecycleVarNameByIndex.md
ext/native-decls/RemoveTimecycleModifier.md
ext/native-decls/RemoveTimecycleModifierVar.md
ext/native-decls/SetTimecycleModifierVar.md

A set of natives allowing people to create, modify and test timecycles in runtime:
```cpp
// Getter for SET_TIMECYCLE_MODIFIER_STRENGTH
float GET_TIMECYCLE_MODIFIER_STRENGTH();
// Getting all available modifiers
int GET_TIMECYCLE_MODIFIER_COUNT();
char* GET_TIMECYCLE_MODIFIER_NAME_BY_INDEX(int modifierIndex);
int GET_TIMECYCLE_MODIFIER_INDEX_BY_NAME(char* modifierName);
// Manipulating modifiers
int CREATE_TIMECYCLE_MODIFIER(char* modifierName); // returns -1 if failed to create
int CLONE_TIMECYCLE_MODIFIER(char* sourceModifierName, char* clonedModifierName); // returns -1 if failed to clone
void REMOVE_TIMECYCLE_MODIFIER(char* modifierName);
// Getting all available timecycle vars and their default values
int GET_TIMECYCLE_VAR_COUNT();
char* GET_TIMECYCLE_VAR_NAME_BY_INDEX(int varIndex); …
```

Timecycle editor and extra natives for FiveM

---

code/components/extra-natives-five/src/PatchNetworkChecks.cpp
code/components/extra-natives-five/src/VehicleExtraNatives.cpp

Added `game_enablePlayerRagdollOnCollision` allowing to activate native ragdoll on collision game logic.
Added `game_enablePlayerJumpRagdollControl` allowing to activate ragdoll on jump like in SP (Jump+R).
Moved `game_enableFlyThroughWindscreen` into a separate file.
https://user-images.githubusercontent.com/10367215/226429970-1574d853-4208-4b66-879a-3a1027776b01.mp4

Various network check bypass variables for FiveM

---

code/premake5.lua

* Disable rdr3 shared natives until fixed,
* Remove link to non-existent library/project on Linux.

fix(build-tools): rdr3 and Linux server build

---

code/components/extra-natives-five/src/WaterExtraNatives.cpp
ext/native-decls/SetWaterAreaClipRect.md

Added **SET_WATER_AREA_CLIP_RECT** - allows to place custom water file outside playable area
Fixed **LOAD_WATER_FROM_PATH** - wasn't handling path separator correctly, creating invalid paths like 'water_handler//water.xml' (two slashes instead of single one)

Add SET_WATER_AREA_CLIP_RECT & Fix LOAD_WATER_FROM_PATH path handling

---

code/client/clrcore-v2/Attributes.cs
code/client/clrcore-v2/Coroutine/Coroutine.cs
code/client/clrcore-v2/Coroutine/Scheduler.cs
code/client/clrcore-v2/Debug.cs
code/client/clrcore-v2/DynFunc.cs
code/client/clrcore-v2/Interop/EventsManager.cs
code/client/clrcore-v2/Interop/ExportsManager.cs
code/client/clrcore-v2/Interop/ExternalsManager.cs
code/client/clrcore-v2/Interop/MsgPackDeserializer.cs
code/client/clrcore-v2/Native/CustomNativeInvoker.cs
code/client/clrcore-v2/Native/Native.cs
code/client/clrcore-v2/Native/NativeTypes.cs
code/client/clrcore-v2/Remote.cs
code/client/clrcore-v2/ScriptInterface.cs
code/client/clrcore-v2/Shared/Player.cs
code/client/clrcore/Server/ServerWrappers.cs
code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp
code/components/citizen-scripting-mono/src/MonoComponentHostShared.cpp
ext/natives/codegen_out_cs_v2.lua

\* This PR does not activate the mono v2 runtime.
Crashes still present
* Sporadic SIGSEGV on resource stop, experienced by early test group but reason is still unknown. Requires a repro to properly investigate.
Coroutine & Scheduler
* Coroutines will force themselves back onto the main thread.
* Scheduler added locks for scheduling
* Scheduler null checks new coroutines
MsgPackDeserializer
* Fix wrong reinterpretation for double
* Read string even if not used
* Return maps as `ExpandoObject`s
DynFunc
* Fix `ShouldWeLogDynFuncError(...)` apparently `Exception.TargetSite` is `SecurityCritical` on mono
* Make it safe to create `DynFunc`'s from `Action<T...>` and `Func<T..., R>`
* Value type support
* `Remote` replaced with `SourceAttribute` flag
- `FiveM.Player` or any other constructible …

fix(clrcore-v2): teething troubles

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/SetEntityIgnoreRequestControlFilter.md

This will allow to use _sv_filterRequestControl_ but still allow to cover some edge cases that would discourage people from using it.
I believe that this will help with the adoption of _sv_filterRequestControl_ and especially _sv_filterRequestControl 4_.

feat(gamestate/server): add SetEntityIgnoreRequestControlFilter native

---

code/components/devtools-five/include/TimecycleEditor.h
code/components/devtools-five/src/TimecycleEditor.cpp
code/components/gta-game-five/include/Timecycle.h
code/components/gta-game-five/src/Timecycle.cpp

- Fixed crash when selecting a timecycle with no mod data.
- Timecycle search now case insensitive.
- Various code tweaks.

QOL improvements for FiveM timecycle editor

---

code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp
data/client/components.json
data/server/components.json
data/server_windows/components.json

* Will enable the mono v2 runtime on FiveM and Server
- Resources can use this runtime by defining `mono_rt2 'Prerelease expiring 2023-06-30. See https://aka.cfx.re/mono-rt2-preview for info.'` in their `fxmanifest.lua` file,
- User's C# assemblies need to be compiled against the `v2/` assemblies.
* RedM needs some internal native changes before it'll be activated,
* Replace mono_rt2 check with an expiration date and informative value.
Final commit for publishing mono_rt2

feat(scripting-mono): enable mono v2 runtime

---

code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp

Replace non-existent `SUCCEEDED` macro with FX's version

fix(scripting-mono-v2): wrong macro

---

code/client/clrcore-v2/Coroutine/Coroutine.cs
code/client/clrcore-v2/Coroutine/Scheduler.cs
code/client/clrcore-v2/ScriptInterface.cs
code/components/citizen-scripting-mono-v2/include/MonoScriptRuntime.h
code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp

Schedule tick calls with the core scheduler, aka Bookmark system or tick-less.
* Removes unnecessary mono-environment-switching costs when there's nothing to execute,
* Renamed parameters and added documentation on the `Scheduler`'s functions.

tweak(scripting-mono-v2): use core scheduler

---

code/client/clrcore-v2/Attributes.cs
code/client/clrcore-v2/BaseScript.cs
code/client/clrcore-v2/Interop/Events.cs
code/client/clrcore-v2/Interop/EventsManager.cs
code/client/clrcore-v2/ScriptManager.cs

* Events can now be registered through `Events.RegisterEventHandler(...)` from anywhere,
* BaseScripts can be attributed with `[EnableOnLoad(<true|false>)]` making it explicit if it should be automatically loaded or not,
* More documentation.

feat(clrcore-v2): global events and BaseScript instantiation control

---

code/client/clrcore-v2/BaseScript.cs
code/client/clrcore-v2/Coroutine/CoroutineRepeat.cs
code/client/clrcore-v2/DynFunc.cs
code/client/clrcore-v2/Interop/EventsManager.cs
code/client/clrcore-v2/Interop/Exports.cs
code/client/clrcore-v2/Interop/MsgPackSerializer.cs
code/client/clrcore-v2/Interop/ReferenceFunctionManager.cs
code/client/clrcore-v2/Native/NativeTypes.cs
code/client/clrcore-v2/ScriptInterface.cs
code/client/clrcore-v2/ScriptManager.cs

feat(clrcore-v2): full BaseScript enable-/disablement
* Allows `BaseScript`s to be enabled and disabled, including all of its ticks, events, exports, and commands
* Tick methods reworked for proper stop and continue logic
* Some internal method renaming to better convey what they do
tweak(clrcore-v2): DynFunc caching and fixes
* `Func.Create` will now cache its wrappers, reusing them when requested again
* Fixes static method wrapping as reported in https://github.com/thorium-cfx/mono_v2_get_started/issues/2
* Improve `[Source]` exception text to distinctly refer to constructors and not conversion operators
* Allow users to get the wrapped method, method is hidden in intellisense as use of it is for exceptional and advanced use cases only

feat(clrcore-v2): full BaseScript enable-/disablement + DynFunc caching and fixes

---

code/client/clrcore-v2/AssemblyInfo.cs
code/client/clrcore-v2/Debug.cs
code/client/clrcore-v2/DynFunc.cs
code/client/clrcore-v2/Interop/CString.cs
code/client/clrcore-v2/Interop/EventsManager.cs
code/client/clrcore-v2/Interop/ExportsManager.cs
code/client/clrcore-v2/Interop/LocalFunction.cs
code/client/clrcore-v2/Interop/MsgPackDeserializer.cs
code/client/clrcore-v2/Interop/MsgPackSerializer.cs
code/client/clrcore-v2/Interop/ReferenceFunctionManager.cs
code/client/clrcore-v2/Native/CustomNativeInvoker.cs
code/client/clrcore-v2/Native/MemoryAccess.cs
code/client/clrcore-v2/Native/NativeTypes.cs
code/client/clrcore-v2/Native/ScriptContext.cs
code/client/clrcore-v2/Native/ScriptContextData.cs
code/client/clrcore-v2/ScriptManager.cs
code/client/clrcore-v2/StateBag.cs

fix(clrcore-v2): CAS transparency fixes
* Fixes all CAS errors reported by SecAnnotate on the the client assembly.
* Plus an exception message fix for MsgPackDeserializer
tweak(clrcore-v2): more guidance on DynFunc exceptions
DynFunc exceptions run through exports, events, and reference functions can now give more details on the issue by rechecking types and their ability to be used.
Should reduce support requests and/or make them easy to solve

fix(clrcore-v2): CAS transparency fixes and better Dynfunc exception logging

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/GetEntityHealth.md

Fixes from what gottfriedleibniz posted on the [forums](https://forum.cfx.re/t/onesync-getvehiclebodyhealth-server-sided/4875372/7)

fix(state/fivem): parse proper fields for bodyHealth, add health

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp

If a bucket is in strict mode the event does not check if the entity has the ignoreRequestControlFilter flag set
This PR fixes it

fix(gamestate/server): support ignoreRequestControlFilter with strict lockdown mode

---

code/client/clrcore-v2/Attributes.cs
code/client/clrcore-v2/BaseScript.cs
code/client/clrcore-v2/Coroutine/Canceler.cs
code/client/clrcore-v2/Coroutine/Coroutine.cs
code/client/clrcore-v2/Coroutine/CoroutineMethods.cs
code/client/clrcore-v2/Coroutine/CoroutineRepeat.cs
code/client/clrcore-v2/Coroutine/Scheduler.cs
code/client/clrcore-v2/Coroutine/TimePoint.cs
code/client/clrcore-v2/ScriptInterface.cs
code/client/clrcore/Server/Entity.cs
code/client/clrcore/Server/Interfaces.cs
code/client/clrcore/Server/Ped.cs
code/client/clrcore/Server/Prop.cs
code/client/clrcore/Server/ServerWrappers.cs
code/client/clrcore/Server/Vehicle.cs

feat(clrcore-v2): more coroutine features
* await `Coroutine.Run(func)`, runs the function directly and allows awaiting it
* await `Coroutine.RunNextFrame(func)`, runs the function on the next frame and allows awaiting it
* await `Coroutine.WhenAny(...)`, awaits until the first awaitee finishes
* await `Coroutine.WhenAll(...)`, awaits until all awaitees finish
* `Coroutine.Schedule(func, delay)` to run func after delay
* `Coroutine.Schedule(func, delay, iterations)` to run func after delay for an x amount of iterations
* `Canceler` support for `Schedule`, `Delay`, and `WaitUntil`
* `Scheduler` and `Coroutine` use `TimePoint` for all absolute timing needs distinguishing it from `ulong` delay scheduling
* `Coroutine` internal rework
- Fixed exeption propagation
- Adding more completion …

feat(clrcore-v2): more coroutine features and moving server types to Server namespace

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp

This is a continuation of an old pull request I made regarding networked sounds #1316 
As discussed, I simply added a convar to disable the routing of these events.

feat(gamestate/server): disable networked sounds convar

---

code/client/clrcore-v2/Coroutine/Coroutine.cs
code/client/clrcore-v2/Interop/LocalFunction.cs
code/client/clrcore-v2/Interop/MsgPackSerializer.cs
code/client/clrcore-v2/Interop/ReferenceFunctionManager.cs
code/client/clrcore-v2/Native/MemoryAccess.cs
code/client/clrcore-v2/Native/Native.cs
code/client/clrcore-v2/StateBag.cs
code/client/clrcore/External/Camera.cs
code/client/clrcore/External/Checkpoint.cs
code/client/clrcore/External/Entity.cs
code/client/clrcore/External/ParticleEffects.cs
code/client/clrcore/External/Ped.cs
code/client/clrcore/External/Vehicle.cs
code/client/clrcore/External/VehicleWheelCollection.cs
code/client/clrcore/Math/v2/Color.cs

fix(clrcore-v2): allow use of Entity's MemoryAccess methods
* Clean up, rectify CAS, and add other helper functions in previously copied v1 `MemoryAccess.cs`.
* Move CAS transparency guarantee to MemoryAccess users.
* Use new MemoryAccess helper functions in Entity methods.
fix(clrcore-v2): make StateBag.Global public
resolves thorium-cfx/mono_v2_get_started#9
fix(clrcore-v2): exports/reffunc fixes
* Fix (a)sync exports calls
* Properly handle latest exception fixes for Exports and RefFuncs
* Shrink serialized data to interface properly with other runtimes

fix(clrcore-v2): MemoryAccess, StateBag.Global, & Exports/RefFunc fixes

---

code/client/clrcore-v2/Attributes.cs
code/client/clrcore-v2/BaseScript.cs
code/client/clrcore-v2/Interop/ExportsManager.cs
code/client/clrcore-v2/Interop/Types/CString.cs
code/client/clrcore-v2/Native/Native.cs
code/client/clrcore-v2/Native/Types/NativeTypes.cs
code/client/clrcore-v2/Native/Types/OutString.cs
code/client/clrcore-v2/ScriptManager.cs
code/premake5.lua

feat(clrcore-v2): KeyMapAttribute
Support for:
* `[KeyMap("Command", description, inputMapper, inputParameter)]`
* `[KeyMap("+Command", description, inputMapper, inputParameter)]`
* `[KeyMap("-Command")]` non-key-binding
tweak(clrcore-v2): shared library update
`ServerScript` & `ClientScript` are now present in both client and server environments, but will only load in their respective environment.
fix(clrcore-v2): several bug fixes
* `Tick -=` will now properly remove previous registered tick methods.
* Small file/folder reorganization and allows recursive files in v2 folders to be included.
* Exports return `dynamic` enabling compiler code generation for dynamic types.
* `OutString` reduced to 1 implicit conversion operator, allowing the compiler to use that one for `(object)` casts and …

tweak(clrcore-v2): KeyMapAttribute, shared library tweaks, and several bug fixes

---

code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/components/extra-natives-five/src/PedExtraNatives.cpp
code/components/gta-streaming-five/src/PatchPedRandomVariation.cpp
code/components/scripthookv/src/VishCompat.cpp
data/client/citizen/common/data/ui/pausemenu.xml
ext/native-decls/IsPedComponentVariationGen9Exclusive.md

- Tweaked server game state data nodes and net events.
- Added new gamepad sprint option in `pausemenu.xml`.
- Scripthook game version enum entry.
- Fixed random crash when using `SET_PED_RANDOM_COMPONENT_VARIATION`.
- Added `IS_PED_COMPONENT_VARIATION_GEN9_EXCLUSIVE` native allowing to "filter" stub gen9ec assets that R* added into a main dlcpack.

Day one patch for b2944 support

---

code/client/clrcore/Math/Vector3.cs

Current math library is designed for a Y-up coordinate system, while GTA has a Z-up RH coordinate system. No one should've used these in their previous state.
* Swap forward and up vectors
* Add `Vector3.Forward` and `Vector3.Backward` so users don't need to know if they need the LH or RH version.
fixes #1899

fix(clrcore): adjust vector directions for Z-up

---

code/components/citizen-devtools/src/ResourceTimeWarnings.cpp
code/components/citizen-server-fxdk/src/SdkIpc.cpp

And ignore the `_cfx_internal` resource for sdk resmon

fix(sdk): don't instantiate resmon when there's no resource manager

---

code/client/clrcore/External/Blip.cs

This function will add a cone to the blip (see picture).  This can be used for for example camera's or whatever you like!
The following code snippet is an example of how you can use the 'new' function.
```cs
using System;
using CitizenFX.Core;
using CitizenFX.Core.Native;
using static CitizenFX.Core.Native.API;
namespace TEST
{
public class Class1 : BaseScript
{
public Class1() 
{
RegisterCommand("testblip", new Action<int, List<object>, string>(async (src, args, raw) =>
{
int hash = (uint)GetHashKey("ch_prop_ch_cctv_cam_02a");
RequestModel(hash);
while (!HasModelLoaded(hash)) await Delay(10);
Vector3 v = GetEntityCoords(Game.PlayerPed.Handle, true);
int obj = CreateObject(GetHashKey("ch_prop_ch_cctv_cam_02a"), v.X, v.Y, v.Z, false, false, false);
while (!DoesEntityExist(obj)) await …
```

tweak(scripting/csharp): add blip cone function

---

code/client/clrcore/External/Ped.cs

This is an alternative pull request to #1949 . After some discussing with thorium and de C# scripters, we decided this would be the best option out of the two pull requests. This pull request puts the ai blip features in the ped class instead of making a separate class. You can decide which one to use.

tweak(scripting/csharp): Add ai blip functions

---

code/client/citicore/console/Console.Variables.h
code/components/citizen-server-impl/src/InfoHttpHandler.cpp

Someone accidentally `sv_icon` instead of `load_server_icon`, not knowing that `sv_icon` was internal and doesn't have any validation logic.
This adds `ConVar_Internal` to deal with this and block modification to ConVars that shouldn't be writable.
It should be noted this makes any value that wants to set its value have to use `SetRawValue` but for this use case should be fine.
[Here is the thread in the FiveM discord](https://discord.com/channels/192358910387159041/1122205927794298920/1122206106937208882) or 1122205927794298920 in case the link doesn't work.

fix(convar): add ConVar_Internal and mark sv_icon and version as internal

---

code/client/citicore/console/Console.Variables.cpp
code/client/citicore/console/Console.Variables.h
code/components/extra-natives-five/src/PatchNetworkChecks.cpp
code/components/glue/src/BindNetLibrary.cpp

This fixes not properly resetting `game_*` ConVars on disconnect.
This also fixes another bug found when trying to fix this that improperly resets all `ConVar_Replicated` flags even if the ConVar had it as its default, which allowed the client to change `game_*` natives on servers that don't have it set by default.

fix(extra/patches): fix values not being reset on server disconnect

---

code/components/gta-core-five/src/CrashFixes.cpp

Fixes R* bug (null pointer dereference) introduced in 2802.0 (and not fixed in 2944.0) related to the new RTTI system. One of the most popular crashes on these builds.
Also disable another null pointer dereference crash fix (on newest builds) since it was fixed by R* 🎉

Fix crashes during streaming objects removal on FiveM b2802+

---

code/components/extra-natives-five/src/WeaponExtraNatives.cpp
ext/native-decls/SetWeaponsNoAimBlocking.md

This native is meant to the way for server creators to disable builtin weapons aim blocking mechanic. For non-player peds the `SET_PED_ENABLE_WEAPON_BLOCKING` native can be used. However, it won't work for local player ped as the logic for this specific case is different. The "weapon blocking" state is synchronized between players. This native could be useful for specific some gamemodes and content creators making custom weapons (used like `weapon_digiscanner`, `weapon_fireextinguisher`, etc).

Add `SetWeaponsNoAimBlocking` for FiveM

---

code/client/clrcore-v2/Coroutine/CoroutineMethods.cs
code/client/clrcore-v2/Interop/EventsManager.cs
code/client/clrcore-v2/Interop/Types/CString.cs
code/client/clrcore-v2/Native/Types/OutString.cs
ext/natives/codegen_out_cs_v2.lua

fix(clrcore-v2): use (u)long types on natives when requested
* Adds overrides for (u)long types for v2 native generation to compensate for `type.nativeType` being just `int` on our 64 bit integer friends.
fix(clrcore-v2): Coroutine.Run, OutString cast, and transparency issue
* Only run Coroutine.Run(...) functions directly when we're on the main thread, otherwise we run it next frame.
* Fix return type of Coroutine.Run<T>(...);
* Move OutString -> CString conversion operator.
* Fix CAS transparency issue with EventHandlerSet's + operator for `Delegate` types (don't know why SecAnnotate didn't pick up on this).
resolves thorium-cfx/mono_v2_get_started#22

fix(clrcore-v2): native long/ulong types, Coroutine.Run, OutString cast, and transparency issue

---

code/client/clrcore-v2/Attributes.cs
code/client/clrcore-v2/BaseScript.cs
code/client/clrcore-v2/DynFunc.cs
code/client/clrcore-v2/Remote.cs

Allows commands and keymappers to create a different DynFunc that remaps and converts the arguments into different parameters. Can be requested by using: `[Command("...", RemapParameters = true)]`
Note that this isn't yet tested thoroughly.
resolves thorium-cfx/mono_v2_get_started#19

feat(clrcore-v2): command parameter remapping

---

code/components/extra-natives-five/src/NativeFixes.cpp
code/components/extra-natives-rdr3/src/NativeFixes.cpp
code/components/gta-core-five/include/RageParser.h
code/components/gta-core-rdr3/component.lua
code/components/gta-core-rdr3/src/RageParser.cpp
code/components/rage-scripting-rdr3/src/scrEngine.cpp

See https://github.com/citizenfx/natives/pull/892
Additional changes related to FiveM:
- Reworked rage parser code to use the modern component exporting approach.
- Added `enumElemCount` to `parMemberDefinition` to avoid manual iterations.
In order to make it also work in RedM, these additional changes was made:
- Implemented side-by-side rage parser support for RDR3.
- Fixed a bug that was breaking native handlers overriding.

Clamp attribute index in `SET_PED_COMBAT_ATTRIBUTES` for FiveM and RedM

---

code/components/extra-natives-five/src/NativeFixes.cpp

changes the cleanup condition to one that doesn't interfere with StartScriptFire initiated fires but still effectively prevents orphaned fire IDs
tested on b1604 w/ scripts provided by the original fix dev (PR https://github.com/citizenfx/fivem/pull/2041), their tests still pass & script fires now function as expected again

fix(extra-natives/five): relaxed entity fire id cleanup

---

code/components/citizen-server-impl/src/ClientRegistry.cpp
code/components/citizen-server-impl/src/PlayerScriptFunctions.cpp
ext/native-decls/DoesPlayerExist.md

This was something I [asked about a while ago](https://forum.cfx.re/t/is-player-active-native/5041300) and have finally gotten around to implementing.
In testing `DOES_PLAYER_EXIST` I found that `m_clientsByNetId` doesn't release the oldNetId which broke some of the use cases for this native, so we reset it.
I'm not sure if this breaks anything anywhere, but please correct me if I'm wrong

Add DOES_PLAYER_EXIST native

---

ext/native-decls/RegisterKeyMapping.md

Document alternate keybinding syntax (~!) by adding a usage example. 
Tested example on fxDK.

feat(native-decls): Update RegisterKeyMapping.md

---

code/client/launcher/GameCache.cpp

This was forgotten in the initial push for b2944 support.

Game cache required entries for FiveM b2944

---

ext/cfx-ui/src/cfx/base/serverUtils.ts
ext/cfx-ui/src/cfx/common/services/servers/lists/FavoriteServersList.ts
ext/cfx-ui/src/cfx/common/services/servers/source/WorkerSource.worker.ts
ext/cfx-ui/src/cfx/common/services/servers/source/listSorter.ts

When you are searching for a specific server in the server list, sometimes the name of your community might be used in other project descriptions, making a user struggle to find the server he is looking for.
For example, if you type in the search bar names like Echo, RSM, GLife, Impulse, or many others, you will end up with non-relevant servers putting random names into their project description and showing up at the top of the list because they've more boost power (Except if the server is pinned).
The goal of this change is to sort in a better way when the user inputs a server name (or project name). If the project's name starts with was the user is inputting, it will be sorted above the top boosted servers.
I have added this gif to show you how it will impact your search.
One issue with …

feat(cfx-ui/sorting): add a new server list sorting for relevant ^server name search

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp

Fix for issue reported on forums, memory offsets used by CurrentGear and NextGear natives turned out to be incorrect / were reporting unexpected results: https://forum.cfx.re/t/native-getvehiclecurrentgear-is-reading-from-the-wrong-address-in-memory/5159163
The variables these offsets get assigned to were swapped by mistake, this was discovered by comparing offsets calculated at runtime with a known good Manual Transmission mod which reports expected numbers (linked in forum thread)
Tested the variable swap under all currently supported builds, the resulting offsets now line up nicely with the mod

feat(extra-natives/five): read current & next gear from correct offsets

---

code/components/citizen-resources-core/src/StateBagComponent.cpp

This is a possible solution for #2159

fix(core/sbac): don't try get dataLength if m_curBit is greater than m_maxBit

---

ext/natives/codegen_out_cs_v2.lua

Typo making `ulong` to `Vector3*` compatibility functions output wrong code.

fix(build-tools): rectify ulong -> Vector3* code generation

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp

Fix for abusing AddVehiclePhoneExplosiveDevice & DetonateVehiclePhoneExplosiveDevice by hackers
Exploit allow hackers to send explosion as other player ( The one who is network owner of car )
Cheaters have been employing two primary methods to carry out this exploit:
AddVehiclePhoneExplosiveDevice: This native function allows cheats to attach explosive devices to in-game vehicles. These devices can then be triggered remotely, causing an explosion at a location determined by the cheater.
DetonateVehiclePhoneExplosiveDevice: This native function is used by cheaters to remotely detonate the explosive devices attached to vehicles. This is how they send explosions as if they were other players.

AddVehiclePhoneExplosiveDevice & DetonateVehiclePhoneExplosiveDevice fix

---

code/components/citizen-server-gui/src/ServerGui.cpp

At one point, the `gamename` variable moved to the fallback console context, which made the code here only ever show 'unknown' instead of an actual game name (like 'FXServer/gta5').
As a fix, we will look this up in the fallback console context as well.

fix(server/gui): 'FXServer/unknown' in console title

---

code/components/citizen-resources-gta/src/PopulationCreationFunctions.cpp
code/components/devtools-five/src/WorldEditor.cpp
code/components/extra-natives-five/src/PedExtraNatives.cpp
code/components/extra-natives-five/src/RuntimeAssetNatives.cpp
code/components/gta-streaming-five/include/EntitySystem.h
code/components/gta-streaming-five/src/EntitySystem.cpp
code/components/gta-streaming-five/src/PatchStreamingPreparation.cpp
code/components/gta-streaming-five/src/PlacementHacks.cpp
code/components/gta-streaming-five/src/PopulationCreationHooks.cpp
code/components/gta-streaming-five/src/TextureStreamingLimits.cpp
code/components/gta-streaming-rdr3/component.lua
code/components/gta-streaming-rdr3/include/EntitySystem.h
code/components/gta-streaming-rdr3/src/EntitySystem.cpp

Plus some code cleanup.
The event work in the same way as in FiveM (`populationPedCreating`), see [docs](https://docs.fivem.net/docs/scripting-reference/events/list/populationPedCreating/).
Example from docs with `CS_dutch` model:

Population ped creation event for RedM

---

code/components/gta-net-five/src/CloneExperiments.cpp
code/components/gta-net-five/src/MumbleVoice.cpp

Patterns should future-proof this code from getting broken again, hopefully. Plus added a bit of explanation in the comments. Reworking this code to use `rage::netInterface::GetPlayerFromGamerId` might be considered in the future, however this function was heavily obfuscated in latest game builds, plus using it will add performance overhead. Simple memory layout hacks may work for some time.
Plus added a shared function to get net object from entity, it should decrease hard-to-read code duplication and ensure consistency.

Improve player talking hook for FiveM

---

code/components/gta-net-rdr3/src/CoreNetworking.cpp

Yet another attempt to fix spawn of peds with "bad models" in RDO. Fortunately, we don't need such measures. But unfortunately, we don't have an obvious way to opt-out from these beforehand as for now, so it's always a build-by-build investigation.
Original report: https://forum.cfx.re/t/broken-human-peds-for-specific-models-and-other-ambient-ped-outfits-not-syncing/5111409

Ignore certain ped model sync blocking tunable in RedM

---

code/components/citizen-server-impl/component.lua
code/components/citizen-server-impl/include/NoticeLogicProcessor.h
code/components/citizen-server-impl/src/NoticeLogicProcessor.cpp
code/components/citizen-server-impl/src/ServerNucleus.cpp
code/components/http-client/include/HttpClient.h
code/components/http-client/src/HttpClient.cpp

This PR changes the server startup notice handler from Lua to a tailored logic processor written in C++. The needs of the notice system were reviewed before the change and the new processor's feature set should cover all that's needed.
Please make sure to update the dynamically served JSON to adhere to the new schema before shipping an FXServer update, otherwise there will be no data for the new notice internals to process. I can provide the updated JSON if necessary.

tweak(server): scriptless startup notices

---

code/components/citizen-server-impl/src/NoticeLogicProcessor.cpp

Better instantiation syntax for the Notice Logic Processor, should build fine for Linux now
+ added default:break; case to a switch that lacked it for completeness sake (no more compile time warning)

fix(server): fix startup notices linux build

---

code/components/gta-core-rdr3/src/PatchTrainConfigCrash.cpp

Fixes a base game crash caused by an invalid train config index on remote train net objects. Sentry crash identifier: `REDM-18W4` (b1491).

Train config index crash workaround for RedM

---

docs/building.md

- Python deprecated distutils in [PEP 632](https://peps.python.org/pep-0632/) and removed it in 3.12

tweak(docs/building): add note when using python 3.12+

---

vendor/chromium/mojo/public/tools/bindings/pylib/mojom/parse/lexer.py
vendor/chromium/mojo/public/tools/bindings/pylib/mojom_tests/fileutil_unittest.py
vendor/chromium/mojo/public/tools/bindings/pylib/mojom_tests/generate/data_unittest.py
vendor/chromium/mojo/public/tools/bindings/pylib/mojom_tests/generate/generator_unittest.py
vendor/chromium/mojo/public/tools/bindings/pylib/mojom_tests/generate/module_unittest.py
vendor/chromium/mojo/public/tools/bindings/pylib/mojom_tests/generate/pack_unittest.py
vendor/chromium/mojo/public/tools/bindings/pylib/mojom_tests/parse/ast_unittest.py
vendor/chromium/mojo/public/tools/bindings/pylib/mojom_tests/parse/conditional_features_unittest.py
vendor/chromium/mojo/public/tools/bindings/pylib/mojom_tests/parse/lexer_unittest.py
vendor/chromium/mojo/public/tools/bindings/pylib/mojom_tests/parse/parser_unittest.py
vendor/chromium/mojo/public/tools/bindings/pylib/mojom_tests/parse/translate_unittest.py

This allows compilation of the mojo project with python 3.12.
* Replace `imp` module with the newer `importlib.util` module that was added in 3.4.
* This allowed for successful builds on my test machines (windows and linux),
* Some reports say that `setuptools` or `distutils` was still missing and is needed to build the natives, I wasn't able to replicate this.
Note: setuptools can can installed as follows: `pip install setuptools` or `py -3 -m pip install setuptools`

fix(build): update mojo files for python 3.12

---

data/shared/citizen/scripting/lua/scheduler.lua

When awaiting a promise that has already been rejected it will return the promise value rather than throwing an error.
```lua
local function fn(cb) cb('err') end
CreateThread(function()
local p = promise.new()
fn(function(err)
p:reject(err)
end)
print(Citizen.Await(p))
print('hello world')
end)
```

fix(scripting/lua): error when awaiting a rejected promise

---

code/client/clrcore/InternalManager.cs

This should've be null checked and ignored. We'll fix it like this as it's not performance critical and we'll need to remove it anyway when we'll update the libraries.
fixes: #2265

fix(clrclore): ignore captured traces if null

---

code/client/clrcore/External/Ped.cs

The Ped class for _GetHeadBlendData was using the local player Ped rather then the Ped its representing, this update fixes that.

Fix (clrcore/fivem) Ped class using wrong handle

---

code/components/extra-natives-five/src/GraphicsExtraNatives.cpp
code/components/rage-graphics-five/include/DrawCommands.h
code/components/rage-graphics-five/src/DrawCommands.cpp
ext/native-decls/DrawGlowSphere.md

Original report: https://forum.cfx.re/t/graphics-drawsphere-renders-only-one-sphere-per-frame/2500594?u=disquse
```c
void DRAW_GLOW_SPHERE(float posX, float posY, float posZ, float radius, int colorR, int colorG, int colorB, float intensity, BOOL invert, BOOL marker);
```
This native allowing to draw a "glow sphere" as a marker or overlay. Limited to 256 spheres per single frame.
Example script: https://pastebin.com/05wnuWCD

Glow sphere drawing system in FiveM

---

code/components/extra-natives-five/src/InterfaceExtraNatives.cpp
ext/native-decls/GetPauseMapPointerWorldPosition.md

This PR implements a new native that returns the world position where the pause map pointer hovers.
Tested on 1604/2189/2802/2944

feat(extra-natives/five): implement 'GET_PAUSE_MAP_POINTER_WORLD_POSITION'

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/docs_improvement.yml
.github/ISSUE_TEMPLATE/feature_request.yml.disabled
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci/build_linux.sh
.github/workflows/ci/build_windows.sh
.github/workflows/ci_build.yml
.github/workflows/issue_closed.yml
.github/workflows/issue_opened.yml
.github/workflows/pr_opened.yml
ext/native-doc-gen/build.sh

This feature focuses on extending our GitHub experience, it includes:
* Issue templates and links to other repos
* PR template
* Automation of labelling and closing of issues/PRs
* CI build checks
- FiveM & RedM
- FXServer (Windows only, Linux is disabled for now)
* build.sh curl required explicit --http1.1 to work on GitHub runners

feat(github): templates and CI

---

code/components/citizen-scripting-lua/src/LuaScriptNatives.cpp

Fixes #2183 and the forums post referenced (SetPlayerRoutingBucket, SetEntityRoutingBucket natives)
Repro
```lua
RegisterCommand("setBucket", function(source, args)
SetPlayerRoutingBucket(tostring(source), (tonumber(args[1] or "100") or 100))
end, false)
RegisterCommand("getBucket", function(source)
print(("You are in bucket %s"):format(GetPlayerRoutingBucket(tostring(source))))
end, false)
```

fix(scripting/lua): correct LuaNativeContext constructor

---

code/components/gta-streaming-five/include/EntitySystem.h

Fixes #2307
Fix the reported regression.
...
Fixing the reported regression.
`gta-streaming-five`
...
**Game builds:**  2802, 2944, 3095
Fixes #2307

Fix typo in `CVehicle::GetHandlingData` (b2802 and b2944)

---

code/components/citizen-server-impl/src/InitConnectMethod.cpp

Invalid ticket lengths could lead to an out-of-bounds read, crashing the server. This is relatively easy to exploit as well (just change the field in an existing valid cfxTicket to `FF FF FF FF`, and send it on to a server you want to crash) and therefore a bit risky - I've been trying to report this privately for ages (see the Sep 6, 2023 commit date!), but it seems to have slipped through the cracks and not been acted on at all for the past _four months_.
Make the server not crash when sending an invalid ticket.
Using larger types.
Server
**Platforms:** Windows. Should work on Linux as well.

fix(server/impl): initConnect addition overflow

---

code/components/extra-natives-five/src/PlayerNatives.cpp
code/components/gta-game-five/include/NetworkPlayerMgr.h

Fixed a regression introduced in b3095 + minor code tweaks & cleanup.
...
By adding b3095 check in `DECLARE_ACCESSOR` and replacing raw accessor with a proper method call.
...
FiveM, Natives
...
**Game builds:** 3095, 2944, 2372, 2060, 1604
Issue `#2` from this report https://forum.cfx.re/t/a-couple-of-problems-since-the-last-updates/5200554

Update `CNetGamePlayer` accessors to support b3095 in FiveM

---

code/components/citizen-server-impl/include/state/SyncTrees_Five.h

Adds research for `CPlayerAppearanceDataNode` and `CPedAppearanceDataNode` with most names documented. Code is behind a `#if 0` whilst the parsed data is unused

feat(onesync): ped and player appearance data node research

---

code/client/shared/CfxRGBA.h
code/components/extra-natives-five/include/GamePrimitives.h
code/components/extra-natives-rdr3/include/GamePrimitives.h
code/components/extra-natives-rdr3/src/GraphicsNatives.cpp

- Reworked draw origin system so now it uses proper structs, making the code to be way more readable.
- Reworked ScriptIM drawing so now it uses in-game system directly.
- This (hopefully) fixes flickering when using `DRAW_(BOX|POLY|LINE)` natives.
- Vertex ordering in `DRAW_POLY` is different now (like in GTA5).
- Added support for `DRAW_BOX` and `SET_BACKFACECULLING` (works as in GTA5).

Graphics natives fixes and improvements for RedM

---

code/components/rage-input-five/src/InputHook.cpp

Custom bits of UI (NUI focus, as well as the F8 console/dear ImGui) do this already, which makes the game's mouse cursor (such as in the pause menu) behave differently.
This commit solves this by hooking up the QueryMayLockCursor event to a flag specifying if the cursor is visible.
Feature was requested in DMs by @summeryukata at some point:
> is there a way to make fivem not confine the cursor
> like, when i have f8 open i can drag it out no problem, but if I pause it keeps it locked to the window
Add a little feature for consistency.
Implements the feature.
FiveM, rage:input:five
**Game builds:** 1604-3095
(force-pushed as commit signing did not work first try - used the wrong key for the committer identity, then forgot `-S` the second time)

tweak(input/five): release cursor capture for the game's cursor

---

code/components/gta-core-rdr3/src/PatchArtificialLightsCrash.cpp

This PR is intended to fix a crash that randomly occurs after using the `SET_ARTIFICIAL_LIGHTS_STATE` native in RedM. A more detailed technical explanation can be found in the code.
...
By patching a function that is causing the crash.
...
RedM
...
**Game builds:** 1311, 1355, 1436, 1491
Fixes an issue reported here: https://forum.cfx.re/t/setartificiallightsstate-crash/5188901

Fix artificial lights crash in RedM

---

.github/workflows/pr_opened.yml

Enable GitHub PR evaluating workflow to label PRs and continue compile checks
Giving this workflow the `issue` write permission.
Note: I was unable to test this on my own repos, but research shows it's related to missing the `issues` write permission (can come from our organization). One would expect this to be fine with `pull-requests` write permissions.
GitHub
GitHub Runners
**Platforms:** GitHub Runners

fix(github): give permissions to label PRs

---

code/components/gta-core-five/src/GameAudioState.cpp

...
By adding the proper offset.
...
RedM
...
fixes https://forum.cfx.re/t/crash-gta-core-rdr3-10f9c

fix(rdr3/audio): add pattern offset for asynchronousAudio

---

code/components/extra-natives-rdr3/src/GraphicsNatives.cpp

Fixing a regression introduced in #2268, basically because of this typo we're skipping draw origin index "0".
By fixing a typo.
RedM
**Game builds:** 1311, 1355, 1436, 1491
Fixing an issue reported by Kono in DMs.

Draw origin index typo in RedM

---

code/components/citizen-playernames-five/src/HookGamerInfo.cpp

To make the gamer tags crew component to work on game build 3095.
This is achieved by patching a function that was preventing this functionality from working (some additional unknown "privilege" checks or so).
FiveM
Addresses the problem reported in this forum topic:
https://forum.cfx.re/t/gamer-tag-crew-component-does-not-work-on-newest-3095-game-build/5201652

Fix gamer tags crew component in FiveM b3095

---

code/components/gta-core-five/src/DisableCameraShake.cpp

The way how this functionality was implemented before is very fragile and got broken in b3095. The one-way nopping was also breaking the ability to disable this option after disconnecting from a server. So it was decided to rework it a bit.
By reworking the way how this functionality was implemented.
FiveM
**Game builds:** 1604, 2060, 2189, 2372, 2545, 2612, 2699, 2802, 2944, 3095
Addresses the problem reported in this forum topic (`#3`):
https://forum.cfx.re/t/a-couple-of-problems-since-the-last-updates/5200554

Rework camera shake toggle convar in FiveM

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp

* if we accept these willy-nilly, clients could possibly OOM the server, or do a one-to-many make-shift DoS on larger a server
* the size limits here are kept high to keep compatibility with people who "misuse" state bags
* sane defaults for servers that don't send large data via state bags would be `set rateLimiter_stateBagSize_rate 1000` and `set rateLimiter_stateBagSize_burst 4000`
Fix the possible abuse cases for state bags, though this doesn't cover all of them [theres already another pr sitting](https://github.com/citizenfx/fivem/pull/2108) that allows better filtering.
The rate and size of state bags similar to `msgServerEvent`
Server
Fixes #2361

fix(state/statebag): filter frequent & large data from client

---

code/components/steam/component.lua
code/components/steam/src/SteamComponent.cpp

This contains a fix for my test server's non-ASCII host name being broken in Steam presence, and some assorted fixes for issues caught along the way (`steamname.txt` returning mojibake, and leftover SteamChild processes lingering).
These changes may not be as meaningful if/when FiveM and RedM are assigned an actual AppID and can use the native rich presence functionality, but for the time being they solve stuff being broken randomly.
Fix some issues that showed up regarding Steam presence.
(.. also, the 'consice' typo is still there in the template)
See commit messages for details.
Client (both FiveM and RedM), `steam` component. Also updates a vendor library, this _wasn't_ tested on the Linux build as I do not have a Linux system available at this time - this should however work.
**Game …

Assorted Steam presence fixes

---

.github/workflows/pr_opened.yml

Enable labelling of external fork PRs, also continuing builds of PRs targeting `RedM`, `ScRT: Lua`, etc.
Finally found the documentation:
> GitHub only grants read access tokens for `pull_request` events, at most. If you encounter an `Error: HttpError: Resource not accessible by integration`, it's likely due to these permission constraints. To resolve this issue, you can modify the `on:` section of your workflow to use `pull_request_target` instead of `pull_request`
- https://github.com/actions/labeler?tab=readme-ov-file#permissions
Removed `issues: write` permission as shown in the example, see link.
GitHub
GitHub
**Platforms:** GitHub Runner

fix(github): PR labeling permission

---

code/components/extra-natives-five/include/GamePrimitives.h
code/components/extra-natives-five/src/GamePrimitives_Im3D.cpp
code/components/extra-natives-rdr3/include/GamePrimitives.h
code/components/extra-natives-rdr3/src/GraphicsNatives.cpp

Add `GET_WORLD_COORD_FROM_SCREEN_COORD` native for RedM.
By adapting related FiveM code for Red Dead Redemption 2 and RedM.
RedM
**Game builds:** 1311, 1355, 1436, 1491
Fixes #1977 
Demonstration:
[Video](https://github.com/citizenfx/fivem/assets/10367215/0c3e3e1c-2ec0-44c7-88c1-5e5dae1195fd)

Add `GET_WORLD_COORD_FROM_SCREEN_COORD` for RedM

---

ext/natives/codegen_types.lua

The goal of this PR is to add typedefs necessary for updating and building natives for RedM and update  the `native-doc-tooling` submodule. See [citizenfx/native-doc-tooling](https://github.com/citizenfx/native-doc-tooling/commit/a8f791baa8505579acde770a8ec558baad5d936c) changes.
This PR achieves the goal by adding the missed typedefs.
FiveM, RedM, Natives
**Game builds:** -

Add typedefs for RedM and update native-doc-tooling

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp

The goal of this PR is to fix an oversight where the "can stand on top" flag (`g_overrideCanPedStandOnVehicle`) and the vehicle map (`g_canPedStandOnVehicles`) weren't reset after disconnection from a server. Also, tweak some natives to use `getAndCheckVehicle` to avoid code duplication.
This PR achieves the goal by resetting the flag and map during `OnKillNetworkDone`. Also, it tweaks the relevant code to use the `getAndCheckVehicle` helper.
FiveM
**Game builds:** 1604, 2060, 2189, 2372, 2545, 2612, 2699, 2802, 2944, 3095

Reset "can stand on top" flag and map after disconnection in FiveM

---

data/shared/citizen/scripting/v8/index.d.ts
data/shared/citizen/scripting/v8/main.js

By default any event that is listened more than 10 times will trigger a log error saying that there may be a memory leak. 
In some cases users may want to listen more than 10 times to a specific event this patch allow to not display a log message in those cases by setting the correct value to the setMaxEventListeners.
It's not a real problem, but often users will print this error saying it's the cause of a bug (but it's not) and it's misleading.
This PR allow to configure the max listeners count so a developer can set it according to his code behavior.
FiveM, RedM, Server, ScRT: JS
N/A

feat(scripting/v8): allow to set the max listeners count

---

code/components/gta-core-five/src/PatchPedPropsLimit.cpp

The game has a "soft limit" for the number of available ped props per anchor per model. This patch is intended to fix this limit to allow players to stream more custom ped props.
This PR achieves the goal by patching a set of game functions that clamp 32-bit ped prop indices to 8-bit integers. More detailed explanations are available in the code.
FiveM
**Game builds:** 1604, 2060, 2189, 2372, 2545, 2612, 2699, 2802, 2944, 3095
Addressing a platform suggestion left on the forum:
https://forum.cfx.re/t/request-to-increase-head-prop-limit-in-fivem/5201885

Workaround for ped props limit in FiveM

---

code/client/clrcore-v2/BaseScript.cs
code/client/clrcore-v2/Coroutine/Scheduler.cs
code/client/clrcore-v2/Interop/Types/ScriptSharedData.cs
code/client/clrcore-v2/ScriptInterface.cs
code/components/citizen-scripting-mono-v2/include/MonoScriptRuntime.h
code/components/citizen-scripting-mono-v2/include/ScriptSharedData.h
code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp

Enable scheduling tick calls from non-main threads, this is necessary to call back into the runtime (on the main thread) after external libraries used async/await with `Task/Task<T>` and we had nothing else scheduled. This didn't work before.
By removing its dependency on the Bookmark system (not thread-safe) and replacing it with a simplified version that achieves the same goal, but thread-safe.
ScRT: C#
Server and client
**Game builds:** 2802
fixes thorium-cfx/mono_v2_get_started#23

fix(scripting-mono-v2): allow scheduling from non-main threads

---

code/client/launcher/premake5.lua
code/components/sticky/src/LaunchIntercept.cpp

Since b6cc153df04ec066b01f7647ca150a684501844a blocks the client from running on Windows 7 or 8, these builds aren't needed anymore, as they served as a workaround for Windows before 8.1 not supporting high-entropy virtual addresses, leading to the logic in [`hook::get_unadjusted`](https://github.com/citizenfx/fivem/blob/66d052957b28a5102eba86fad5947e40b22597dc/code/client/shared/Hooking.h#L82) not working.
When merging this PR, keep in mind:
1. The change in `sticky` should be mirrored in `adhesive` in `fivem-private` as well.
2. If incremental builds do not remove old binary artifacts, the non-ASLR binaries should be removed manually.
Clean up the build output and remove unneeded executables.
Dropping the unneeded non-ASLR builds.
FiveM, RedM …

tweak(client): remove non-ASLR game executables

---

code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp

Bump mono v2's pilot date allowing users to use it for another 3 months
By setting the next date to 30-06-2024
ScRT: C#

tweak(scripting/mono-v2): bump pilot date

---

code/components/gta-core-rdr3/src/PoolManagement.cpp

The goal of this PR is to prevent pool error crashes from confusing our players.
See [67d0d60](https://github.com/citizenfx/fivem/commit/67d0d60fc2da64a82c8a0c08d5c1fe5d2c374940) for more details.
By removing the confusing extra warning.
RedM
**Game builds:** 1311, 1355, 1436, 1491

Don't mention gameconfig in pool errors in RedM

---

ext/cfx-ui/src/cfx/common/services/servers/transformers.ts

Remove server variable from filtered object to prevent rendering it in the component.
Added exception for new server variable in transformers file
FiveM
fixes #2367

fix(ext/cfx-ui): added exception for sv_disableClientReplays

---

code/client/clrcore-v2/Attributes.cs
code/client/clrcore-v2/BaseScript.cs
code/client/clrcore-v2/Native/Native.cs

- allows the client to use `[NuiEvent("NuiEventName")]` to receive Nui messages
Add similar attributes as used by `EventHandler` for Nui
Adds new `NuiEventAttribute` and registers it via `RegisterNuiCallback`
ScRT: C#
RedM

feat(mono-rt2): add NuiEvent attribute

---

code/client/clrcore-v2/Attributes.cs
code/client/clrcore-v2/BaseScript.cs

- keymap natives are not currently supported by RedM, using these would result in RedM crashing
Block the usage of KeyMap on RedM until input mappings are made
Throw a not implemented exception the native is called
ScRT: C#
RedM

fix(mono-v2): disallow KeyMap to be used on RedM

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
ext/native-decls/GetVehicleGearRatio.md
ext/native-decls/SetVehicleGearRatio.md

These new natives will allow developers to create scripts to create custom gear ratios for vehicles.
I added the memory editing stuff to VehicleExtraNatives.cpp to allow me to create the 2 new natives.
float GetVehicleGearRatio(Vehicle vehicle, int gear);
void SetVehicleGearRatio(Vehicle vehicle, int gear, float ratio);
FiveM, Vehicle, Lua, JS, C#
**Game builds:**  3095,2944,2802,2699,2612,2545,2372,2189,2060,1604

feat(extra-natives/five): GET_VEHICLE_GEAR_RATIO and SET_VEHICLE_GEAR_RATIO 

---

code/components/citizen-scripting-lua/src/LuaScriptRuntime.cpp

Call `__close` metamethod on to-be-closed variables ([added in Lua 5.4](https://www.lua.org/manual/5.4/manual.html#3.3.8)) when an uncaught error occurs. Before this change variables would be closed only if the function/event/script execution ended without an error.
This PR calls the `lua_resetthread` method, when handling an error case, which unwinds the stack and closes all to-be-closed variables present there.
ScRT: Lua

fix(scripting/lua): Fix not closing to-be-closed variables on error

---

code/components/citizen-scripting-lua/src/LuaScriptNatives.cpp

Introduces faster OAL natives for RedM when using ``use_experimental_fxv2_oal true`` on the Lua 5.4 ScRT 
By including the ``NativesRDR.h`` header file that is compiled and copied into citizen-scripting-lua/src. 
RedM, ScRT: Lua
**Game builds:**  1491.18
Tested with scripts utilising Lua 5.3, MonoV1, JS and Lua 5.4 (without OAL) ScRT's. With all behaving as intended

feat(scripting/lua): redm oal natives

---

ext/natives/codegen.lua

Commit https://github.com/citizenfx/natives/commit/e6f473573f6eb7e2921b2ef48668117cbbe84bbb changed the native name from '_SET_PED_HAIR_COLOR' to 'SET_PED_HAIR_TINT' which makes the RPC native definition invalid.
We now also check for alias matches when generating RPC decl. in codegen and apply client-native aliases to RPC natives. This allows us to keep RPC native naming in sync with client-native changes while maintaining backward compatibility with old native naming (like on the client side).
FiveM, Natives (RPC)
**Game builds:** 2699 
fixes #2549
fixes #2447
fixes https://forum.cfx.re/t/5226975

tweak(natives/rpc): Use client-native names and apply aliases

---

code/components/citizen-playernames-five/src/HookGamerInfo.cpp

The fix introduced in d1b35aa (#2358) didn't resolve some broken scenarios. This PR is meant to resolve everything.
Reworking the original fix to cover all possible scenarios where gamer tags weren't working as intended on b3095.
FiveM

Better gamer tag crew component fix for b3095

---

code/components/rage-formats-x/include/convert/gtaDrawable_five_rdr3.h
code/components/rage-formats-x/include/convert/phBound_five_rdr3.h
code/components/rage-formats-x/include/rmcDrawable.h

Fix crash when models with embedded textures crash on unload
RedM converter

fix(tool/formats): five -> rdr3 embedded textures crash on unload

---

code/components/citizen-server-gui/src/PlayerList.cpp
code/components/citizen-server-impl/include/GameServerNet.h
code/components/citizen-server-impl/src/GameServerNet.ENet.cpp
code/components/debug-net/src/NetDebug.cpp
code/shared/net/PacketNames.h

This makes it so if a player times out, instead of getting packet hash as hex they'll get the actual packet name

feat(net): attribute proper packet names for timeout

---

code/components/extra-natives-five/src/InteriorExtraNatives.cpp
ext/native-decls/SetEmitterProbeLength.md
ext/native-decls/SetInteriorProbeLength.md

Allow servers to customize the probe distance used in `CPortalTracker`.
All dynamic entities own an instance of `CPortalTracker`. It is used to detect traversal from and into interiors, through portals and other related actions. 
By default the probing function inside `CPortalTracker`'s tick/update function probes downwards 4.0 units, trying to extract the interior the entity is in from collision data (staticboundsstore).
In many cases this will not work, leading to ~30 hard coded special cases based on interior archetype hash. Rockstar extends the probing distance for these interiors, most notably in `xs_arena_interior` to 150.0f.
By adding a new FiveM native `SET_INTERIOR_PROBE_LENGTH` to give servers individual control of game behaviour depending on their needs.
- The override value is …

feat(extra-natives/five): Add `SET_INTERIOR_PROBE_LENGTH` for FiveM

---

code/components/citizen-scripting-v8/src/V8ScriptRuntime.cpp

Due to the increasing amount of users using the JS runtime, some users are starting to hit the heap size limit and crashing, this increases the heap limit to match system memory, copying behavior from the [mono project](https://github.com/mono/mono/blob/38b0227c1ce0c53058a5d78d080923435132773a/mono/utils/memfuncs.c#L246) for [sgen](https://github.com/mono/mono/blob/38b0227c1ce0c53058a5d78d080923435132773a/mono/sgen/sgen-memory-governor.c#L502).
It should be notes that this caps at 4GB for some reason, I don't currently have time debug this but its likely a Node limitation.
Setting the isolate heap size to the physical memory size
SCRT: JS
**Game builds:** Tested, changes aren't build specific.
**Platforms:** Windows, needs testing on Linux.
Supersedes #1796

tweak(citizen-scripting-v8): increase heap size per isolate to match physical memory size

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp

* This game event is sent when a client tries to change state values on a remotely owned entity.
* Allow to block this game event from being routed to target clients to prevent potential abusive uses.
Introducing a new ConVar called 'sv_enableNetworkedScriptEntityStates' that allows blocking of the 'SCRIPT_ENTITY_STATE_CHANGE_EVENT' game event (routing is enabled by default).
FiveM, RedM, Server
**Game builds:** 2699
fixes #2553

tweak(gamestate/server): allow blocking of ScriptEntityStateChangeEvent

---

code/components/gta-core-five/src/PatchPedCompExpressionsLimit.cpp

This PR aims to fix a bug where 32-bit component indices were clamped to 8 bits in ped component expression mods related functions, which was breaking expression mods on components with indices greater than 255.
This goal is achieved by patching certain functions to prevent them from clamping component indices to 8 bits.
FiveM
**Game builds:** 1604, 2060, 2189, 2372, 2545, 2612, 2699, 2802, 2944, 3095 
Addresses the problem reported in this forum topic:
https://forum.cfx.re/t/increase-255-limit-for-ped-heel-height/5229225

Workaround for ped component expression mods limit in FiveM

---

data/client_rdr/citizen/common/data/gameconfig.xml

This PR increases several RDR pool sizes, allowing for the creation of more AMVs, fragments, timecycle boxes, and other elements.
Editing gameconfig.xml
RedM

tweak(data/rdr3): increase pools size

---

code/components/citizen-resources-client/src/ConsoleScriptFunctions.cpp
code/components/discord/src/DiscordPresence.cpp
ext/cfx-ui/src/assets/languages/locale-en.json
ext/cfx-ui/src/cfx/apps/mpMenu/settings.tsx

Requested in https://forum.cfx.re/t/5018677
Allow users to either completely disable Discords Rich Presence status or only show the current game version without displaying any game status.

feat(discord): user toggle for rich presence

---

code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/state/ServerSetters.cpp

Fixes a client-crash when calling physics-altering natives on an object that was created by `CreateObjectNoOffset` on the server-side.
We now populate the `CGlobalFlagsDataNode` with the needed flag bits on object creation so the owning client doesn't crash when pushing node updates in the 'Update' method.
FiveM, Server
**Game builds:** 2060, 2699, 3095
fixes #2583

fix(gamestate/server): Populate CGlobalFlagsDataNode on object create

---

data/client/citizen/common/data/gameconfig.xml

When using ropes, we ran into some limitations and the poolSize might've been the cause. Also when using the `SetRopesCreateNetworkWorldState` native, we were receiving errors of the pool size being full. I couldn't find anything related to the `CNetworkRopeWorldStateData` pool and how it could be edited/increased, so thought it might be using the normal `ROPE` pool
A simple pool size increase in `gameconfig.xml`. RDR has a size of 48, GTA originally had a size of 12 and I bumped it up to 32.
FiveM
N/A
Wasn't able to compile - didn't have the environment setup for it, but this change _shouldn't_ impact compilation anyways?

feat(data): Increased PoolSizes `ROPE` 12 -> 32 & `ropeData` 8 -> 24

---

code/components/gta-core-five/src/CrashFixes.DrawHandler.cpp

When colliding, some objects may hit a codepath that expects a crCreature to be created and that requires the entity to have a valid drawhandler, which invisible objects might not/won't have.
Checks for a valid crCreature before running some object collision logic.
FiveM
**Game builds:** 2372, 3095.
**Platforms:** Windows.
Fixes uncle-oklahoma-king

fix(game/five): fixes a crash caused by colliding objects without a drawhandler

---

code/components/citizen-resources-gta/src/ResourcesTest.cpp
code/components/gta-core-rdr3/src/PatchTrainTrackCrashes.cpp
code/components/gta-core-rdr3/src/PatchTrainTrackFileOverride.cpp

This PR adds the manifest statement `replace_traintrack_file`, which allows resource developers to override the default railway config file that is located at `common:/data/levels/rdr3/traintracks.xml`. This enables developers to create entirely custom railway networks without having to work around the base game's train tracks.
Since RDR2 was not initially designed to handle user-generated railroad data, this PR also includes several patches to improve stability.
The manifest statement is parsed from the `fxmanifest` file in the same location as the other statements, in `code/components/citizen-resources-gta/src/ResourcesTest.cpp`. Because this functionality is RedM specific, it has been placed in an `ifdef` guard checking for `IS_RDR3`. When a developer includes `replace_traintrack_file` …

feat(rdr3): Manifest statement for custom train tracks

---

ext/system-resources/resources/chat/html/App.ts

Currently, when using the included system-resource chat, it does not update the scroll position of the chat window, nor does it unhide the chat window when new chat messages are received.
With the change from Vue 2 to Vue 3, watchers were changed to be shallow, so they only react when a new value is assigned but won't trigger when changing a nested value. By setting the watcher to be a deep watcher again, the chat now scrolls automatically to the last message and shows up briefly when in 'when active' mode.
Server, system-resources: chat
**Server build:** 8823 

fix(system-resources/chat): scroll to bottom and show chat on new message

---

code/components/gta-core-five/src/CrashFixes.PhysicalCyclicAttachment.cpp

Game is missing a "is parent attachment" check on a common physical attach codepath, such check is present on other parts of the game.
Makes sure physicals can't attach themselves in a cyclic manner.
FiveM
**Game builds:** 2060, 3095.
**Platforms:** Windows.
Fixes `spring-mirror-island`

fix(game/five): prevent physical attachments from becoming cyclic

---

ext/natives/codegen.lua
ext/natives/codegen_out_markdown.lua

Removing leading and trailing backticks from the native summary section breaks formatting if the summary only contains formatted code.
Removal of the regex pattern matching for leading and trailing backticks in the doc string parse function when native md is being generated.
See issue https://github.com/citizenfx/natives/issues/1124 for a showcase of the mismatch between client and server native docs.
Natives
fixes https://github.com/citizenfx/natives/issues/1124

fix(natives/rpc): Keep code fencing in doc summary

---

code/components/net/src/NetLibrary.cpp

Allow the server to pass a specific endpoint using deferrals to a specific player.
- Fetching handover json data and overriding the server's endpoints if an endpoint value exists in handover
FiveM & RedM
Tested passing a custom endpoint
Documentation about handover https://docs-backend.fivem.net/docs/scripting-manual/nui-development/loading-screens/
```lua
-- Server script
AddEventHandler('playerConnecting', function(_, _, deferrals)
local source = source
deferrals.handover({
endpoints = { "127.0.0.1" }
})
end)
```

feat(net): support dynamic server endpoints using handover

---

code/components/rage-device-five/src/HookInitialMount.cpp

**The issue:**
The application seems to get stuck in a loop when cloud files are
accessed, this is caused by users installing their GTA on the cloud,
causing the game to neither load, nor 'gracefully' exit.
**The solution:**
To correct this, we simply get the file attributes and check if
the following flag is set: `FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS`. If
it's set, we return an invalid handle, so it's passed down the stack.
Once this errors, `FatalError` under `OpenArchiveWrap` will be
triggered. I have modified the message so any affected clients are
notified in the event this occurs.

fix(rage-device/five): Error out on cloud files

---

code/client/clrcore/External/Game.cs
code/client/clrcore/External/Model.cs
code/client/clrcore/External/RelationshipGroup.cs
code/client/clrcore/External/WeaponAsset.cs
code/client/clrcore/Math/Matrix.cs
code/client/clrcore/Math/Matrix3x3.cs
code/client/clrcore/Math/Quaternion.cs
code/client/clrcore/Math/Vector2.cs
code/client/clrcore/Math/Vector3.cs
code/client/clrcore/Math/Vector4.cs

Fix potential null reference exceptions in clcore.
Instead of using ``left.Equals(right)`` where left could be null, leading to a null reference exception, we check both left and right for being null before.
FiveM, RedM, Client, ScRT: C#
fixes #1312

fix(clcore): Adjust "==" and "!=" operators to fix null reference exceptions

---

data/shared/citizen/scripting/v8/main.js

Fixes issue where raw event listeners weren't triggered without standard subscribers.
Skips payload deserialization when no standard event subscribers are present.
Fixing these issues in js scripting event function
ScRT: JS

fix(scripting/v8): raw event listeners

---

code/components/citizen-resources-core/include/StateBagComponent.h
code/components/citizen-resources-core/src/StateBagComponent.cpp
code/components/citizen-scripting-core/src/ResourceScriptFunctions.cpp
ext/native-decls/GetStateBagKeys.md
ext/native-decls/StateBagHasValue.md

The modifications in this pull request introduce two new natives along with supporting methods for state bags.
`STATE_BAG_HAS_VALUE`: This native is designed to eliminate unnecessary deserialization of state bag values. It serves the purpose of determining whether a value exists for a specific key within the state bag without the need for full deserialization.
`GET_STATE_BAG_KEYS`: This native expands the utility of state bags by enabling the construction of custom models around the state bag without the necessity to manually check each key for existence. This enhancement streamlines the process of working with state bags and facilitates the creation of more efficient and organized models.
FiveM, RedM, Server,
**Game builds:**  2944

feat(net/client): Add state bag methods

---

data/client_rdr/components.json

Enable mono v2 scripting runtime on RedM.
Mind you, it's still in beta, breaking changes and crashes are expected.
By adding it to the components
RedM, ScRT: C#
RedM client up to start up
**Game builds:** None

feat(mono-v2): Enable mono v2 on RedM

---

code/client/clrcore-v2/Client/RedM/AssemblyInfo.cs
code/client/clrcore-v2/Client/RedM/Entity.cs
code/client/clrcore-v2/Client/RedM/Game.cs
code/client/clrcore-v2/Client/RedM/Model.cs
code/client/clrcore-v2/Client/RedM/Ped.cs
code/client/clrcore-v2/Client/RedM/Pickup.cs
code/client/clrcore-v2/Client/RedM/Player.cs
code/client/clrcore-v2/Client/RedM/Prop.cs
code/client/clrcore-v2/Client/RedM/Vehicle.cs
code/client/clrcore-v2/Client/RedM/World.cs
code/client/clrcore-v2/Game/Shared/Game.cs
code/client/clrcore-v2/Game/Shared/Interfaces.cs
code/client/clrcore-v2/Shared/IEntity.cs
code/client/clrcore/External/Game.cs
code/premake5.lua

Add same helper methods that FiveM has
Start implementing base classes for RedM.
RedM, SCRT:C#

feat(mono/redm): initial works for rdr

---

code/components/conhost-v2/include/ProductionWhitelist.h
code/components/extra-natives-five/src/DrawImNatives.cpp

This PR aims to implement support for the `cl_crosshair_t` [command from CS:GO](https://totalcsgo.com/commands/clcrosshairt). The `cl_crosshair_t` command allows players to customize their crosshair to a "T" style by removing the top line of the crosshair.
- **Command Implementation**: Added the `cl_crosshair_t` command to toggle the "T" style crosshair.
```cpp
static ConVar<bool> cl_crosshair_t("cl_crosshair_t", ConVar_Archive, false);
```
- **Drawing Logic Update**: Modified the `DoCrosshairDraw` function to conditionally skip drawing the top vertical line of the crosshair when `cl_crosshair_t` is enabled.
```cpp
// draw top vertical crosshair line if cl_crosshair_t is disabled
if (!cl_crosshair_t.GetValue())
{
int iInnerTop = iCenterY - iInnerCrossDist - iBarThickness / 2;
int …
```

feat(extra-natives/five): support for cl_crosshair_t command

---

code/components/citizen-server-impl/include/state/SyncTrees_Five.h

Serialize CPedAttachDataNode
By using the Serialize method instead of parsing/unparsing and checking this datanode doesn't contain more data (was checked on 3258)
FXServer
Was tested on 2944 & 3095 by creating a vehicle client-side and attaching the player to the vehicle, then using `GetEntityAttachedTo`  (who is calling `CBaseAttachNodeData`) to check if the native return the vehicleID
Here is the code i used to do the test
```lua
-- Client side
RegisterCommand('space', function()
local playerPed = PlayerPedId()
local vehicleModel = GetHashKey('adder')
RequestModel(vehicleModel)
while not HasModelLoaded(vehicleModel) do
Wait(500)
end
local playerCoords = GetEntityCoords(playerPed)
local playerHeading = GetEntityHeading(playerPed)
local vehicle = CreateVehicle(vehicleModel, …
```

feat(netsync): serialize CPedAttachDataNode

---

code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/state/ServerSetters.cpp

* Serialize CVehicleCreationDataNode
* Serialize CVehicleCreationDataNode instead of Parsing/Unparsing and checking this data node was complete (was checked on the 3258 dump)
* m_unk5 was usesSpecialFlightMode (when the vehicle is a plane and use the special flight mode)
FXServer
Was tested on 2944 & 3095 by creating a vehicle server-side (and checking if the vehicle was created successfully)
Here is the code i used to do the test
```lua
RegisterCommand("test", function(source)
local player = GetPlayerPed(source)
local coords = GetEntityCoords(player)
local veh = CreateVehicleServerSetter(`shamal`, "plane", coords.x, coords.y, coords.z, 0)
print(DoesEntityExist(veh)) -- return true
end, false)
```

feat(netsync): serialize CVehicleCreationDataNode

---

code/components/citizen-scripting-lua/src/LuaScriptRuntime.cpp
data/shared/citizen/scripting/lua/scheduler.lua

- Respect the `__tostring` metamethod on tables when outputting an error message.
- Prevent errors when no value is passed to the `error` function.
Magic.
- ScRT: Lua
**Platforms:** Window
Resolves #2359.

Improve Lua error handling

---

code/components/gta-net-five/src/MumbleVoice.cpp
code/components/voip-mumble/include/MumbleClient.h
code/components/voip-mumble/include/MumbleClientImpl.h
code/components/voip-mumble/src/MumbleClient.cpp
code/components/voip-mumble/src/MumbleClientState_Channel.cpp
ext/native-decls/MumbleDoesChannelExist.md

To add the ability to check if channels exist, which is usefull to avoid issue #2677
Additionally changed the insert call for channels to emplace (same way as done in users) and cache the widened channel name before a for loop where this was not done yet.
It adds the native `MUMBLE_DOES_CHANNEL_EXIST` which allows scripts to check if a mumble channel exists before executing a native on said channel ensuring that the native actually has effect.
FiveM & RedM (voip/mumble)
**Game builds:** 9073
fixes #2677

feat(voip/mumble): Add MUMBLE_DOES_CHANNEL_EXIST native

---

data/client/citizen/common/data/gameconfig.xml

Currently by default, fwPortalSceneGraphNode is set to 400, servers with many interiors and in turn lots of portals, this can cause a game crash. its possible to simply add this pool to the config to increase it.
currently it says "Unknown Pool full - 400", which makes sense because fwPortalSceneGraphNode is missing from the config therefore its unknown.
Adding the pool to the gameconfig and increasing its value to prevent game crashes with many interiors loaded
...
making the pool accessable to the gameconfig.
...
FiveM
...

feat(data): Add fwPortalSceneGraphNode pool to gameconfig

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/GetVehicleHornType.md

Adding a server side getter to the client side native `START_VEHICLE_HORN`
by reading the HornTypeHash bit in the CVehicleAppearance data node.
FXServer/FiveM
**Game builds:** 3095 
**Platforms:** Window
Was tested by using StartVehicleHorn client side, then getting the hornType value server side.
```lua
-- Client side
RegisterCommand("setHorn", function()
local veh = GetVehiclePedIsIn(PlayerPedId(), false)
StartVehicleHorn(veh, 1000000, GetHashKey("HELDDOWN"), false)
end)
-- Server Side
RegisterCommand("hornType", function(source, args)
local playerPed = GetPlayerPed(source)
local veh = GetVehiclePedIsIn(playerPed, false)
if GetVehicleHornType(veh) == GetHashKey("HELDDOWN") then
print("yes")
end
end)
```
To test it, use this snippet, use the setHorn command, then the hornType command

feat(onesync/natives): add GetVehicleHornType

---

code/components/citizen-server-impl/include/ScriptDeprecations.h
code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/CanHeliTailBoomBreak.md
ext/native-decls/GetHeliBodyHealth.md
ext/native-decls/GetHeliDisableExplodeFromBodyDamage.md
ext/native-decls/GetHeliEngineHealth.md
ext/native-decls/GetHeliGasTankHealth.md
ext/native-decls/GetHeliMainRotorDamageScale.md
ext/native-decls/GetHeliPitchControl.md
ext/native-decls/GetHeliRearRotorDamageScale.md
ext/native-decls/GetHeliRearRotorHealth.md
ext/native-decls/GetHeliRollControl.md
ext/native-decls/GetHeliTailRotorDamageScale.md
ext/native-decls/GetHeliTailRotorHealth.md
ext/native-decls/GetHeliThrottleControl.md
ext/native-decls/GetHeliYawControl.md
ext/native-decls/GetIsHeliEngineRunning.md
ext/native-decls/GetThrusterSideRcsThrottle.md
ext/native-decls/GetThrusterThrottle.md
ext/native-decls/IsHeliTailBoomBroken.md

* New getters :
- GET_THRUSTER_THROTTLE
- GET_THRUSTER_SIDE_RCS_THROTTLE
- IS_HELI_TAIL_BOOM_BROKEN
- GET_IS_HELI_ENGINE_RUNNING
- GET_HELI_YAW_CONTROL
- GET_HELI_THROTTLE_CONTROL
- GET_HELI_TAIL_ROTOR_DAMAGE_SCALE
- GET_HELI_ROLL_CONTROL
- GET_HELI_REAR_ROTOR_HEALTH
- GET_HELI_REAR_ROTOR_DAMAGE_SCALE
- GET_HELI_PITCH_CONTROL
- GET_HELI_MAIN_ROTOR_DAMAGE_SCALE
- GET_HELI_GAS_TANK_HEALTH
-  GET_HELI_ENGINE_HEALTH
- GET_HELI_DISABLE_EXPLODE_FROM_BODY_DAMAGE
- GET_HELI_BODY_HEALTH
- IS_HELI_TAIL_BOOM_BREAKABLE
`GET_HELI_TAIL_ROTOR_HEALTH` was incorrect, it was reading the rear rotor bit instead of the tail rotor (which doesn't exist). To address this, I created a new native `GET_HELI_REAR_ROTOR_HEALTH` and added a deprecation warning to GET_HELI_TAIL_ROTOR_HEALTH using ScriptDeprecations, as …

feat(onesync/helicopters): serialize helicopters datanodes

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/GetGamePool.md

Have server parity for `GET_GAME_POOL`
Implements `GET_GAME_POOL` and fixes possible issues with `GET_ALL_*` native possibly returning entities that will be marked for cleanup or cleanup finalization 
Server

feat(scripting/state): add `GET_GAME_POOL` server side parity

---

code/client/launcher/GameSelect.cpp

This PR adds a new path for Epic games installation for the game selection process. As we've got more issues about wrong IVPath in the discord guild recently
Adds another "folderAttempt" entry with a recent valid Epic games Registry value, see : 
FiveM

Add new valid Epic installation path for gameselect process

---

ext/cfx-ui/src/cfx/apps/mpMenu/services/intl/intl.mpMenu.ts

Clarify the South Korea server
Currently, the South Korea server is not displayed on the home screen. If the country is ko-KO, please set it to ko-KR to resolve this issue.
FiveM, RedM
**Game builds:** ALL

fix(ext/cfx-ui): South Korea system locale

---

code/components/citizen-server-impl/src/state/PlayerStateScriptFunctions.cpp

Fix the server crashing if the player entity doesn't exist when the native is called
Using the proper `MakePlayerEntityFunction` wrapper that checks if the entity exist before calling the function
Server

fix(state/scripting): fixes player natives trying to reference non-existent player entity

---

ext/native-decls/AddStateBagChangeHandler.md
ext/native-decls/GetEntityFromStateBagName.md

This PR fixes 2 invalid Lua examples using === instead of ==, in Lua the strict '===' operator does not exists
By removing one "=" to achieve a correct check for invalid entity
Native docs

fix(native-decls): fix invalid operator in Lua examples

---

code/components/citizen-server-impl/include/state/SyncTrees_Five.h

Fix some server-side natives that return invalid values on game build >= 3095 like:
`GET_PLAYER_INVINCIBLE`
`GET_PLAYER_WEAPON_DAMAGE_MODIFIER`
`GET_PLAYER_MELEE_WEAPON_DAMAGE_MODIFIER`
Adding a missing bit reading operation on `CPlayerGameStateDataNode` for >= b3095
Server
**Game builds:** 2944, 3095, 3258
Fixes #2748

fix(onesync): CPlayerGameStateDataNode for b3095

---

code/components/conhost-v2/src/ConsoleHostGui.cpp

Fix crash when printing a large amount of things to console (2501+) due to `ItemTimes` using a `ImVector` instead of `circular_buffer`.
```lua
-- this expects you to have run `con_miniconChannels "script:*"` prior
CreateThread(function()
for i = 1, 5000 do
print("test", i)
end
end)
```
Replace `ImVector` with a `circular_buffer` so that it properly caps out at `2500` items instead of allowing it to infinity expand as a Vector, causing a crash later when it tries to remove `Items` and `ItemKeys` because they are properly restricted to `2500` items and will try to remove past the bounds if `Items`.
https://github.com/citizenfx/fivem/blob/705cd7901ac03c5a0d1e1355d94e84046309b80d/code/components/conhost-v2/src/ConsoleHostGui.cpp#L729-L734
FiveM/RedM
**Platforms:** N/A

tweak(conhost): use circular_buffer instead of ImVector

---

code/components/extra-natives-five/src/DrawImNatives.cpp

there is a recent issue introduced that causes the bottom line of the crosshair to render incorrectly
the bottom line ignores the gap and starts in at the center
made use of `iInnerBottom` for the line start instead of `iCenterY`
FiveM
not tested
fixes an issue introduced in #2544

fix(extra-natives/five): fix crosshair bottom line drawn incorrectly

---

code/client/clrcore-v2/Game/Shared/Game.cs

As of https://github.com/citizenfx/fivem/pull/2731 this is no longer needed.
Allow rt2 to properly take `Prop` for `GetGamePool`
FiveM

fix(clr/shared): remove preprocessor stuff for Object

---

code/client/clrcore-v2/Game/Shared/Game.cs
code/client/clrcore/Server/Entity.cs
code/client/clrcore/Server/Prop.cs

Fix bug for `mono_rt2` server implementation introduced in https://github.com/citizenfx/fivem/pull/2488 (and temp fixed in https://github.com/citizenfx/fivem/commit/3768dc04fa2d53030f0d52b362340c2b7ed2131b)
This also changes the server variant for `mono_rt2` from Object -> Prop fixing an oversight in https://github.com/citizenfx/fivem/pull/2731
This relies on on other changes so this will be marked as a draft for now.
Properly use server namespaces for native invokes
Server

fix(clr/shared): fix GetGamePool for server

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/GetEntityOrphanMode.md
ext/native-decls/SetEntityOrphanMode.md

Allow server owners to choose how they want the entity to be treated when it no longer has a valid/relevant owner.
This will allow for servers to use client side `CREATE_*` natives while being able keep the entity relatively persistent like the server setters, and also avoiding some of the known bugs with server-setters.
This will also allow the server owner to have specific entities be deleted whenever they leave the server.
Add `EntityOrphanMode`s to let the server owner choose how they want an entity to be treated when the entity loses its first owner or is no longer relevant.
Server

feat(server/state): add `[GET/SET]_ENTITY_ORPHAN_MODE`

---

code/components/voip-mumble/src/MumbleAudioInput.cpp
code/components/voip-mumble/src/MumbleAudioOutput.cpp

Fix voice cracking on high load
Setting a higher thread priority for Mumble voice. These changes need to be tested on Canary; I can't see any other way to conduct large-scale tests. I tried to create this issue using two RedM clients and running a CPU stress test in the background, but there was no way to replicate this on my PC and my friend's PC.
FiveM, RedM
fixes #2742

fix(voip/mumble): Voice cracking on high load

---

code/client/clrcore-v2/Interop/LocalFunction.cs

Decorate LocalFunction.Invoke with SecuritySafeCritical to fix callbacks throwing ReplicateMethodAccessException
Fix ``ReplicateMethodAccessException`` being thrown when a callback is being used.
The erroring function ``LocalFunction.Invoke`` is decorated as ``SecuritySafeCritical``
ScRT: C#, FiveM
**Game builds:** b3095
fixes #2749

fix(clcore-v2): Fix ReplicateMethodAccessException for Callbacks

---

data/shared/citizen/scripting/v8/main.js

Improve error messages when unpacking function unpacker
Currently if you error in this section of code on the server you get a hard to use stack trace that doesn't provide you any insights
1. Cache the resource that originally called an export to x resource
2. Catch unpack if it errors and return the default null
3. Warn the end user if the resource recently restarted, or point them in the right direction as ref calls should only be invalidated on resource restart.
ScRT: js

tweak(scripting/v8): better error messages for ref calls

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/GetVehicleNeonColour.md
ext/native-decls/GetVehicleNeonEnabled.md

* Added 2 getters GetVehicleNeonColour(), GetVehicleNeonEnabled()
By reading/write bits in CVehicleAppearanceDataNode
For crew things needs more test/check some data could be wrong here
FiveM

feat(server): add getters for neons

---

code/components/gta-core-five/src/CrashFixes.InvalidPickupCreation.cpp

Prevent crash caused by invalid pickup weapon components on pickup creation.
Adds proper validations on pickup creation
FiveM
**Game builds:** 2060, 3095
Fixes `GTA5_b3095.exe!sub_141163854 (0x456)`

fix(game/five): verify pickup weapon component is valid on creation

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
code/components/extra-natives-five/src/PoolTraversalNatives.cpp
ext/native-decls/GetGamePool.md

Give a fast path for calls to `GET_GAME_POOL` that only want to get networked objects (which can be a max of 80 objects), reducing the serialization/de-serialization overhead for this native call.
Getting entities from `GetGamePool("CObject")` can be costly due to the fact that this pool will include map objects too, which can lead to this table being thousands of objects long.
This doesn't include networked variants for `CPed` and `CVehicle` because these are more often times going to be networked, where as `CObject` is more likely to be client local objects
This adds a new fast path `CNetObject` which should only return objects that are networked
<details>
<summary>Test Example</summary>
```lua
CreateThread(function()
local networkedObjects = GetGamePool("CNetObject")
for i = 1, …
```

feat(extra-natives): add `CNetObject` to `GET_GAME_POOL`

---

code/client/clrcore/External/Vehicle.cs

Add new license plate style indexes to `LicensePlateStyle` enum.
Since they where added to the [Native Docs](https://github.com/citizenfx/natives/pull/1120), they should of been added to the C# enum list at the same time.
Adding the new license plate styles from the latest DLC
...
FiveM, ScRT: C#
...
Latest
**Game builds:** Latest

tweak(clrcore): add missing LicensePlateStyle enum types

---

code/components/citizen-server-impl/include/state/SyncTrees_Five.h

- Fixing getting the wrong values returned when using server getters like `GET_VEHICLE_NUMBER_PLATE_TEXT`
- Removing the second serialization of `data.primaryColour` which seems to be a small copy & paste mistake. Added with the following pr: #2785
- FiveM, Server
- Couldn't test it myself, but comparing the new and old synctree only showed this difference between them.
- Not working server getters like `GET_VEHICLE_NUMBER_PLATE_TEXT`

fix: vehicle sync tree causing getters to return the wrong values

---

code/client/clrcore/External/Tasks.cs

Re-introduce `LookAt` calls with two arguments so we don't break compatibility.
This also fixes the `LookFlags`, as it was on the wrong argument
FiveM
Fixes #2873

fix(mono): fix breakage accidentally introduced in #2740

---

code/components/citizen-resources-gta/src/GameInputFunctions.cpp
code/components/gta-core-five/include/GameInput.h
code/components/gta-core-five/src/GameInput.cpp
ext/native-decls/SetKeyMappingHideResources.md

Actually, @tabarra added # in his key mappings to have the txAdmin key mappings at the top of the FiveM key settings. This PR aims to fix this so Tabarra doesn't have to do this workaround
If the left is monitor and not the right one, we return true to indicate that the left needs to be placed before the right. If the right one is txAdmin and not the left one, we return false so that the right is placed before the left. Thanks @FabianTerhorst for fixing the sorting logic.
FiveM
Here is a screenshot where i did the test with a resource called ns_carrierheist.
**Platforms:** Windows,

feat(gameinput): new sorting algo and new native

---

code/components/gta-core-five/src/CrashFixes.InvalidPickupCreation.cpp

Prevent crash caused by invalid pickup weapon components on pickup creation.
This is an improvement on #2797 which was absolutely garbage.
Adds proper validations on pickup creation
FiveM
**Game builds:** 2060, 2699, 2802, 3095, 3258
Fixes GTA5_b3095.exe!sub_141163854 (0x456)

fix(game/five): verify pickup weapon component is valid on creation ( again, but proper )

---

code/components/conhost-v2/src/ConsoleHostGui.cpp

This improves the focus logic of the text input field in the client console. We now focus the input field when:
- Opening the console
- Hovering over the input field
- Whenever the console gains focus and no other clickable or input-taking item is active
Changing the focus logic for the console input field.
FiveM, RedM
fixes #2887

tweak(console): Improve keyboard focus

---

code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp

Fix a crash that occurred when an export declared in lua code was executed from C# v2 from the same resource multiple times, the issue with more details is here: https://github.com/thorium-cfx/mono_v2_get_started/issues/32
It seems that there are times that `m_appDomain` is destroyed when the script is stopped, but RemoveRef is still called a little after the C# script is destroyed, therefore RemoveRef is called when `m_appDomain` is null and results in the crash.
I don't know if there is a better solution for this.
ScRT: C#
**Game builds:** .
fixes [#32](https://github.com/thorium-cfx/mono_v2_get_started/issues/32)

fix(scripting/mono-v2): validate app domain before removing ref

---

ext/cfx-ui/src/cfx/apps/mpMenu/services/linkedIdentities/linkedIdentities.service.ts

This fixes an oversight in a previous change that does not register the afterRender function from linkedIdentities.service in the target list, preventing the main UI from showing any linked identities in the settings pane.
Re-adding the missing component registration.
cfx-ui
/

fix(ext/cfx-ui): afterRender not firing for identity service

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/src/state/ServerGameState.cpp

- this swaps `MoveEntityToCanidate` to use `ShouldServerKeepEntity` instead of having specific logic for orphan mode
- makes 'entitiesToDestroy' use `ShouldServerKeepEntity` instead of `IsOwnedByServerScript`so we reassign if orphan mode is set to keep the entity
Properly reassign the entity to the server in certain situations where it would previously not happen
Add a new function that uses the original script check & entity orphan checks
Server

fix(server/state): properly reassign entities that are set to `EntityOrphanMode::KeepEntity`

---

ext/cfx-ui/src/cfx/common/services/servers/transformers.ts

This change aims to simplify and centralize the logic for filtering out specific server configuration variables (convars).
By creating a helper function (shouldVarBeShown), we reduce redundancy and improve readability.
With these changes it also includes the new convar `sv_replaceExeToSwitchBuilds` 
Replacing multiple cases in the processServerDataVariables function with a single call to shouldVarBeShown, resulting in cleaner and more maintainable code.
FiveM/RedM

tweak(cfx/nui): convar filtering logic with shouldVarBeShown helper + add `sv_replaceExeToSwitchBuilds`

---

code/components/voip-mumble/src/MumbleAudioInput.cpp

This fixes a nullptr exception when trying to write to the Audio Processing Module while the audioCaptureClient is invalid.
We now also apply the last voice intent mode to the new audio device instead of the default ('speech') mode.
Added a nullptr check before trying to write to the Audio Processing Module.
FiveM
Reported here: https://discord.com/channels/779705925577080842/1301532596240515082 (Cfx.re Engineering Group)

fix(voip-mumble): nullptr check

---

code/components/citizen-server-impl/src/packethandlers/ServerCommandPacketHandler.cpp

This resolves the reported issue of blank lines cluttering the client console output.
Discarding empty data previously sent to the client, preventing unnecessary "empty line" entries from appearing in the client console.
Server
/

fix(server): don't invoke cfx_internal:serverPrint on empty string

---

code/components/conhost-server/component.lua
code/components/conhost-v2/component.lua
code/components/conhost-v2/include/Textselect.hpp
code/components/conhost-v2/src/ConsoleHostGui.cpp
code/components/conhost-v2/src/ConsoleHostImpl.cpp
code/components/conhost-v2/src/DrawFPS.cpp
code/components/conhost-v2/src/Textselect.cpp

The goal of this PR is to enhance the functionality and usability of the client and server consoles by implementing selectable and copyable text, improving the user experience, and resolving various interface issues. This includes ensuring that the console input fields are more user-friendly and maintain proper focus behavior, while also improving the visual consistency and functionality of the consoles.
https://github.com/user-attachments/assets/0c39ea07-f372-4973-a44d-2920e7cbca6e
- Selectable/Copyable Text: Introduced a submodule that provides the functionality to select and copy text in ImGui windows. This has been implemented on **all** available consoles.
- Modified the text input behavior so that the consoles' text input fields automatically gain focus when no other …

feat(console): rework (selectable/copyable log text entries)

---

code/components/gta-net-five/include/netBlender.h
code/components/gta-net-five/src/CloneObjectManager.cpp

Fixes scenarios where a train becomes owned by the server (orphan natives) and upon a player re-entering the trains scope and  becoming owner of the train, The train resets to the node 0 of the track it is currently on
By forcing the train to find its current track node based on the trains current position, only upon ownership change to a player from a server and if the new client has no knowledge of the trains current track node.
FiveM
**Game builds:** 1604, 2372, 2545, 2802, 3258

fix(net/five): correct train track node on ownership change

---

code/components/citizen-legacy-net-resources/src/ResourceNetBindings.cpp

This ensures that the "same thread" constraint in SendNetPacket stays valid. (We don't need to send server-commands before full game init. anyway).
Blocking server-commands before we are fully initialized (Render->MainThrd switch).
FiveM
/

tweak(legacy-net/resources): check for gameinit on server-command

---

code/components/gta-streaming-five/src/GameEventHooks.cpp

vtable indices have changed on 3258. This breaks the patch for fall damage not triggering `CEventNetworkEntityDamage`.
Correcting the vtable index.
FiveM
fixes #2779

fix(game/five): cNetObjPhys vtable index for 3258

---

code/components/net-base/include/Net.h
code/server/launcher/src/Main.cpp

On some systems (like Ubuntu) netinet headers get included by default. In those cases, we are re-defining system macros without undefining them first, which makes building fail.
This fixes building on native Ubuntu, so this *should* revive Github Runners once again.
https://github.com/tens0rfl0w/fivem/actions/runs/11621071896/job/32364102250
- Guarding `_GNU_SOURCE` macro
- Undefining `__bswap_*` macros before re-defining them
Source compiling (Linux)
**Platforms:** Linux (Github Runners - ubuntu-20.04)
/

tweak(compiler/linux): build portability

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
ext/native-decls/DoesTrainStopAtStations.md
ext/native-decls/SetTrainStopAtStations.md

Allows for mission trains (trains created with CREATE_MISSION_TRAIN) to stop at stations. Enabling for the same behaviour as non-mission trains. This removes the need for scripts to implement their own logic which may not play well with multiple players/owners 
By creating SET_TRAIN_STOP_AT_STATIONS which allows ScRT to directly toggle a flag deciding if a train should stop at stations
FiveM, Natives
**Game builds:**  1604, 2372, 2699, 3258

feat(extra-natives/five): train station natives

---

ext/native-decls/GetPlayerIdentifier.md

Add simple documentation to the native, which has the wrong parameter name, and provide useful information.
Renames an incorrect parameter name.
Adds a reference on how to get the number of identifiers.
Adds a reference on how to get an identifier by type.
Specify a return value and an OutOfBounds value.
Server Native Docs

feat(docs/natives/GetPlayerIdentifier): Improve simple doc

---

code/components/conhost-v2/src/DrawPerf.cpp

Starting with Windows 8, Microsoft updated CPU performance counters to use "Processor Utility" instead of "Processor Time" to reflect dynamic frequency scaling (e.g., Intel Turbo Boost, AMD Precision Boost). This causes the in-game metrics to display wrong CPU utilization values.
This change ensures in-game metrics display those more accurate values.
FiveM, RedM
Reported here: https://discord.com/channels/779705925577080842/1260757053635297381 (Cfx.re Engineering Group)

tweak(conhost-v2): switch CPU utilization tracking to dynamic scaling

---

code/components/gta-core-five/src/CrashFixes.FakeParachuteProp.cpp

Addresses a crash caused by the game wrongfully assuming that every entity/fragment that uses a model of type 'vehicle' is parented by a vehicle ( in which the entity would have a valid vehicle shader )
Add proper validation for vehicle shader access
FiveM
**Game builds:** 3095, 3258

fix(game/five): check for vehicle type on drawhandler shader access

---

code/components/extra-natives-five/src/TrackNatives.cpp
ext/native-decls/GetTrackBrakingDistance.md
ext/native-decls/GetTrackMaxSpeed.md
ext/native-decls/IsTrackEnabled.md
ext/native-decls/IsTrackSwitchedOff.md
ext/native-decls/SetTrackBrakingDistance.md
ext/native-decls/SetTrackEnabled.md
ext/native-decls/SetTrackMaxSpeed.md

This PR introduces a set of track natives to allow for scripts to get and set information relating to the track. This PR also resolves 2 track related issues tied to trains.
- Disabled tracks being considered when finding the nearest track to spawn mission trains on.
-  The tracks maximum speed being constantly set to all trains that can stop at stations while the train is in a moving state. Preventing scripts from being able to modify it, this change does not impact trains when slowing down at stations or speeding up to leave a station.
By creating new natives that retrieve track information from the game.  Hooking into the function responsible for finding the closest track index and it's track node and making sure it accounts for disabled tracks.
FiveM, Natives
**Game builds:**  1604, …

feat(extra-natives/five): track natives

---

ext/natives/codegen_out_native_lua.lua

Allow `VAR_STRING` to be used on RDR when using OAL
Marks it as 'unsupported' so it wont be generated as a supported native for OAL
RedM
This was only tested that it doesn't add to the map in `NativesRDR.h`
Fixes the issue @outsider31000 reported

tweak(codegen): set VAR_STRING as an unsupported type for OAL

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
ext/native-decls/GetTrainCruiseSpeed.md
ext/native-decls/GetTrainDirection.md
ext/native-decls/GetTrainSpeed.md
ext/native-decls/GetTrainState.md
ext/native-decls/SetTrainState.md

Introduce a set of getters + a setter for several aspects of train movements. Allows for scripts to get information about the trains current speed, cruise speed, direction and state (e.g. moving, stopping at station, stopped at station and driving away from station) which was previously not possible 
By creating GET_TRAIN_DIRECTION, GET_TRAIN_STATE, GET_TRAIN_CRUISE_SPEED, GET_TRAIN_SPEED and SET_TRAIN_STATE (to allow for scripts to change the trains current state)
FiveM, Natives
**Game builds:** 1604, 3258

feat(extra-natives/five): train movement natives

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/DeleteEntity.md
ext/native-decls/DeleteTrain.md

Fix some oversights in some code regarding entity validation, trains, and how deletions for trains are handled, and how setting orphan mode is handled for trains
Make code that iterates over trains more generic so we can re-use it throughout more code.
Make calls that were previously just checking for `!entity` also check for if the entity is being deleted, fixes some cases
When called on trains `SET_ENTITY_ORPHAN_MODE` will also set the orphan mode for all trains attached, fixing the possibility of partial deletes from a train not being relevant.
Change `DELETE_ENTITY` to not allow it to be called on train carriages, as we don't have a way to write to the sync node of the current train that one of its links no longer exists, this could lead to broken state and possibly cause weird …

Minor fixes for trains, use `IsEntityValid` for other calls checking if the entity exists

---

code/components/gta-core-five/src/CrashFixes.DecalCallbacks.cpp

Fixes a crash that occurs when a vehicle only has the highest lod set up. Usually people work around this by duplicating the model file & appending `_hi` (as further explained in code)
If the original function does not return a valid lod, we find the first suitable one and return it to prevent a crash later on.
FiveM
**Game builds:** 1604, 2189, 2699, 3095, 3258

fix(game/five): crash when no medium lod exists on a vehicle

---

code/components/nui-resources/src/ResourceUIScripting.cpp
ext/native-decls/SetNuiZindex.md
ext/ui-build/data/root.html

Set the z-index for the NUI resource.
You can set the z-index of an NUI resource with `SET_NUI_Z_INDEX`.
FiveM, RedM, Natives

feat(nui): add `SET_NUI_ZINDEX`

---

code/components/extra-natives-five/src/RuntimeAssetNatives.cpp

Fix not being able to set the last/bottom right pixel of runtime textures.
Fixing a logic error (>= when it should be >)
FiveM, Natives
Note: tested and was unable to set outside bounds of a 8x4 texture through either x/y.
Would be very surprised if this broke based on build.
N/A

fix(extra-natives-five): Fix unable to set last pixel of runtime texture

---

ext/natives/codegen_out_pointer_args.lua

https://github.com/citizenfx/fivem/commit/ec2ba2e99f1891e8e4882aa6bd899f0092cfe51c enabled type checking for server natives but didn't account for arguments of type "Player" being `charPtr` within RPC natives.
Manual type fix for args of type `Player` in RPC natives.
FiveM, Server, Natives
fixes #3023

fix(scripting): RPC natives pointer args for player type

---

code/components/loading-screens-five/src/LoadingScreens.cpp

Sets the Players Ped to 0,0,0; this makes RAGE render/activate game mechanics (Map, Entities, Entity dependent natives, UI).
Also, it removes setting the `doSetup` condition, as this code is unrelated and not reachable via manual shutdown.
Sets the Players Ped to 0,0,0
Remove `loadsThread.doSetup = true;`, in ShutdownLoadingScreenNui
FiveM
**Game builds:** 1, 2060, 3258
**Platforms:** Windows Client
Current (Only distant cars, water, weather, and time are present & entities are static if spawned):
New (Playable game state):
Most people don't see this behaviour, as spawn managers/menus set the coords.

tweak(game/fivem/loadscreen): Initialize the player for RAGE with manual shutdown

---

code/components/extra-natives-five/include/Train.h
code/components/extra-natives-five/src/NativeFixes.cpp
code/components/extra-natives-five/src/TrackNatives.cpp

Prevent client crashes when using the CREATE_MISSION_TRAIN native.
By adding checks that are missing with the original native implementation. Such as invalid train variations (that do not exist in trains.xml), required carriage models not being loaded, and checking to ensure that there is at least a single track enabled to create a train on (this wouldn't crash the client, but would rather return a native error in the console which could be confusing to users).
This PR also moves some Train structs from TrackNatives to a Train header file to reduce code duplication 
FiveM
**Game builds:** 1604, 2060, 2372, 2545, 2699, 2802, 3095, 3258, 3407
I've created a repro resource to reproduce the crashes and their new behaviour with this PR. …

tweak(extra-natives/five): sanitize mission train creation

---

code/components/voip-mumble/include/MumbleClientImpl.h
code/components/voip-mumble/src/MumbleAudioInput.cpp
code/components/voip-mumble/src/MumbleAudioOutput.cpp
code/components/voip-mumble/src/MumbleClient.cpp
code/components/voip-mumble/src/MumbleClientState_User.cpp
code/components/voip-mumble/src/MumbleCrypto.cpp

1. Fix a bunch of issues where players would not be able to talk to other users, or hear other users
2. Fix music mode intent having cut outs for quieter music
Fixes a bunch of different implementation errors, each commit should explain what it does relatively well in the description.
FiveM, RedM

Mumble fixes

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp

Fix oversight in 8957209b72626bacd970f07412f3dff6ccac2bf0 which added the `IsEntityValid` to `makeEntityFunction`, this is only needed for checks that an entity is valid (i.e. `DOES_ENTITY_EXIST`, and to a lesser extent, `NETWORK_GET_ENTITY_FROM_NETWORK_ID`) and pool getters.
Swap back to the old check for `makeEntityFunction`
Server
Fixes #3042

fix(state): fix not being able to use any entity native calls in 'entityRemoved'

---

code/client/clrcore/External/WeaponCollection.cs

Allows to iterate over WeaponCollection like:
```cs
foreach(Weapon weapon in Game.PlayerPed.Weapons)
{
//Do something
}
```
Make WeaponCollection inherit ``IEnumerable<Weapon>`` and create the necessary function ``GetEnumerator()``
FiveM, ScRT: C#
**Game builds:** 
**Platforms:**

feat(clcore): Allow iteration of WeaponCollection

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
ext/native-decls/GetVehicleXmasSnowFactor.md
ext/native-decls/SetVehicleXmasSnowFactor.md

add natives to allow for control over the effect xmas weather has on vehicle handling.
...
by adding 2 new natives for getting and setting the value responsible for effecting this.
...
FiveM, ScRT: Lua, ScRT: C#, ScRT: JS
...

tweak(extra-natives/five): implement [GET/SET]_VEHICLE_XMAS_SNOW_FACTOR

---

code/client/clrcore/External/WeaponHash.cs

Update WeaponHash.cs with up-to-date weaponhashes in order to allow both them to be used in both C#-runtimes.
Add corresponding weaponnames and -hashes to WeaponHash.cs
Fivem, ScRT: C#
**Game builds:** 
**Platforms:**

fix(clcore): Update WeaponHash.cs with hashes from dlcs mpheist3 to mp2024_01 (latest)

---

code/components/voip-mumble/include/MumbleClientImpl.h
code/components/voip-mumble/src/MumbleClient.cpp

- The previous implementation would constantly swap between UDP/TCP constantly causing the players mic to stutter
- The old implementation should've been completely removed, this is an oversight in https://github.com/citizenfx/fivem/commit/f182bb5176e37ed996d27fdb87170a4097d6025b
Fix broken implementation of https://github.com/citizenfx/fivem/commit/f182bb5176e37ed996d27fdb87170a4097d6025b, time since last UDP received doesn't matter as this is all determined by MumbleCrypto.
Removes UDP timeout checks and once `m_hasUdp` is set to true, disallow it from being set to false again for the first 20 seconds of a connection (mimicking mumbles implementation https://github.com/mumble-voip/mumble/blob/e64f334c9376cfc8425916a152e3c09e301d5188/src/mumble/ServerHandler.cpp#L648-L663)
FiveM, RedM …

tweak(mumble): swap to completely using TCP ping for checking if UDP is available

---

code/components/citizen-server-impl/src/ServerExtCommerce.cpp
ext/native-decls/LoadPlayerCommerceDataExt.md

Was talking with @the-neco about the usage of some of the commerce natives but found that their usage was extremely limited because they could not be updated after the first request.
Allow LoadPlayerCommerceDataExt to reload player SKUs while in game, this currently only fetched once and cannot be updated until the player rejoins, this adds unnecessary friction.
This allows `LoadPlayerCommerceDataExt` to fetch the players packages again once every 10 seconds.
Calls to `LoadPlayerCommerceDataExt` after 10 seconds will refresh the clients SKUs
Server

fix(commerce): allow the server to refresh sku's after initial load

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/GetVehicleDoorStatus.md

This PR addresses two issues: missing bounds checks that allowed reading out-of-bounds memory, and a missing parameter in the native declaration of `GET_VEHICLE_DOOR_STATUS`.
- Introduced checks to ensure that array indices are within valid bounds before accessing data, preventing out-of-bounds reads.
- Updated the native declaration of `GET_VEHICLE_DOOR_STATUS` to include the missing `doorIndex` parameter.
- Corrected array size for `doorPositions` in `CVehicleGameStateNodeData`.
FiveM, Server
**Platforms:** Windows (Server)
Reported here: https://discord.com/channels/779705925577080842/779739477642838036/1304152704137826304 (Cfx.re Engineering Group)

fix(gamestate/server): add array bounds checks and fix native decl.

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/components/citizen-server-impl/src/state/ServerSetters.cpp
ext/native-decls/server/CreateVehicleServerSetter.md

This PR addresses an issue where creating an object, ped, or vehicle via server-setters does not validate the availability of free object IDs. This oversight can lead to memory leaks and undefined behavior, as overwriting an existing entity handle keeps the previous entity pointer alive in the sync pool, resulting in "ghost entities" and inaccessible allocated memory.
Checking if we got a valid / free object id, and if not, returning a non-valid GUID ('0') indicating failed creation (Client logic parity).
Server
**Platforms:** Windows (Server)
/

fix(server/gamestate): memory leak

---

code/components/gta-core-five/component.json
code/components/gta-core-five/src/PatchAttachCD2545.cpp
ext/native-decls/OnesyncEnableRemoteAttachmentSanitization.md

This PR introduces the ability to toggle checks that prevent entity-to-ped attachments on remotely owned peds. These checks are disabled by default in FiveM.
A new native function, `OnesyncEnableRemoteAttachmentSanitization`, has been added to allow toggling of these attachment checks at runtime.
The value resets to the default state ('off') upon player disconnect.
FiveM
**Game builds:** 2545, 3258
Requested by @slashkeyvalue in: https://discord.com/channels/779705925577080842/779739506286002196/1301027817483538453 (Cfx.re Engineering Group)

feat(core/five): sanitization for attachments on remote peds

---

ext/cfx-ui/src/cfx/common/services/activity/ActiveActivityPubFeed.ts

While debugging an issue with a [user on the forums](https://forum.cfx.re/t/how-to-server-feed-dedicated-space-on-fivem-social/5199841/13?u=theindra), noticed that accounts marked as "Automated" in Mastodon fail to load in the servers feeds. This is because these accounts are [returned as](https://github.com/mastodon/mastodon/blob/72a4da83fdd2ac8a089cde208149792108783d97/app/serializers/activitypub/actor_serializer.rb#L53-L54) type `Service` in the ActivityPub response, while the code only checks for `Person` currently.
Allows ActivityPub users with both `Person` and `Service` type.
CfxUI

tweak(ext/cfx-ui): allow automated accounts for servers feeds

---

ext/sdk/resources/sdk-root/shell/src/fxdk/project/node/project-builder.ts

Updates the generated comment to portal
Changing keymaster to portal url
FxDK

tweak(fxdk): Change Keymaster to Portal

---

code/components/extra-natives-five/src/PedCollectionsNatives.cpp
ext/native-decls/GetPedPropCollectionLocalIndex.md
ext/native-decls/GetPedPropCollectionName.md

Add two new FiveM client natives for prop collections to provide parity with existing drawable variation natives. The new natives allow retrieving collection-local indices and collection names for ped props, similar to [GetPedDrawableVariationCollectionLocalIndex](https://docs.fivem.net/natives/?_0x9970386F=) and [GetPedDrawableVariationCollectionName](https://docs.fivem.net/natives/?_0xBCE0AB63=).
Added two new native functions
1. `GET_PED_PROP_COLLECTION_LOCAL_INDEX`: Returns the collection-local index for a prop at a given anchor point
2. `GET_PED_PROP_COLLECTION_NAME`: Returns the collection name for a prop at a given anchor point
FiveM

feat(game/five): add ped prop collection natives

---

code/client/citicore/console/Console.CommandHelpers.h
code/client/citicore/console/Console.Commands.cpp
code/client/citicore/console/Console.Commands.h
code/components/citizen-scripting-core/src/ResourceScriptFunctions.cpp
ext/native-decls/GetRegisteredCommands.md
ext/native-decls/GetResourceCommands.md

The goal of this PR is quite simple: allow resources to see which resource, registered which command.
This goal, was mainly sparked by a [suggestion in txAdmin](https://discord.com/channels/577993482761928734/1318332458499838055):
> In txAdmin menu, under Resources tab, It would be useful to view all the registered commands under each script in a dropdown
This PR achieves this by:
- storing the invoking resource from `REGISTER_COMMAND` in the Command Object
- Allowing that data to be accessed from the existing native: `GetRegisteredCommands`
- Adds a Brand new Native: `GET_RESOURCE_COMMANDS`, that allows resources to retrieve the command list, from specific resources, allowing for much cleaner code.
- All internal commands, such as convars, are marked as `internal` for the resource. …

feat: allow resources to retrieve the invoking resource of commands

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/include/state/SyncTrees_RDR3.h
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/GetPedRelationshipGroupHash.md

Add a new getter to be able to obtain the relationship group from server side.
Completing the CPedAIDataNode.
FiveM, Server, Natives

feat(gamestate/server): ped AI node getter

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/GetPlayerFocusPos.md
ext/native-decls/IsPlayerInFreeCamMode.md

This PR introduces two new server natives:
1. **`IsPlayerInFreeCamMode`**  
- Allows to check if a player is in free cam mode (i.e. not using the main game camera / having a camera offset from the players ped position).  
2. **`GetPlayerFocusPos`**  
- Retrieves the current focus position of a player's camera, representing the game state area currently synced with the player's client.  
Reading data from `CPlayerCameraDataNode` and returning the relevant information.  
FiveM, RedM, Server, Natives
/

feat(server/gamestate): freecam status natives

---

.gitmodules
code/components/rage-input-five/component.lua
code/components/rage-input-five/include/InputHook.h
code/components/rage-input-five/src/InputHook.cpp
ext/cfx-ui/src/assets/languages/locale-en.json
ext/cfx-ui/src/cfx/apps/mpMenu/settings.tsx

This PR introduces support for [AMD Radeon Anti-Lag 2](https://github.com/GPUOpen-LibrariesAndSDKs/AntiLag2-SDK) in FiveM, significantly reducing input latency for systems utilizing AMD Radeon RX 5000 GPUs or newer.
In GPU-bound scenarios, the improvement is particularly noticeable. For example, the following results demonstrate the difference in input-to-game latency under highly GPU-bound conditions within FiveM:
- **Anti-Lag 2 enabled:**
- **Anti-Lag 2 disabled:**
_(Green text represents the frame delay between physical input and game interaction.)_
This implementation integrates AMD Radeon Anti-Lag 2 into the main input polling loop of FiveM. This should also roughly match the entry point for signal callbacks of the message pump.
Alternative entry points, such as hooking game …

feat(rage-input-five): AMD Radeon Anti-Lag 2

---

code/components/extra-natives-five/src/NativeFixes.cpp

This PR addresses an issue where helicopter rotors do not break off correctly when their health is set to `0.0` via scripts using the natives `_SET_HELI_MAIN_ROTOR_HEALTH` or `_SET_HELI_TAIL_ROTOR_HEALTH`.
Under normal game scenarios, such as damage from collisions or bullets, a rotor with `0.0` health breaks off the helicopter as intended. However, when the health is altered via these natives, the necessary checks to trigger rotor detachment are missing. This results in an inconsistent synchronization state: the rotor remains attached on the entity owner's client, while it appears broken off for remote players (as health sync node updates for `NetObjHeli` contain the required checks already).
This PR ensures that rotor health changes made via script are handled consistently, preserving …

fix(game/five): SET_HELI_*_ROTOR_HEALTH sync fixes

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
ext/native-decls/SetVehicleXmasSnowFactor.md

The previous implementation hooked the subtraction instruction (`subss`) instead of the initial multiplication instruction (`mulss`) bypassing the total snow amount multiplier. It also caused game crashes for NPC controlled vehicles when calculating wheel collision vectors and had no impact on player controlled vehicles.
We now hook the initial multiplication instruction which keeps reference to the total snow amount (which can be overwritten). This calculation occurs in two separate sections, both of which are now patched.
Values are clamped between `0.0` and `2.0` to make sure physics don't get broken.
GameValueStub's used for less code duplication.
FiveM, Natives
**Game builds:** 3407
/

fix(extra-natives/five): xmas snow grip factor natives

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp

This PR adds a way to prevent certain manipulations of NPCs. Native functions such as TaskShootAtEntity and TaskGoToEntity are often used by malicious users to manipulate NPC into harming other players without requiring network control over them. 
I believe that a handler is more suitable than a convar in this case, considering the wide variety of tasks.
Introduce CGivePedScriptedTaskEvent struct and added the corresponding handler in the GetGameEventHandler and GetGameEventHandlerWithEvent functions.
FiveM server

feat(server/state): add GIVE_PED_SCRIPTED_TASK handler

---

code/components/citizen-scripting-lua/include/LuaScriptRuntime.h
code/components/citizen-scripting-lua/src/LuaScriptRuntime.cpp
data/shared/citizen/scripting/lua/scheduler.lua

Adds a ClearTimeout function to the Lua runtime so that scripts can cancel a timer that was previously set with SetTimeout.
Implements ClearTimeout which removes a scheduled timer from the queue.
ScRT: Lua

feat(citizen-scripting-lua): ClearTimeout function

---

code/components/handling-loader-five/src/HandlingLoader.cpp

Correct broken physics by modifying handling with nils values
Switch from GetArgument to CheckArgument to be able to create an error if the value is not correct
FiveM
fixes #3097

fix(handling-loader): fix broken physics

---

code/components/citizen-scripting-core/src/ResourceScriptFunctions.cpp

- this allows you to do `ExecuteCommand("add_ace group.moderator command.test allow") as long as the calling resource was the one that created the command
Currently if resources want to do `add_ace` for its own commands it has to do [weird wrappers](https://github.com/overextended/ox_lib/blob/189306d5aac329b39543dd4c7ac93f18361e561f/package/server/resource/acl/index.ts#L4-L5) to [do add_ace](https://github.com/overextended/ox_lib/blob/189306d5aac329b39543dd4c7ac93f18361e561f/resource/acl/server.lua#L6-L21)
Having to use these kinds of wrappers is bad security since it can allow any resource to call them and give itself certain permissions, but there is no way currently to `add_ace` to your own command.
This PR gives the creating resource of a command to have control over it removing the …

tweak(core/acl): give the creating resource the ability to modify the ACL for its own commands

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
ext/native-decls/GetVehicleHasFlag.md
ext/native-decls/SetVehicleFlag.md

Implement natives to set and get vehicle flags. This is the PR of @kams3 with the addition of the setter.
By reading the specific offset in this signature: 48 85 C0 74 3C 8B 80 ? ? ? ? C1 E8 0F, which exposes vehicle flags on the vehicle. 
This rely on https://github.com/citizenfx/fivem-docs/pull/480
FiveM

feat(natives/vehicle): implement getter/setter for vehicle flags

---

code/components/extra-natives-five/include/ropeManager.h
code/components/extra-natives-five/src/NativeFixes.cpp
code/components/extra-natives-five/src/RopeNatives.cpp
data/client/citizen/common/data/gameconfig.xml
ext/native-decls/RegisterRopeData.md

Adds a way to register custom rope data during gameplay and fixes a crash if an invalid rope type is passed into `ADD_ROPE`
This superceeds an earlier PR #2205 which wasn't friendly if multiple resources wanted to have custom rope data
Adds `REGISTER_ROPE_DATA` which has parameters matching the fields seen in `ropedata.xml`, allowing you to create ropes with different sizes, textures, etc
Clamps the `ropeType` of `ADD_ROPE` so that a crash will not occur if an invalid type is passed
FiveM, Natives
**Game builds:** 1604, 2060, 2189, 2372, 2545, 2612, 2699, 2802, 3095, 3258, 3323, 3407

feat(extra-natives/five): REGISTER_ROPE_DATA

---

code/components/rage-input-five/src/InputHook.cpp

Currently, when using DirectInput as the input method for the mouse, mouse inputs are still passed through to the game, even when an overlay such as a NUI or the client console is focused. This results in unintended user interactions with the game.
This PR hooks into the `recaptureLostDevices` function, which re-acquires a DirectInput mouse device that has lost focus, to block execution of the function when the game has no focus. Additionally, it un-acquires the game's DirectInput mouse device by directly accessing its memory address and invoking `Unacquire` on the object when a focus switch is invoked.
FiveM
**Game builds:** 2060, 2699, 3258, 3407
fixes #1010

fix(input/five): DirectInput mouseDev unacquire

---

code/components/rage-input-five/src/InputHook.cpp

This PR addresses an issue where, with the mouse input method set to "Raw Input," the game fails to reset mouse button states when it loses focus (e.g., when a NUI or the client console gains focus). As a result, any mouse buttons pressed at the moment of focus loss remain in a "pressed" state until the game regains focus and the button is physically pressed again. This behavior can lead to unintended actions, such as continuous weapon firing.
To resolve this issue, the PR introduces a manual flush of the `ioMouse` button array. This ensures that button states are cleared when the game loses focus, preventing them from getting stuck and mitigating unintended user inputs.
FiveM
fixes #2508

fix(input/five): flush raw input mouse buttons on focus loss

---

code/components/nui-core/src/CefInput.cpp

This PR addresses an issue where the mouse cursor is not clipped to the game window when a NUI is focused without the cursor being present (i.e., only the keyboard is focused). This behavior causes the cursor to move outside the game frame in non-fullscreen mode or when using a multi-monitor setup, leading to loss of focus while moving the game camera.
The proposed change introduces a check for the presence of a cursor (`g_hasCursor`). Game frame clipping is now disabled only when a cursor is actively present, ensuring camera movement still works as intended.
FiveM
Reported by myself here: https://forum.cfx.re/t/5172373

fix(nui/core): keep cursor clipping when no cursor is present

---

code/components/extra-natives-five/src/VfxNatives.cpp
ext/native-decls/DrawCorona.md

Added native `DRAW_CORONA` to render more advanced light effects, like volumetric lights.
Creating the `CCoronas` structure that contains the list of coronas, and a method to add new ones.
The patterns have been taken from https://github.com/thorium-cfx/fivem/commit/26f7e2d61251f798b87d5aba0750372993e32d22 and the `CF_NO_RENDER_UNDERGROUND` flag from https://github.com/alexguirre/Spotlight/blob/master/Source/Core/Memory/GameStructs.cs#L296
FiveM, Natives
**Game builds:** 3095, 3407

feat(extra-natives-five): add DrawCorona native

---

code/components/extra-natives-five/src/VfxNatives.cpp

The game function `addLightCorona` expects vectors to be aligned to a 16-byte memory boundary, but `DirectX::XMFLOAT3` does not provide this alignment by default. This misalignment causes an access violation error when executing `movaps xmm5, xmmword ptr [rax]` in release builds.
- Replaced the usage of `DirectX::XMFLOAT3` with `DirectX::XMVECTOR`, which guarantees 16-byte alignment as required.
- Function pattern has been simplified
FiveM, Natives
**Game builds:** 1, 1604, 2060, 2189, 2372, 2545, 2612, 2699, 2802, 2944, 3095, 3258, 3407
fixes #3132

fix(extra-natives-five): DrawCorona 16-byte vector alignment for SIMD instructions

---

code/components/handling-loader-five/src/HandlingLoader.cpp

As outlined in detail in https://github.com/citizenfx/fivem/issues/3130, the [following PR](https://github.com/citizenfx/fivem/pull/3101) attempts to 'validate' against NULL values when using `SetVehicleHandlingFloat` or `SetVehicleHandlingInt` to prevent vehicle physics from breaking. The issue is that NULL values are parsed as 0, meaning that you can also no longer use the value 0 in these natives (which is common).
Furthermore, the issue the PR was intending to fix wasn't actually caused by NULL values; it's isolated to the handling loader setting a high value for `fTractionCurveMax` when 0.0f/NULL is detected ([source](https://github.com/citizenfx/fivem/blob/7bcb23de344a68b53ff0b95e63c49f0a9cb5298a/code/components/handling-loader-five/src/HandlingLoader.cpp#L215-L218)).
Not allowing …

Revert "fix(handling-loader): fix broken physics"

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp

I need glasses.
Fixing the typo.👓
FiveM, RedM, Natives
**Platforms:** Windows (Server)
/

fix(server/gamestate): typo in freecam natives

---

code/client/shared/StdInc.h

Microsoft stopped including chrono automatically internally, so we must now include it in our own standard include
https://learn.microsoft.com/en-us/cpp/overview/what-s-new-for-visual-cpp-in-visual-studio?view=msvc-170
FiveM, RedM, Server

fix(shared): include chrono to fix breakage caused by msvc-170

---

code/components/citizen-server-main/src/ServerInstance.cpp

The server players.json IDs privacy announcement link was **big**, now link is _smol_.
Used the cfx.re link shortener: https://aka.cfx.re/players-json-privacy
FXServer, exclusively.
Didn't test it at all (except the link itself).
None, nobody even complained, but I needed to test the shortener and this particular link has been on my head recently.

tweak(server): shortened players.json privacy announcement link

---

code/components/extra-natives-five/src/NuiAudioSink.cpp
code/components/gta-net-five/src/MumbleVoice.cpp
code/components/voip-mumble/include/MumbleAudioSink.h
code/components/voip-mumble/include/MumbleClient.h
code/components/voip-mumble/include/MumbleClientImpl.h
code/components/voip-mumble/include/MumbleClientState.h
code/components/voip-mumble/src/MumbleAudioOutput.cpp
code/components/voip-mumble/src/MumbleClient.cpp
code/components/voip-mumble/src/MumbleClientState_Channel.cpp
code/components/voip-mumble/src/MumbleClientState_User.cpp
code/components/voip-mumble/src/MumbleVersionHandler.cpp
ext/native-decls/MumbleSetServerAddress.md

Fix some possible edge cases where players could be invalid but we would still send a properly formatted mumble name
Removes swapping between `std::wstring` and `std::string`
Reset the mumble connection in cases where the client loses their TCP connection.
Fix some cases where the client would send duplicates of the same targets to the server, leading to some excessively large packets.
Wrap any native that needs to be used while connected in `MakeMumbleNative`
This change set is currently untested
FiveM, RedM
**Game builds:** ..

Mumble tweaks/fixes

---

code/components/extra-natives-five/src/TrackNatives.cpp
ext/native-decls/GetClosestTrackNodes.md
ext/native-decls/GetTrackNodeCoords.md
ext/native-decls/GetTrackNodeCount.md
ext/native-decls/RegisterTrackJunction.md
ext/native-decls/RemoveTrackJunction.md
ext/native-decls/SetTrackJunctionActive.md

Introduce a way to register track switching. Track switching allows for a train to change the track index it is currently navigating along. Suggested by @glitchdetector 
introduces ``REGISTER_TRACK_SWITCH`` and ``SET_TRACK_SWITCH_ACTIVE`` to allow for registration of a train switch and ability to enable/disable the track switch
FiveM, Natives
A test resource showing the functionality of all new natives and test cases are provided  https://github.com/citizenfx/fivem/pull/3044#issuecomment-2671891066
**Game builds:** 1604, 2060, 3258, 3407

feat(extra-natives/five): track switching

---

code/components/citizen-scripting-lua/src/LuaOS.cpp

With `os.execute` being sandbox disabled, this offers an alternative for creating directories in Lua.
`LuaOSCreateDir` taps into and works with the VFS system directly to offer a more concise solution for creating directories instead of leaving `os.execute` open for anything and everything.
Server, ScRT: Lua

feat(citizen-scripting-lua): Add os.createdir function

---

code/components/citizen-server-impl/src/GetConfigurationMethod.cpp

This code path is affected by a potential race condition during server initialization, as commands may be executed before the resource context is fully initialized.
Early-out if we are not initialized, as there is no res cache to target yet.
Server
**Platforms:** Windows (Server)
/

fix(server): resMan init race

---

ext/native-decls/GetGlobalPassengerMassMultiplier.md
ext/native-decls/GetVehicleXmasSnowFactor.md

it appears the hyperlink does not work on the native docs, i believe this is because it was previously in lowercase.
fix SET_GLOBAL_PASSENGER_MASS_MULTIPLIER and SET_VEHICLE_XMAS_SNOW_FACTOR hyperlinks.
Fix hyperlinks between natives.
...
changing the case of the native hashes.
...
FiveM, Natives
...

fix(native-decls): fix native hyperlinks

---

code/components/extra-natives-five/include/Train.h
code/components/extra-natives-five/src/TrackNatives.cpp
code/components/gta-streaming-five/src/PatchTrackLimits.cpp

Expands the hardcoded track limit of 27 tracks to 127 (though can be easily expanded in the future by modifying kMaxTracks in extra-natives-five/TrackNatives.cpp and gta-streaming-five/PatchTrackLimits.cpp.
With the introduction of track switching with https://github.com/citizenfx/fivem/pull/3044 There is a bigger need for having more available tracks (Base GTA takes up 12, Leaving 15 for custom tracks that may be taken up by different map resources and track switching)
By replacing all instances of the original array holding track data and replacing it with a larger allocated array. All checks for trackIndex being less then 27 have also been replaced with kMaxTracks or kMaxTracks - 1. 
Two other track related functions were also rewritten and placed into TrackNatives.cpp because of …

feat(five/streaming): expand train track array

---

code/components/gta-core-rdr3/src/PatchAMV.cpp

There is a global bitset used to store the enabled/disabled state of every AMV. This bitset has a hardcoded size of 6016 entries, once there are more AMVs than the bitset size, it starts reading/writing out-of-bounds. This causes the AMVs to start blinking and can potentially crash.
This patch re-allocates that bitset with enough space to fit the capacity of all the AMV pools. The functions that access it are patched to point to the new buffer and use the new size constants.
RedM
**Game builds:** 1491, 1436, 1355, 1311
Fixes #2821.

fix(core/rdr3): AMV hardcoded limit causing blinking

---

code/components/extra-natives-rdr3/src/HudNatives.cpp
ext/native-decls/GetMinimapType.md

Get the minimap type in RDR3
...
Return the value 0,1,2 or 3 depending on whether the map is off, standard, expended, or simple. 
...
RedM natives
...
Get the minimap type after edit it with SetMinimapType(): ✅
Get the minimap type after edit it in the pause menu: ✅
Fixed the missing native to get the minimap type set by SetMinimapType()

feat(extra-native-rdr3): `GET_MINIMAP_TYPE`

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/GetEntityRemoteSyncedScenesAllowed.md
ext/native-decls/SetEntityRemoteSyncedScenesAllowed.md

The original GTA network code includes sanitization for local player peds, but it still allows malicious actors to permanently desync a player’s ped on all remote clients. Additionally, other remotely owned entities lack any sanitization, making them vulnerable to similar abuse.
- Introduces a template-based `Sanitize` method for all game events, streamlining future sanitization implementations.
- Blocks all networked synchronized scenes containing entities that are not owned by the requesting client.
- Provides a bypass mechanism for specific entities via `SET_ENTITY_REMOTE_SYNCED_SCENES_ALLOWED`.
- Allows retrieval of the current bypass state with `GET_ENTITY_REMOTE_SYNCED_SCENES_ALLOWED`.
**Note:** Once this change reaches general availability, client-side sanitization can be removed …

tweak(gamestate/server): sanitize network synchronized scene

---

code/components/citizen-scripting-core/src/ResourceScriptFunctions.cpp

The strict state bags mode prevents writing by the server. My PR corrects this.
With a `#ifndef` to check that the execution is done on the client side
Server

fix(citizen-scripting-core): strict mode only for the client

---

code/components/extra-natives-five/src/VisualSettingsNatives.cpp
ext/native-decls/GetVisualSettingFloat.md

This PR introduces a new native function that retrieves values from `visualsettings.dat`. While a setter already exists for modifying these values via script, there was previously no way to read them. This addition provides a convenient method for accessing visual settings.
I had to redo this PR since i messed up the initial PR, as i initially worked on it on the master branch and didn't do a separate branch for it.
old PR : https://github.com/citizenfx/fivem/pull/2951
...
Create a new native which allows getting the floating point value of a specific visualsettings.dat setting.
...
FiveM
...
**Game builds:** 3095, 3258

feat(extra-natives/five): visual settings getter native

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp

This introduces a new server-side event called `serverEntityCreated` that gets called when a server-side script creates a new entity with invoking natives like `CREATE_VEHICLE_SERVER_SETTER`.
Triggering `serverEntityCreated` when we create an entity on the server-side per synctree initialization. 
FiveM, Server
resolves #2658

feat(gamestate/server): serverEntityCreated event

---

code/components/gta-core-five/src/CrashFixes.SelfCollision.cpp

Fix a game crash when two collisions collide with each other without having a valid m_Bounds. This is happening for specific objects, mostly testing objects that are not used in the map but are spawned by malicious players to make people nearby crash. By default when spawning the prop there is no problem, but if the player or something external hits a sub-object that makes it move and collide with another sub-object of the same object it will reproduce this crash.
Hooking the `ProcessSelfCollision` function and validating that the `boundComposite` and `boundComposite->m_Bounds` are valid
FiveM
**Game builds:** 1, 1604, 2060, 2189, 2372, 2545, 3095, 3258, 3407
fixes #3173

fix(gta-core-five): validate bounds collisions

---

code/components/citizen-scripting-v8/src/V8ScriptRuntime.cpp
data/shared/citizen/scripting/v8/bufferish.js
data/shared/citizen/scripting/v8/main.js
data/shared/citizen/scripting/v8/msgpack.d.ts
data/shared/citizen/scripting/v8/msgpack.js

Swaps out the outdated and unsupported [msgpack-lite](https://github.com/kawanet/msgpack-lite) package for [msgpackr](https://github.com/kriszyp/msgpackr), improving performance (58-95% faster depending on data and size) and adding support for more features (some are disabled for compatibility purposes).
Swaps out the custom version of msgpack-lite with [msgpackr](https://github.com/kriszyp/msgpackr), adds [bufferish](https://github.com/kawanet/bufferish) to maintain backwards-compatibility for unknown types, and uses some patches to behave more like msgpack-lite.
ScRT: JS
**Game builds:** FXServer 13019, FiveM 3258, RedM 1491
Supersedes https://github.com/citizenfx/fivem/pull/2931 and https://github.com/citizenfx/fivem/pull/3018.

feat(v8/scripting): swap from msgpack-lite to msgpackr

---

.github/workflows/build_alpine_container.yml
.github/workflows/ci/build_linux.sh
.github/workflows/ci_build.yml
.github/workflows/pr_opened.yml

Addresses two oversights from a previous change (#3212).
- The repository name and owner name are now converted to lowercase before pushing the builder image to the registry. This ensures compatibility with GHCR, which does not support uppercase characters in image names.
- Authentication with the container registry is now performed prior to pulling the image, addressing issues related to private access settings.
**Note:** While these changes have been tested, enterprise organizations may have different configurations when scoping access to private container images. As such, there is no guarantee that this will behave as intended across all environments.
GitHub CI
**Platforms:** Github-hosted Runner
/

tweak(github/ci): registry auth and lowercase image name

---

code/components/citizen-scripting-node/src/NodeScriptRuntime.cpp

Resolves an error from #3201.
The bufferish module was only being loaded in the client runtime.
ScRT: JS
n/a
n/a

fix(scripting/node): load bufferish module in server scripts

---

code/components/gta-streaming-five/src/PatchSkeletonCrash.cpp

Validate that the component obtained from the attachment index is not -1, which represents an invalid position in the component array.
There are some peds that don't have the same attachment bones as the common ones and when the ragdoll is activated with a weapon it causes it to crash near people.
Patching a part of the `CPedWeaponManager::SwitchToRagdoll` function to validate that the `r13` register representing the component value is not -1.
FiveM
**Game builds:** 1, 1604, 3407
fixes #3185

fix(gta-streaming-five): sanitize ragdoll component based in attach bone

---

code/components/citizen-scripting-node/src/NodeScriptRuntime.cpp

Came up while running with PageHeap enabled.
`FreeIsolateData` deallocates `m_isolate_data`, but `m_nodeEnvironment` still holds a reference to this object in `isolate_data_`. When `FreeEnvironment` is called, it passes this invalid pointer to the `CallbackQueue` via `std::forward`, potentially causing a read access violation on already freed memory.
We now call `FreeIsolateData` after `FreeEnvironment`, deallocating `m_isolate_data` only after no more object access is guaranteed.
Node.js v22 ScRT
/

fix(scripting/node-v22): isolate data deallocation sequencing

---

code/components/gta-core-rdr3/src/EntityDeletionHacks.cpp

currently the native DeletePed and DeleteEntity would allow to delete a player , just like FiveM has done it , we do the same for RedM
by not allowing the player to be deleted which it shouldnt be allowed just like fivem has done.
RedM
1491
windows
#2344

fix(gta-core-rdr3): prevent player from being deleted when using `DELETE_/PED/ENTITY`

---

data/shared/citizen/scripting/v8/main.js

Fixes an oversight where int64s were encoded to BigInt. Breaking compatibility as msgpack-lite didn't do the same
Force int64s to be encoded as a number same as msgpack-lite
FiveM, RedM, Server, ScRT: JS
#3234 #3232

fix(v8/scripting): don't encode int64 to BigInt

---

code/components/citizen-game-main/src/FrontendNui.cpp
code/components/glue/src/GtaNui.cpp
code/components/nui-core/include/CefOverlay.h
code/components/nui-core/src/CefInput.cpp
code/components/rage-input-five/include/InputHook.h
code/components/rage-input-five/src/InputHook.cpp
code/components/rage-input-rdr3/include/InputHook.h
code/components/rage-input-rdr3/src/InputHook.cpp

This fixes regressions introduced by some previous changes and improves inconsistencies across different input methods.
[tweak(nui/core): disable cursor clipping in main menu](https://github.com/citizenfx/fivem/commit/1cdd2262bb9266129d865a8fdb0a18ad030a05a3) 
Small regression introduced by a previous change done by me (https://github.com/citizenfx/fivem/pull/3083) that enabled cursor clipping in the main menu, which is an unwanted behavior in general.
[tweak(input/five): only flush mouse buttons on full focus loss](https://github.com/citizenfx/fivem/commit/0f9ddca23f842bc1a4a63c42375417b183dfdc9f) 
The current implementation is a bit confusing, when we set 'SetGameMouseFocus' in 'InputHook' to false, there are still cases where inputs get passed through, for example when a NUI has focus …

tweak(input/five): usabillity improvements

---

code/components/gta-core-five/src/PedAlternateVariationCache.cpp

This PR fixes an oversight introduced in https://github.com/citizenfx/fivem/pull/3195 that causes hairstyles to reset when equipping or removing a mask.
Previously, `outArray->m_count = 0;` was only called when the condition in `GetAlternateVariationsCacheEntry` was met. This PR ensures that it is always called, preventing unintended hairstyle resets.
Additionally, the assert statement has been removed. While not directly related to the fix, it was unnecessary.
FiveM
fixes #3236

fix(game/five): hotfix for disappearing hair on mask switch

---

code/components/gta-core-five/src/PatchVehicleRadioSync.cpp

Fixes an issue in >2944. As behaviour was changed with radio station syncing. This restores the ability for a passenger to change the radio station to a custom station without it being set to 255 (OFF)
Redirect call to ``GetRadioStationMetaIndex`` which contains all registered radio stations without filtering for stations that are apart of Dat151RelType 124 (RadioStationList2). Restoring previous functionality
FiveM
Tested with custom radio stations + vanilla radio stations
**Game builds:** 2944, 3258, 3407

fix(five/game): custom station sync from passenger

---

code/components/extra-natives-rdr3/src/NativeFixes.cpp

Prevent the native `GET_CLOSEST_OBJECT_OF_TYPE` from converting a non-networked object to networked, this causes that when using this native many times it converts unwanted objects to networked and causes the synchronized object pool to fill up quickly.
Removing instructions that check if the object is already networked.
RedM, Natives
fixes #2833

fix(extra-natives-rdr3): prevent local entities to be converted to networked objects

---

code/components/gta-core-five/src/CrashFixes.VerifyCWeaponInfo.cpp

Mitigates crashes caused by accessing a `CWeaponInfo` object that has a valid base class (`CItemInfo`) but an unexpected sub-type.
This PR leverages RAGE's custom RTTI implementation to verify the class hash of the supplied `CxxxInfo` object. If the check fails, the function returns early with zero, preventing invalid pointer dereferences further down the call stack.
Although the game provides a native function for this validation via a vtable call, newer game builds have obfuscated and significantly altered its behavior. To ensure cross-build compatibility, this PR implements a custom check instead.
FiveM
**Game builds:** 1604, 2060, 2189, 2372, 2545, 2612, 2699, 2802, 2944, 3095, 3258
fixes #3250

fix(core-five): CWeaponInfo crash mitigation

---

code/components/extra-natives-five/src/Draw2dNatives.cpp

Fix a crash when running native `DRAW_LINE_2D` due to a shift in the `_setDrawRectCoords` function as of gamebuild 3407.
Change function offset for version b3407 and later.
FiveM, Natives
**Game builds:** 3095, 3258, 3407
fixes #3126

fix(extra-natives-five): draw rect function offset

---

code/components/citizen-server-impl/include/GameServerNet.h
code/components/citizen-server-impl/src/GameServerNet.ENet.cpp
code/components/citizen-server-impl/src/PlayerScriptFunctions.cpp
ext/native-decls/GetPlayerPeerStatistics.md
ext/native-decls/GetPlayerPing.md

This adds the ability to get packet loss, packet loss variance, and round trip time variance, rtt is already revealed via GET_PLAYER_PING but this still re-adds it for consistency
Having some Prometheus endpoints here might make sense in the future, not sure if adding more endpoints is wanted outside of perf specific stuff though.
Server

feat(server): add `GET_PLAYER_PEER_STATISTICS` to get useful peer stats

---

code/components/citizen-server-impl/src/ServerResourceList.cpp

Like the .git folder, we ignore the .github folder from the resource scan so git repos with a .github folder do not result in a warning during a resource scan.
Adding an additional check to the resource scan loop so that resources with the name ".github" are skipped.
Server

tweak(server): ignore resources that have a name starting with '.' in resource scan

---

ext/native-decls/ExecuteCommand.md

The goal of this PR is to help anyone else that experiences the same issue I did, with being unable to use ExecuteCommand in my resource, without first adding an acl for the resource, and attempting to google the issue only told me how to add ACLs for players.
This PR is achieving that goal by adding documentation to the ExecuteCommand native, to include a simple pointer towards how to add an acl for a resource.
Natives
**Platforms:** N/A
N/A

Add documentation to ExecuteCommand native

---

code/components/gta-core-five/src/PatchBlipCategories.cpp

Game builds <= `2189` require a different approach for patching this as the instruction flow differs in some critical sections.
Temporarily disable this patch on builds <= `2189` to avoid crashes.
(Given the current game build usage, I propose this approach instead of a global revert, as some servers and scripts have already adapted to this feature.)
FiveM
**Game builds:** 1604, 2060, 2189, 2372 
/

fix(core-five): tmp disable expanded blip categories on builds <= 2189

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp

This pull request fixes an issue where fuel was being consumed even when the vehicle's engine was off. The [Fuel Consumption Documentation](https://docs.fivem.net/docs/scripting-manual/using-new-game-features/fuel-consumption/) states that fuel should be consumed only when the engine is running, but this must have been overlooked.
Added a check to ensure fuel consumption only happens when the engine is on.
FiveM, Natives
**Game builds:** -

fix(extra-natives-five): process fuel only when engine is on

---

code/components/citizen-server-impl/src/GameServer.cpp
code/components/citizen-server-impl/src/state/ServerGameState.cpp

This disables the forced start of the 'sessionmanager' resource when OneSync is enabled and the game type is GTA V.
Unlike RDR2, GTA V does not require any logic that is implemented in the 'sessionmanager' resource when running with OneSync enabled. The Lua scheduler implementation for invoking remote function references in https://github.com/citizenfx/fivem/blob/76e67bd59382996a816b66eb5e9760bda2560863/data/shared/citizen/scripting/lua/scheduler.lua#L567 that uses sessionmanager as a script host is deprecated and not functional, so this should not break anything.
FiveM
**Platforms:** Windows (Server), Linux
Resolves #2876

tweak(gameserver): Don't enforce sessionmanager with OneSync

---

code/components/citizen-scripting-core/include/ScriptSerialization.h
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
code/components/extra-natives-rdr3/src/EntityNatives.cpp
code/components/gta-streaming-rdr3/include/EntitySystem.h
ext/native-decls/GetEntitiesInRadius.md

This PR introduces a new native function that retrieves entities within a specified radius using various parameters. It addresses several key issues:
- **Entity Set Limitations:** Current entity sets are limited to 255 entries, and many servers fail to clear them, leading to pool overflows.
- **Single Object Limitation:** The existing `GET_CLOSEST_OBJECT_OF_TYPE` function returns only one object and one model, which restricts its usability.
- **Performance Improvements:** Although servers can achieve similar results using Lua with the `GET_GAME_POOL` native, running this function every frame with same logic takes approximately 0.45ms in Lua, whereas the new native performs the task in around 0.05ms. [Done just for test performance no one use this every frame]
The new native function …

feat(extra-natives-rdr3): add `GET_ENTITIES_IN_RADIUS` for RedM

---

code/components/gta-core-five/src/GameAudioState.cpp

This PR changes the default value of the game_useSynchronousAudio setting to true, which removes the hard cap of 188 FPS in FiveM. The goal is to improve the out-of-the-box experience by allowing players to benefit from uncapped frame rates without requiring manual configuration.
EDIT: I've read the https://github.com/citizenfx/fivem/issues/2354 issue ( checking if it's already an issue posted about this ), i can confirm that this change completely removes the stuttering, it was tested on one of my servers, every player with a decent PC was getting that framerate, and after enabling game_useSynchronousAudio, the stuttering was gone, and also they had unlimited FPS.
This PR updates the default value passed to the game_useSynchronousAudio console variable from false to true.
FiveM
... …

tweak(gta-core-five): set game_useSynchronousAudio convar default true

---

code/components/citizen-devtools/src/ResourceTimeWarnings.cpp
code/components/citizen-server-gui/src/PlayerList.cpp
code/components/conhost-v2/src/ConsoleHostGui.cpp
code/components/conhost-v2/src/ConsoleHostImpl.cpp
code/components/conhost-v2/src/DrawPerf.cpp
code/components/gta-net-five/src/CloneDebug.cpp

This PR includes various improvements and bug fixes for ImGui-based UIs, addressing crashes and usability issues encountered in the client and server interfaces.
- Fixed a client crash when using the search function in the `pgRawStreamer` Debug window. The ImGui clipper does not support modifying the item list during iteration.
- Fixed a server crash that occurred when collapsing a player info window in `svgui`.
- Improved console focus behavior to prevent floating ImGui windows from getting stuck behind the client console.
- Adjusted focus behavior for performance widgets, ensuring that `drawPerf` and the resource time warning widget no longer steal focus when their viewport is clicked.
FiveM, Server
/

fix(imgui): various improvements

---

code/components/conhost-v2/src/DrawPerf.cpp

Following support threads in the Discord guild, this change (#2953) still confuses users as Microsoft clamps CPU utilization values to 100% in task manager.
Clamp the CPU utilization value to a maximum of 100% to make sure the value matches the one displayed in task manager.
FiveM
/

tweak(conhost-v2): clamp CPU usage to 100%

---

code/components/gta-core-rdr3/src/GameInitRage.cpp

Fix an issue where users having a custom startup.meta file inside of their Red Dead Redemption or Red Dead Online installation would lead to the game failing to load correctly.
By preventing the game from acknowledging the files existance. Tested with problematic [startup.meta](https://gist.github.com/Ehbw/32275b1ee13e5d6f1b880cf448e5873c) file placed in x64/data/ of my Red Dead Online installation (which is used by redm). In normal conditions this file would never exist and the function would normally return false as is. So no
RedM
**Game builds:**  1491

fix(core/rdr3): block custom startup.meta file

---

code/components/voip-mumble/include/MumbleClientImpl.h
code/components/voip-mumble/src/MumbleClient.cpp
code/components/voip-mumble/src/MumbleCrypto.cpp

Send resync for crypt state in situations where we've failed to decrypt after a certain span of times
After 1s of not being able to decrypt a packet from the server we sent a resync request, copying behavior [from mumble](https://github.com/mumble-voip/mumble/blob/master/src/mumble/ServerHandler.cpp#L244-L254), notably the time we wait is different here, we send ping packets every 1 second, mumble only does it every 5 seconds.
This should hopefully fix some of the last few edge cases where people have reported "i can talk, but I can't hear anyone"
FiveM, RedM
**Game builds:** Agnostic

fix(client/mumble): request resync if we fail to decrypt a packet after 1 seconds

---

code/components/legitimacy/component.json

Fixes an issue with building the RedM client. where "conhost-v2" would fail to load because of legitimacy.dll missing its mojo.dll dependency. 
Add mojo as a dependency for the legitimacy component. Ensuring that mojo project files are built for all games (server, rdr3, ny) rather then just five (where fxdk-main depends on it)
FiveM, RedM

fix(legitimacy/rdr3): add mojo as a dependency

---

code/components/citizen-server-impl/src/state/ServerGameState.cpp
code/components/gta-net-five/src/ClientRPC.cpp
code/components/gta-net-five/src/CloneManager.cpp
code/components/gta-net-five/src/NetServerObject.cpp

Prevent clients from being able to delete server-setter vehicles if ``sv_protectServerEntities`` is enabled. While also minimising the impact on the client that attempts the deletion.
By blocking clone removal on the server side if the entity the client is attempting to delete is owned by a server-script. Checks on Functions related to delete Peds, Vehicles and Objects are hooked to ensure that these entities cannot be deleted by game code/natives. This prevents desync cases where the entity owner has deleted the entity on their client. 
FiveM, Server
A test resources used to ensure the new changes worked and previous behaviour remained the same is provided with more details being found in server.lua: 
[entity-protection.zip](https://github.com/user-attachments/files/19267120/entity-protec …

feat(gamestate/server): sv_protectServerEntities

---

code/components/gta-streaming-rdr3/src/PatchTextureOverride.cpp
ext/native-decls/DoesTextureExist.md
ext/native-decls/RemoveTexture.md

This PR increases the number of textures that can be created from the previous limit of 32 (reserved only for player faces) to 512. This change is a first step toward expanding the scope, allowing server owners to apply textures to other parts of the body, such as legs, torso, and more. Additionally, two new natives have been introduced: `REMOVE_TEXTURE` and `DOES_TEXTURE_EXIST`, which help manage textures.
- Allocates a new array for 512 texture overrides and updates related pointers and offsets.  
- Hooks the texture allocation function with injected stubs to enforce the new limit.  
- Registers new natives (`REMOVE_TEXTURE` and `DOES_TEXTURE_EXIST`) for texture management.
Redm

feat(core/rdr3): increase texture override pool size

---

code/components/gta-streaming-rdr3/src/PatchTextureOverride.cpp

This PR temporarily reverts the `max serialize` changes due to inconsistencies between the production and canary environments. Once basic functionality is confirmed to work correctly in the canary environment, the change will be reintroduced and pushed to production.
By disabling the affected part of the code to prevent environment mismatches and ensure stability in production.
RedM

fix(core/rdr3): revert serialize component changes

---

.github/workflows/ci_build.yml

https://github.com/actions/runner-images/issues/11101
Bumping the Ubuntu version of the Linux runners to `24.04`.
GitHub CI
**Game builds:** /
**Platforms:** /
/

fix(github): bump Linux runner Ubuntu version

---

code/components/gta-core-five/src/CrashFixes.SelfCollision.cpp

Fix a crash that occurred in the call to the `CalcClosestLeafDistance` function that is responsible for traversing the bvh to find the squared distance to the closest leaf node from the given position.
The function could crash if the bvh or bvhNode pointer was null.
Adding a check before the original call of the function.
FiveM
**Game builds:** 1604, 3095, 3407
fixes #3155

fix(gta-core-five): invalid bounding volume hierarchy

---

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
ext/native-decls/GetTrainTrackIndex.md

Introduces a way for client scripts to know which track a train is currently on. As with track switching a train can change track index from where it was originally created on. Requested by GlitchDetector
By introducing ``GET_TRAIN_TRACK_INDEX`` to allow client scripts to retrieve the trains current track index.
FiveM, Natives
**Game builds:** 1604, 3258

feat(extra-natives/five): GET_TRAIN_TRACK_INDEX

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp

This pull request adds routing bucket event listeners to help developers and server owners handle player/entities routing bucket changes.
with these listeners, it becomes **much easier to manage** features tied to virtual worlds.
for example, doors that need to stay in sync within a specific routing bucket can be tracked through events when players move or are removed, this allows clean separation of logic per virtual world, this is just one example.
By exposing these events, server-side scripts can register handlers to respond in real time when a player moves between buckets. this gives full control to manage entities/players or logic tied to specific virtual worlds, such as syncing doors, tracking world-specific data, etc.
```lua
AddEventHandler("onPlayerBucketChange", function(player, …
```

feat(citizen-server): add event listeners for routing bucket changes

---

ext/native-decls/SetEntityOrphanMode.md

Cleanup the wording in the native declaration to make it less confusing, and add information about how this works with trains
> **NOTE**: This native doesn't guarantee the persistence of the entity.
Is confusing wording, replaced with what is actually defined behavior (that the server will not delete the entity in its normal garbage collection)
Server
N/A
- [N/A] Code compiles and has been tested successfully.

tweak(native-decls): update documentation for trains

---

code/components/citizen-resources-client/src/KVScriptFunctions.cpp
ext/native-decls/kvp/DeleteResourceKvpNoSync.md
ext/native-decls/kvp/SetResourceKvpFloatNoSync.md
ext/native-decls/kvp/SetResourceKvpIntNoSync.md
ext/native-decls/kvp/SetResourceKvpNoSync.md

just like the server we add client asynchronous natives.
using async natives reduces the load on the client as it's not always  needed to wait for the operations to finish
the goal is to have it stream lined with the server natives that already have async natives
FiveM/RedM
windows

feat(kvp-client): add client asynchronous kvp natives

---

code/components/extra-natives-five/src/InputNatives.cpp
data/shared/citizen/scripting/v8/main.js
ext/native-decls/RegisterRawKeymap.md
ext/natives/codegen_out_js.lua

This somehow managed to slip through when I originally made this pr, this
just swaps the native declaration and ordering in code to be the right order
since when `RawKeymap` was called the ordering is `keyDown`, `keyUp`.
This fixes another oversight in the initial PR, we should always register
`m_wasTriggered` changes, even if we don't have refs, otherwise we will
have "perma stuck" keymaps if the user decides to not register one part of
the keymap
This also adds a proper error message if you provide an invalid index
This also fixes an issue with `REGISTER_RAW_KEYMAPS` where it would still supply
a ref id even if there was no function (aka when set to null) to make the reference to, and when
calling into the JS ScRT it would error because `callback` would be null.
This copies the …

Fixes oversights in original RawKeymap PR

---

code/components/gta-core-rdr3/src/PatchBlipLimitCrash.cpp

this pr fixes a crash, when blip limit has been reached `920` and players use the set waipoint in the big map
it causes them to crash.
thanks to @Ktos93
Logs in the f8 console when blip limit has been reached and blocks the player  from using the waypoint, which prevents the crash
the log will help players report to the developers so they become aware of the issues.
RedM
1491
windows

fix(core-rdr3): fix crash when Blip limit is reached RedM

---

code/components/gta-net-five/src/CloneExperiments.cpp

Resolves a common Deadlock related to the Cover system for players that navigate around the 0.0, 0.0, 0.0 coordinates in the games world and its surrounding area's.
By removing a hook in CloneExperiments that accidently made a cover related function no-op in a OneSync environment. Restoring its original behaviour in OneSync and resolving the deadlock
RedM
Fixes https://github.com/citizenfx/fivem/issues/3203 Fixes #2801 and  https://forum.cfx.re/t/heartlands-world-origin-client-freeze-when-moving-quickly/5182328

fix(net/rdr3): Deadlock in CProcessControlUpdateGraph

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp

Fixes a server crash when using the `onEntityBucketChange` new event.  
Unlike `SET_PLAYER_ROUTING_BUCKET`, `SET_ENTITY_ROUTING_BUCKET` requires a different argument type. 
Was an oversight of mine. 
we change to the required argument type
...
windows

fix(server-routing-bucket): change entity argument type

---

code/client/launcher/Main.cpp

Make RedM load vulkan-1.dll from System32 (if available) over the bundled vulkan-1.dll in CEF. 
CEF's M103's vulkan-1 is several years old and is a dev build versioned "1.0.111.2222" and on some system configurations doesn't play well with it leading to some vulkan assertions or "ERR_GFX_STATE" crashes on start-up.
If in some case the user does not have vulkan-1 installed in System32. The bundled vulkan-1.dll in CEF will be used 
In launcher we load vulkan-1.dll as a system.dll similar to what is done for dxgi.dll, d3d9.dll, d3d12.dll, d3d10.dll. Most users will have vulkan-1 present here as during the Red Dead Redemption 2 installation Vulkan 1.1.108 installer is ran which places the file in the users C:/Windows/System32/vulkan-1.dll location.
RedM
**Platforms:** …

fix(client): vulkan load order

---

code/components/gta-net-five/src/NetServerObject.cpp

Fixes an oversight introduced in #3249 
Check if ped/vehicle/object is a nullptr before trying to call GetNetObject, matching the behaviour of the original functions.
FiveM

fix(net/five): factory nullptr check

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/include/state/SyncTrees_Five.h
code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
ext/native-decls/DoesTrainStopAtStations.md
ext/native-decls/GetTrainBackwardCarriage.md
ext/native-decls/GetTrainCruiseSpeed.md
ext/native-decls/GetTrainDirection.md
ext/native-decls/GetTrainForwardCarriage.md
ext/native-decls/GetTrainState.md
ext/native-decls/GetTrainTrackIndex.md
ext/native-decls/IsTrainCaboose.md

Correct CTrainGameStateDataNode for >b2372 and implement several server getter natives for trains
By finishing CTrainGameStateDataNode and correcting the order for >b2372 Originally PR'd alongside server-setter trains (#2322). And implementing getter natives to allow server scripts to take advantage of this with the following natives:
GET_TRAIN_STATE
IS_TRAIN_CABOOSE
DOES_TRAIN_STOP_AT_STATIONS
GET_TRAIN_CRUISE_SPEED
GET_TRAIN_TRACK_INDEX
GET_TRAIN_FORWARD_CARRIAGE
GET_TRAIN_BACKWARD_CARRIAGE
GET_TRAIN_DIRECTION
FiveM, Server, Natives
Provided is a resource created to test these new server natives to ensure they work as intended [train-servers-node.zip](https://github.com/user-attachments/files/18030317/train-servers-node.zip)

feat(gamestate/server): train sync node getters

---

code/components/extra-natives-rdr3/src/GraphicsNatives.cpp
ext/native-decls/GetAspectRatio.md

This PR adds a dedicated aspect ratio native in RedM to mirror FiveM’s existing functionality. While GET_CURRENT_SCREEN_RESOLUTION can technically yield the aspect ratio (x/y), a specific native clarifies its purpose and makes usage more straightforward for developers
It introduces a new native  that directly returns the current aspect ratio
RedM
1491
windows

feat(extra-natives-rdr3): add `GET_ASPECT_RATIO` native RedM

---

code/components/extra-natives-five/src/GamePrimitives_Outlines.cpp
ext/native-decls/sdk/ResetEntityDrawOutlineRenderTechnique.md
ext/native-decls/sdk/SetEntityDrawOutlineRenderTechnique.md

Allow developers to specify a custom shader technique group for entity outlines via a new native (`SET_ENTITY_DRAW_OUTLINE_RENDER_TECHNIQUE`). This expands the flexibility of the outline rendering system, which was previously limited to the unlit technique, and addresses use cases beyond the intended FxDK environment, as some developers rely on this functionality in their own codebases.
> Note: While not critical to FxDK usage, this native aims to improve flexibility for developers already relying on outline rendering in their projects.
Introduces the `SET_ENTITY_DRAW_OUTLINE_RENDER_TECHNIQUE` native, allowing scripts to specify a custom shader technique group for entity outlines. The implementation updates the outline rendering system to use the provided technique group, with a fallback …

feat(extra-natives/five): add support for configurable outline render technique

---

code/components/extra-natives-five/src/PedExtraNatives.cpp
ext/native-decls/SetWetClothPinRadiusScale.md

Add support for controlling wet cloth physics behavior implementing the native `SET_WET_CLOTH_PIN_RADIUS_SCALE`.  
This allows scripts to modify how tightly wet cloth adheres to characters.
Suggestion in [forum](https://forum.cfx.re/t/request-native-toggle-to-set-clothing-to-ignore-wetness/), thanks so much to @alberttheprince
https://github.com/user-attachments/assets/1fb30fd8-79eb-43d1-b639-783407594df3
Creating a native to change the default value in `SetWetClothingHeight`, `ProcessWetClothingInWater`, `IncWetClothing` functions.
FiveM, Natives
**Game builds:** 1604, 3258, 3407

feat(extra-natives-five): add `SET_WET_CLOTH_PIN_RADIUS_SCALE` for wet cloth physics control

---

code/components/gta-core-five/PtfxScriptLimit.cpp

While trying to create a spell system in game, i managed to hit the script ptfx very easily with other players.
I tried to cast ~10 spells in 20 seconds with 20 other players around me, making a total of 200 ptfx.
This made a lot of ptfx created with `StartParticleFxLoopedAtCoord` invisible, because the game couldn't attribute script id to all my requests.
By overriding the init function we have access to multiple limits the game hardcode, the specific "128 ptfx" limit can be changed to 256 very safely, other limits could be changed later but need more research.
FiveM
**Game builds:** 1604 / 2802 / 3258 / 3407
Script used to test :
```
CreateThread(function()
RequestNamedPtfxAsset('core')
local coords = vector3(-1050.7, 458.62, 185.3)
local i = 0
for x = 1, 32 do …
```

feat(core/five): patch script ptfx limits

---

code/components/glue/src/GtaNui.cpp
code/components/rage-graphics-rdr3/include/VulkanHelper.h
code/components/rage-graphics-rdr3/src/RenderHooks.cpp

This pr will add crashometry of the resources that are used by the Vulkan API. The data that I added are the following: GPU name, Vulkan APIversion, and driver version. We want to have this data, to diagnose the Vulkan crashes more precisely. To add to that, I also expanded the error handling in glue. Now, instead of having an assert and not having no data, we display the VkResult, so we know what went wrong. 
The validation layers could also be enabled, but it when it is enabled in the instance, it fails and falls back to d3d12. Matter of fact, you need the Vulkan SDK installed, hence the removal for now.
This pr adds more information to try diagnose crashes, and hopefully guide to a faster solution.
RedM
**Game builds:** 1491  
NA
Thanks @Ehbw for the patterns.

feat(graphics/rdr3): add crashometry for vulkan

---

code/components/citizen-scripting-v8/src/V8ScriptRuntime.cpp

Prevent the FXServer instance from crashing, due to the script name being null when an exception is thrown inside a callback, from inside an eval() function. Not all callbacks work, it might only happen for ones triggered from C++ code. For example the callback of https.get() causes the crash, while the callback from `setTimeout()` doesn't.
A simple reproduction for the issue:
```js
eval(`
const https = require('https');
https.get('https://google.com', res => {
throw new Error("dfgfgdfgdfg")
})
`);
```
A few people reported this crash as if it started happening today, without any changes from their side. Due to the weird nature of eval-ing remotely downloaded code, I have high suspicions (but no proof) that they were using leaked resources with backdoors and the payload was causing the …

fix(citizen-scripting-v8): Crash when formatting an exception stack trace from a callback that's inside an eval() function.

---

code/components/gta-streaming-five/src/CrashFixes.TextureMipLevels.cpp

This will make the minicon filters like `script:*` not show those warning that are not script related.

tweak(console): changed warning type

---

code/components/extra-natives-five/src/PedExtraNatives.cpp
ext/native-decls/AddHealthConfig.md
ext/native-decls/GetPedModelHealthConfig.md
ext/native-decls/RemoveHealthConfig.md
ext/native-decls/SetHealthConfigDefaultArmor.md
ext/native-decls/SetHealthConfigDefaultEndurance.md
ext/native-decls/SetHealthConfigDefaultHealth.md
ext/native-decls/SetHealthConfigDogTakedownThreshold.md
ext/native-decls/SetHealthConfigDyingThreshold.md
ext/native-decls/SetHealthConfigFatiguedThreshold.md
ext/native-decls/SetHealthConfigHurtThreshold.md
ext/native-decls/SetHealthConfigInjuredThreshold.md
ext/native-decls/SetHealthConfigInvincible.md
ext/native-decls/SetHealthConfigMeleeFatalAttack.md
ext/native-decls/SetHealthConfigWritheFromBulletThreshold.md
ext/native-decls/SetPedModelHealthConfig.md

Unfortunately `pedhealth.meta` cannot be streamed via DATA_FILE entries, so decided to add natives to manipulate those values. It allows to change ped model health config, add new health config, remove health config and modify values of existing health configs.
This will allow to set for example default health value that users spawn with on the server without need to use sethealth/setmaxhealth natives. Didn't test functionality of all fields, but for example dying threshold allows us to change default "100" value that our ped dies to other values.
...
Hooked directly to function that returns health config from array, if it exists in our map then return modified values instead.
...
Fivem natives
**Game builds:**  3258

feat(extra-natives-five): Add health config natives

---

code/components/extra-natives-five/src/LightNatives.cpp
ext/native-decls/DrawLight.md
ext/native-decls/PrepareLight.md
ext/native-decls/SetLightAlpha.md
ext/native-decls/SetLightAo.md
ext/native-decls/SetLightCapsuleSize.md
ext/native-decls/SetLightClipRect.md
ext/native-decls/SetLightColor.md
ext/native-decls/SetLightCone.md
ext/native-decls/SetLightCoords.md
ext/native-decls/SetLightDirection.md
ext/native-decls/SetLightExtraflags.md
ext/native-decls/SetLightFadeDistance.md
ext/native-decls/SetLightFalloff.md
ext/native-decls/SetLightFlags.md
ext/native-decls/SetLightHeadlight.md
ext/native-decls/SetLightIntensity.md
ext/native-decls/SetLightInterior.md
ext/native-decls/SetLightPlane.md
ext/native-decls/SetLightRadius.md
ext/native-decls/SetLightShadowDetails.md
ext/native-decls/SetLightShadowFadeDistance.md
ext/native-decls/SetLightSpecularFadeDistance.md
ext/native-decls/SetLightTexture.md
ext/native-decls/SetLightType.md
ext/native-decls/SetLightVolumeDetails.md
ext/native-decls/SetLightVolumetricFadeDistance.md

This PR introduces several new natives to create, delete, and manage all properties of scripted lights. This enables more flexible lighting setups and access to features that were not previously available through the traditional `DRAW_LIGHT_...` natives, such as texture projection, capsule shapes, and volumetric flags.
Instead of using a per-frame draw approach, this PR implements a handle-based system to manage lights. With the `CREATE_LIGHT` and `DELETE_LIGHT` natives, users can create lights that persist across frames, improving both performance and usability.
Persisting light objects means they are reused every frame, instead of being recreated, using a draw-based native would have required a large number of arguments to expose all the fields of the `CLight` class.
This PR is a draft …

feat(extra-natives/five): add light natives

---

code/components/gta-core-rdr3/src/PatchWeaponInfoCrash.cpp

Mitigates crashes caused by accessing a nullptr ``CWeaponInfo`` object. Mitigation for this issue was also possible through server-side scripts listening to ``weaponDamageEvent`` like so
```lua
AddEventHandler("weaponDamageEvent", function(sender, data)
if data.weaponType == 2416459067 then
CancelEvent()
end
end)
```
Before running any logic in CWeaponDamageEvent, we check if the weaponHash provided by the event is valid (does it return a ``CItemInfo`` and is the sub-type ``CWeaponInfo``), if the check fails, the function returns early with zero, preventing crashes.
RedM
fixes #3335

fix(core/rdr3): CWeaponInfo crash mitigation

---

code/components/gta-core-five/src/CrashFixes.Ladder.cpp
code/components/gta-core-rdr3/src/CrashFixes.Ladder.cpp

Prevent the game from crashing when a non-biped ped (e.g., animals, fish) interacts with a ladder and the game attempts to evaluate movement using `CTaskClimbLadder::IsMovementBlocked`.
Check if the rax register that store the `GetBipedCapsuleInfo()` result is valid.
FiveM
**Game builds:** 1604, 3095, 3407
Not public issue but reported by @spoty123

fix(gta-core-five): prevent crash in climbing ladder with non-biped

---

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp

This PR fixes the errors when trying to generate the event docs :

fix(net-event-doc): fix typedoc not recognizing int

---

code/components/citizen-resources-gta/src/TextChangingFunctions.cpp
code/components/gta-streaming-five/src/StreamingFreeTests.cpp
code/components/gta-streaming-five/src/sfFontStuff.cpp
code/components/gta-streaming-rdr3/component.lua

Allow to register custom fonts like in fivem.
And also fix a issue in the `GetFileTypeIdFromExtension` function because is using the extension arg as the fileName and it was containing "garbage" which was preventing the use of the GetStreamingIndexForName function.
Defining a constant to store the number of fonts already registered in the game so we can calculate the index in the `g_fontIds` array. Replacing some patterns to make them work in redm.
RedM

feat(gta-streaming-rdr3): allow registration of custom fonts

---

code/components/extra-natives-five/src/WeaponExtraNatives.cpp

Currently, using `SET_WEAPONS_NO_AUTOSWAP` in combination with enabling ped config flag 48 causes the ped to equip WEAPON_UNARMED when running out of ammo. This behavior should not belong to the purpose of SET_WEAPONS_NO_AUTOSWAP.
Checking in the stub if `g_SET_WEAPONS_NO_AUTOSWAP` is enabled to skip or continue the flow.
FiveM
**Game builds:** 1604, 3407
Reported by @n3xuuu not public issue.

fix(extra-natives-five): avoid weapon change with no swap enabled

---

code/components/gta-core-rdr3/src/PatchWeaponTargetCrash.cpp

Mitigates crash related to nullptr rage::netObject deref from weaponDamageEvent. When a server cannot allocate additional network Ids (e.g. hit the current 8000 network ID limit) or local players cannot register this entity due to network pools being full.
Check if the target is a nullptr at this point in weaponDamageEvent (which should never happen) and return 0 (fail) instead of continuing where it would crash 
RedM
**Game builds:**  1491
RDR2_b1491.exe!sub_1423F081C (0x386)

fix(core/rdr3): crash when targetting invalid ped/player

---

code/components/gta-core-five/src/CrashFixes.RiverEntities.cpp

Fix a crash caused by river entities with null archetype.
Validating the archetype that is located in 0x20 from the river entity(CEntity).
FiveM
Crash reported by @ook3D

fix(gta-core-five): validate river entity archetype

---

code/components/gta-net-rdr3/src/netSyncTree.cpp

Backport https://github.com/citizenfx/fivem/commit/9cb9d1522784fdca2aa0154c6e4f32bea5689b9b and https://github.com/citizenfx/fivem/commit/c0b8ca566319015ce056d863f8c4b6d113321ae6 From FiveM in order to fix the same crashes/unintended behaviour in RedM.
Patching CanApply functions for Vehicle, Ped, Player and Animal Creation nodes in order to properly verify the models used. The game currently only checks if the model is valid but does not check if that model should be used for that entity type (e.g. ped model for a vehicle) leading to unintended behaviour and crashes.
RedM

fix(net/rdr3): verify net object model archetype

---

code/components/gta-core-five/src/CrashFixes.Ladder.cpp

Fix a issue with ladders that detect that some physical object is colliding in the test made by ladder logic, this only seems to happen in a custom map of NoPixel but very sure that can happen in ladders with same environment(cover above the end of ladder)
Clip: https://streamable.com/52f0it
I've checked and I was overwriting some registers that was used after, so here I'm restoring original rax value and r11 that is only used at the end for writing.
FiveM
Can't test cause is in a custom map, can I get a feature branch to ask people with this issue to test if its working?
Not public issue but reported by @d22tny

fix(gta-core-five): overriding ladder registers causing bad collision checks

---

code/components/gta-core-rdr3/src/PatchIncreaseMaxObjects.cpp
code/components/gta-core-rdr3/src/PoolManagement.cpp

Allow to increase networked objects pool in RedM, currently there's a limit of 60.
The structure of the code is the same as that of #3542 made by @Ehbw 
I've tested this increasing up to 200 and looks to work well, but should be good to set the limit to 100 in the pool allow list.
Adding object pool entries that contains a list of pools that are going to be increased alongside `CNetObjObject`.
RedM

feat(gta-core-rdr3): support for increased networked object pool

---

code/components/citizen-devtools/src/ResourceTimeWarnings.cpp

Improve QoL of the pool list search feature by making it case-insensitive, allowing partial matches anywhere within the name and allow filter Items & MaxItems.
https://github.com/user-attachments/assets/49e2fbeb-c10a-4ddf-8f3f-4f64b01e7741
Replaces the strict Starts_with check with a case-insensitive substring search. Now users can type any part of the name, and the filter will match it regardless of case. It also includes Items and MaxItems in the search by converting them to strings and checking if the input matches any part of them.
FiveM, RedM

fix(citizen-devtools): improve search filter of pool list

---

code/components/gta-streaming-five/src/LoadStreamingFile.cpp

Resolves custom collisions failing to load following #3543.
By not allowing custom ybns/collision to be reloaded in RDR3, as for a currently unknown reason it causes crashes for some clients and ultimately breaks its collision.
RedM
**Game builds:** 1491.50
Tested with a custom interior with multiple collision files.
Reported in engineering discord and tied to sub_142B89780 (0x63) / september-solar-beer crashes that begun on august 6th.

fix(streaming/rdr3): don't attempt to reload collisions

---

code/components/loading-screens-five/src/HookLoadingScreens.cpp
code/components/rage-input-five/src/InputHook.cpp
code/components/rage-nutsnbolts-five/include/nutsnbolts.h
code/components/rage-nutsnbolts-five/src/FrameHook.cpp

Prevent crashes caused by reading from a nullptr when `updateBusySpinner` is called from the Render thread.
Although the root cause of this issue requires further investigation, this PR provides a temporary fix to prevent crashes when `updateBusySpinner` is unexpectedly called from the Render thread instead of the Main thread. This call causes a subsequent function to return a nullptr due to failing thread constraint checks in native game code.
The only potential side effect of this fix is missing updates to the busy spinner during the loading of addon data files, but this is still better than outright crashing.
FiveM
fixes #2850

fix(game/five): updateBusySpinner thread constraint check

---

code/components/rage-input-rdr3/include/InputHook.h
code/components/rage-input-rdr3/src/InputHook.cpp

Port improvements made to FiveM's rage-input-five/InputHook.cpp to rdr3 to resolve several issues. Mainly:
- Key inputs getting stuck when losing window focus, opening NUI or pressing F8.
- Cursor randomly getting stuck when trying to access F8.
By backporting several commits made to rage-input-five that resolved issues/improved behaviour. Mainly:
Clearing g_gameKeyArray on focus loss, preventing keys from being stuck down when accessing F8, accessing NUI that takes input or losing focus of the window.
Implementing controlBypasses, to allow for future use of enabling/disabling PTT when focus is being stolen for F8/NUI.
Implementing ``InputHook::IsMouseButtonDown`` and ``InputHook::IsKeyDown`` for future use with custom keymappings. …

feat(input/rdr3): backport fives input hook improvements

---

code/components/citizen-server-impl/include/state/ServerGameState.h
code/components/citizen-server-impl/src/state/ServerGameState.cpp

This currently uses a decently amount of the chunk of time in ETW traces because this gets called per frame, this adds another bool to the SyncData and makes sure we only add the routing target once instead of constantly spamming the write lock.
Reduce the locking done for routing targets
Only adding routing targets once.
Server

tweak(server-impl/sbag): reduce the amount of locking for adding routing targets

---

code/components/gta-core-rdr3/src/PatchWeaponTargetCrash.cpp

Follow up patch for #3547, resolving another crash related to this in cases where an entity is being actively created/destroyed and lacks pedComponents leading to a crash in weaponDamageEvent.
Implementing a nullptr check in the function where ped components are accessed.
RedM
wyoming-washington-thirteen / RDR2_b1491.exe!sub_1423F081C (0x3d6)

fix(core/rdr3): followup for combat crash

---

code/components/gta-core-rdr3/src/PatchIncreaseMaxVehicles.cpp
code/components/gta-core-rdr3/src/PoolManagement.cpp

Allow to increase non and networked vehicles in RedM, the current limit is 40, this aims to allow more boat, trains and all vehicles except draft vehicles for now cause it's need more research.
With this should be good to have the `CNetObjVehicle` in the allowed pool list up to 40.
Patches several hardcoded vehicle limits in the game(total desired vehicles, mission/script limits, and CVehicle cap)
RedM

feat(gta-core-rdr3): support for increased networked vehicle pool

---

ext/native-decls/RegisterFontFile.md
ext/native-decls/RegisterFontId.md

With #3543, ``REGISTER_FONT_ID`` and ``REGISTER_FONT_FILE`` was added to RedM, however the ``game: gta5`` field was not removed from either natives causing them to not be generated for RedM.
Remove ``game: gta5`` fields from RegisterFontId and RegisterFontFile native declaration 
RedM, Natives

fix(ext/native): remove gta5 game field for font natives

---

code/components/citizen-server-main/src/ServerInstance.cpp

The goal of this PR is to remove the players.json endpoint warning that was added when identifiers got removed from the API back in september last year. I think the message could be removed by now as this sometimes causes confusion and nobody asks about the identifiers change anymore. It was added in: https://github.com/citizenfx/fivem/commit/cf1984ab77dcc1f19e2b1ce61ede57eabb2b48d6
This PR removes the players.json endpoint warning
FXServer
**Platforms:**

tweak(server): remove warning about the identifiers change
