citizenfx/fivem

code/components/nui-core/include/CefOverlay.h, code/components/nui-core/src/CefInput.cpp
Combines GiveFocus(hasFocus) and GiveFocus(hasFocus, hasCursor)
Improves backwards compatibility with the fake cursor script
=> NUI: Mouse cleanup

code/client/clrcore/External/Game.cs, code/client/clrcore/External/Vehicle.cs
Based on https://github.com/crosire/scripthookvdotnet/commit/ec2b7167d4f223f9465d6e726bf73b3b4a0eeb8c
=> clrcore: update vehicle's memory offsets to match 1103

code/components/citizen-scripting-lua/src/LuaScriptRuntime.cpp, data/shared/citizen/scripting/lua/deferred.lua, data/shared/citizen/scripting/lua/scheduler.lua
=> Add promise / await implementation

ext/cfx-ui/src/app/app-nav.component.html, ext/cfx-ui/src/app/app-nav.component.scss, ext/cfx-ui/src/app/app-nav.component.ts, ext/cfx-ui/src/app/home/home.component.html, ext/cfx-ui/src/app/home/home.component.scss, ext/cfx-ui/src/app/servers/components/server-filter.component.html, ext/cfx-ui/src/app/servers/components/server-filter.component.scss, ext/cfx-ui/src/app/servers/components/server-filter.component.ts, ext/cfx-ui/src/app/servers/components/servers-list.component.ts, ext/cfx-ui/src/app/settings/settings.component.scss
Preview: https://imgur.com/a/4Owgm
=> Ping filtering, steam auth indicator and improvements.

code/client/clrcore/CitizenTaskScheduler.cs
* Root tasks were added m_inTickTasks and never cleared.
* The memory leak can be seen by simply adding `Debug.WriteLine( $"[TASK] {m_inTickTasks.Count}" );` to the end of CitizenTaskScheduler.Tick and loading up a C# plugin with an OnTick event.
* This is fixed by setting the root m_inTickTasks to null. The locking is also changed a bit to support m_inTickTasks being null. An alternative fix might be to remove from the lastInTickTasks list when a task is completed.
=> Fixes: Memory leak in CitizenTaskScheduler.Tick

code/components/extra-natives-five/src/VehicleExtraNatives.cpp, ext/natives/codegen_cfx_natives.lua
Fixes the repair glitch that occurs when enabling an vehicle extra.
=> Repair fix

code/components/font-renderer/src/GtaGameInterface.cpp
Preview: https://i.imgur.com/Z6qoou4.png
Watermark exists while in-game
=> Disable watermark in main menu

code/client/clrcore/External/Ped.cs, code/client/clrcore/External/World.cs
``
World.GetAllProps()
``
Returns all props on the map
``
World.GetAllPeds()
``
Returns all peds on the map
``
World.GetAllVehicles()
``
Returns all vehicles on the map
``
World.GetAllPickups()
``
Returns all pickups on the map
=> clrcore: Add more Ped DrivingStyles and new World methods

code/tools/ci/build_server_2.sh
All builds deserve a version :stuck_out_tongue:
=> ci: add version to docker builds

.travis.yml, code/Rockerfile
I forgot to add these variables in #135
=> ci: add travis env variables to rocker builds

docs/building.md
I was having trouble building this without going into the fivem directory which the 'git clone' generates.
=> missing 'cd fivem'

.travis.yml, code/Rockerfile, code/tools/ci/build_server_2.sh
=> ci: fix branch and build number env variables

code/client/shared/Registry.h
It fixes compilation of `CitiCore` on linux.
=> shared: fix undefined inline variable

code/client/clrcore/External/World.cs
- Add Cloud Hats
- Add Cloud Hat Opacity
=> clrcore: Add Cloud Hats

code/client/clrcore/External/Game.cs, code/client/clrcore/External/MpPedDataStructs.cs
Most of the values are still unknown, However there are 3 useful variables that _are_ known.
Known values in the struct:
1. Collection Hash
2. Tattoo Hash
3. Zone ID (torso/head/arms/etc)
=> Add tattoo collection data function

code/components/extra-natives-five/include/NativeWrappers.h, code/components/extra-natives-five/src/NativeWrappers.cpp, code/components/extra-natives-five/src/PedExtraNatives.cpp, code/components/extra-natives-five/src/VehicleExtraNatives.cpp
This PR is implementing few getters for ped customization related natives.
https://github.com/citizenfx/natives/pull/66
=> Implement new ped customization getters

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
This PR is implementing vehicle wheelie state natives (get/set).
Example script: https://pastebin.com/J6XGbkCW
Demonstration: https://gfycat.com/fairdisloyalafricanfisheagle
https://github.com/citizenfx/natives/pull/79
=> extra-natives: wheelie state offset

code/components/extra-natives-five/src/InterfaceExtraNatives.cpp
This PR is implementing getters for bigmap native. (https://runtime.fivem.net/doc/natives/#_0x231C8F89D0539D8F)
https://github.com/citizenfx/natives/pull/83
=> Implement bigmap getters

code/client/clrcore/InternalManager.cs
Allows methods using `TickAttribute`, `EventHandlerAttribute` and/or `CommandAttribute` to be `public`/`internal`/`private` and `static`.
Also added some variations for `CommandAttribute`:
```csharp
[CitizenFX.Core.Command("mycommand")]
private void OnMyCommand() { }
[CitizenFX.Core.Command("mycommand")]
private void OnMyCommand(string[] args) { }
// Server only
[CitizenFX.Core.Command("mycommand")]
private void OnMyCommand(CitizenFX.Core.Player player) { }
// Server only
[CitizenFX.Core.Command("mycommand")]
private void OnMyCommand(CitizenFX.Core.Player player, string[] args) { }
// Legacy
[CitizenFX.Core.Command("mycommand")]
private void OnMyCommand(int source, List<object> args, string raw) { }
```
=> allows command/event/tick methods to be public, internal, private and static

code/client/citicore/ComponentLoader.cpp, code/client/citicore/ComponentLoader.h, code/client/citicore/console/ProgramArguments.h, code/client/shared/StdInc.h, code/components/citizen-scripting-mono/src/MonoComponentHost.cpp
- Removed some unused code from ComponentLoader.cpp
- Converted some c-style code into more c++-like code
- Constified some functions in ComponentLoader
- Added a couple utility functions to fwPlatformString and marked fwPlatformString::ConvertString as static
=> Code cleanup, clearing some warnings and fixing Linux build

code/components/extra-natives-five/src/PedExtraNatives.cpp
This PR is implementing getters for ped hair colours (``_SET_PED_HAIR_COLOR``)
https://github.com/citizenfx/natives/pull/110
=> Implement ped hair colour getters

code/components/citizen-server-impl/src/ClientRegistry.cpp
Add server event: playerJoining, which corresponding to client event: onPlayerJoining.
=> server: add playerJoining event

code/client/clrcore/External/VehicleWindowCollection.cs
Added following methods:
```csharp
VehicleWindow[] GetAllWindows();
void RollUpAllWindows();
bool HasWindow(VehicleWindowIndex window);
```
Updated following method:
```csharp
void RollDownAllWindows();
```
=> Added some vehicle window methods and updated RollDownAllWindows

data/shared/citizen/scripting/lua/scheduler.lua
Hopefully this can serve as an alternative to #157
=> scripting/lua: Rework handling of coroutines and promises

code/components/gta-streaming-five/src/UnkStuff.cpp
Preview: https://gfycat.com/GoodSolidDrongo
=> Patch fuel tank leaking in netgames

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
This native returns train's current track node index.
Example (by TheIndra): https://i.imgur.com/Eo6rwir.png
https://github.com/citizenfx/natives/pull/141
=> Implement train track node getter

code/components/citizen-server-impl/include/state/SyncTrees_Five.h
Unfortunately I don't think any useful server sided "natives" could be made for this node.
=> complete CVehicleCreationDataNode

code/vendor/lua/src/lbaselib.c, code/vendor/lua/src/lobject.h, code/vendor/lua/src/lvm.c
See commit messages...
On a similar note, would it be possible to dos2unix, or something along those lines, vendor/lua? There are similar changes I'd like to make in lmathlib, but the line-endings are wildly inconsistent (CRLF vs LF) and the diff's are borderline unreadable.
=> vendor/lua: luaV_gettable modifications

code/components/extra-natives-five/src/InteriorExtraNatives.cpp
This natives may be really useful for interior makers.
Also, there's demonstration of small features created using this natives.
https://gfycat.com/anotherfantasticgrebe
https://gfycat.com/limpadmiredleafwing
https://gfycat.com/vacantunknownbongo
https://gfycat.com/finishedfaithfulcanadagoose
https://github.com/citizenfx/natives/pull/167
=> Implement additional interior natives

code/components/extra-natives-five/src/PedExtraNatives.cpp
This PR not fixing and not adding anything. Just a slight refactor of `PedExtraNatives.cpp` file to make it looks more clean and readable.
=> Refactor ped extra natives

code/components/citizen-server-impl/include/state/SyncTrees_Five.h, code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
New natives!
`GET_VEHICLE_COLOURS`
`GET_VEHICLE_EXTRA_COLOURS`
`GET_VEHICLE_INTERIOR_COLOUR`
`GET_VEHICLE_DASHBOARD_COLOUR`
`GET_VEHICLE_CUSTOM_PRIMARY_COLOUR`
`GET_VEHICLE_CUSTOM_SECONDARY_COLOUR`
`GET_VEHICLE_LIVERY`
`GET_VEHICLE_ROOF_LIVERY`
`GET_VEHICLE_DIRT_LEVEL`
`GET_VEHICLE_WHEEL_TYPE`
`GET_VEHICLE_WINDOW_TINT`
`GET_VEHICLE_TYRE_SMOKE_COLOR`
`GET_VEHICLE_NUMBER_PLATE_TEXT`
`GET_VEHICLE_NUMBER_PLATE_TEXT_INDEX`
=> onesync/sync: complete CVehicleAppearanceDataNode

.travis.yml, code/Rockerfile
Rocker changes: https://github.com/hellslicer/rocker/compare/1.3.3...1.3.4
Labels:
```
docker inspect --format='{{json .Config.Labels}}' citizenfx/server:dev
{"org.label-schema.name":"fxserver","org.label-schema.vcs-ref":"master","org.label-schema.vendor":"citizenfx","org.label-schema.version":"v1.0.0.1624"}
```
Environment variables:
```
$ docker inspect --format='{{json .Config.Env}}' citizenfx/server:dev
["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","CI_BRANCH=master","CI_BUILD_NUMBER=v1.0.0.1624","LD_LIBRARY_PATH=/usr/lib/v8/:/lib:/usr/lib/"]
```
=> build/linux: properly set build args and add labels to docker image

data/shared/citizen/scripting/v8/index.d.ts
- resultAsLong
- resultAsObject
- clearTick
- source
=> index.d.ts: add missing declarations

code/components/extra-natives-rdr3/src/TextNatives.cpp
Adds Text Justification and Text Wrap native to draw text right justified / to the right of the screen
=> Added SET_TEXT_JUSTIFICATION and SET_TEXT_WRAP  native

code/components/extra-natives-rdr3/src/GraphicsNatives.cpp
This PR is restoring some drawing natives that was unfairly removed from RDR3.
=> Implement DRAW_LINE and DRAW_POLY for RDR3

code/components/nui-core/include/CefOverlay.h, code/components/nui-core/src/CefInput.cpp, code/components/nui-resources/src/ResourceUIScripting.cpp
https://forum.fivem.net/t/nui-mouse-interactions/287288
This allow "interacting" with both the NUI frame and the game.
=> nui: implement `SET_NUI_FOCUS_KEEP_INPUT`

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
Added following vehicle extra natives:
```
float GET_VEHICLE_WHEEL_SIZE(int vehicle);
float GET_VEHICLE_WHEEL_WIDTH(int vehicle);
bool SET_VEHICLE_WHEEL_SIZE(int vehicle, float size);
bool SET_VEHICLE_WHEEL_WIDTH(int vehicle, float width);
```
=> Added GETTER and SETTER for changing visual size and width of vehicle wheels

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
added
```c
float GetVehicleWheelBrakePressure(Vehicle vehicle, int wheelIndex);
float GetVehicleWheelSteeringAngle(Vehicle vehicle, int wheelIndex);
float GetVehicleDrawnWheelAngleMult(Vehicle vehicle);
```
based on https://github.com/E66666666/GTAVGlowingBrakes
=> extra-natives-five: Add wheel brake pressure and steering angle natives

code/components/extra-natives-five/src/InteriorExtraNatives.cpp
=> Fix interior room extents natives

code/components/extra-natives-five/src/PlayerNatives.cpp
https://github.com/citizenfx/natives/pull/255
=> Extra getters for some player modifiers

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
https://forum.cfx.re/t/request-native-to-get-vehicle-speed-modifier/1046397
https://github.com/citizenfx/natives/pull/262
=> Implement more vehicle modifier getters

code/components/extra-natives-five/src/WeaponExtraNatives.cpp
https://forum.cfx.re/t/request-a-native-to-get-ped-weapon-damage-multiplier/1014699?u=disquse
https://github.com/citizenfx/natives/pull/261
=> Implement weapon damage modifier getter

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
1) Patternified almost all offsets.
2) Removed unused offsets and native registrations.
3) General code improvements.
=> Refactor vehicle-extra-natives

code/client/shared/atPool.h, code/components/extra-natives-rdr3/include/NativeWrappers.h, code/components/extra-natives-rdr3/src/PoolTraversalNatives.cpp, code/components/gta-core-rdr3/include/Pool.h, code/components/gta-core-rdr3/src/PoolManagement.cpp, data/client_rdr/citizen/common/data/gameconfig_pc.xml
After few hours of testing I haven't met any issue.
Also increased `fwScriptGuid` pool from 1450 to 40000.
=> Backport pool management and pool traversal natives for RedM

code/components/devcon/src/DevConServer.cpp
to facilitate the usage of vconsole
=> devcon: create a specific port for cl2

code/components/gta-net-five/src/MumbleVoice.cpp, code/components/voip-mumble/include/MumbleAudioOutput.h, code/components/voip-mumble/include/MumbleClient.h, code/components/voip-mumble/include/MumbleClientImpl.h, code/components/voip-mumble/src/MumbleAudioOutput.cpp, code/components/voip-mumble/src/MumbleClient.cpp
https://github.com/citizenfx/natives/pull/278
=> mumble/client: add more getter natives

code/components/extra-natives-rdr3/src/GraphicsNatives.cpp
Restores `SET_DRAW_ORIGIN` and `CLEAR_DRAW_ORIGIN` from five.
https://gfycat.com/incredibledistinctdamselfly
=> Draw origin natives for RedM

ext/cfx-ui/src/app/servers/connecting-popup.component.html, ext/cfx-ui/src/app/servers/connecting-popup.component.ts
=> cfx-ui: implement a close shortcut for lazy people

code/components/citizen-server-impl/src/state/ServerGameState.cpp
Works fine.
However, when damageType is 3 I am not sure if it is a mistake but hitGlobalId is zero as f80_1 is false.
=> onesync/events: add CWeaponDamageEvent

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
useful for server-side anticheat
=> onesync: add is_ped_a_player

data/shared/citizen/scripting/v8/console.js
=> fix console.timeEnd() and console.count()

ext/webadmin/server/Controllers/ConsoleController.cs, ext/webadmin/server/Views/Console/Log.cshtml
Cleaner PR than previous, and without the fuckery: https://github.com/citizenfx/fivem/pull/471
=> webadmin: added ability to execute console commands

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp, ext/native-decls/GetAllPeds.md
Used GET_ALL_VEHICLES and adapted it for Peds.
=> server: Add GetAllPeds 

code/components/citizen-server-impl/src/state/ServerGameState.cpp
=> onesync/events: add giveWeaponEvent

data/client/citizen/common/data/gameconfig.xml
This was tested by ~5 people these last days
=> gamconfig: fix VehicleStreamRequest pool crash with onesync-plus

code/components/citizen-server-impl/include/state/ServerGameState.h, code/components/citizen-server-impl/include/state/SyncTrees_Five.h, code/components/citizen-server-impl/src/PlayerScriptFunctions.cpp, ext/native-decls/GetPlayerTimeInPursuit.md, ext/native-decls/GetPlayerWantedLevel.md, ext/native-decls/IsPlayerEvadingWantedLevel.md
Just added some more getters for wanted level / cop related stuff. Works to the best of my knowledge.
=> OneSync: Added more getters with cop/wanted level stuff

code/components/citizen-server-impl/src/InitConnectMethod.cpp
Hi,
I've been looking since the community update #2 into the reverse proxy support. Trying to uncover how to implement it myself, I think, and I'm sorry if I made a mistake, by looking into the source code, that everything is there except a way to pass the endpoints which we want to be randomly picked.
Now I am not that proficient in C++, and there isn't a quick way of testing the changes, but I hope this works.
Have a great day!
=> reverse proxy multi endpoint support

ext/native-decls/GetEntityPopulationType.md
Shamelessly stolen from https://github.com/citizenfx/natives/pull/282
=> Document GetEntityPopulationType native

ext/ui-build/data/root.html
https://forum.cfx.re/t/nui-iframe-management-tabbing-between-frames/1491744/12
=> fix(ui-build): stop focus jumping between iframes on tab presses

ext/native-decls/SetEntityDistanceCullingRadius.md
=> fix(native-decls): fix typo in SetEntityDistanceCullingRadius

code/components/extra-natives-five/src/PlayerNatives.cpp, ext/native-decls/GetPlayerInvincible2.md
Tested, works fine
The offset is the same for both 1604 and 2060
=> feat: add GET_PLAYER_INVINCIBLE_2

data/shared/citizen/scripting/v8/main.js
Based on lua:
```javascript
// server
const serverId = GetPlayers()[0];
const ped = GetPlayerPed(serverId);
const ply = Player(serverId);
const veh = Entity(GetVehiclePedIsIn(ped));
ply.state.test = { ok : 'yup'}
veh.state.test = { ok : 'yes' }
GlobalState.mode = 'open'
```
```javascript
// Client
const serverId = GetPlayerServerId(PlayerId());
const ped = PlayerPedId();
const ply = Player(serverId);
const veh = Entity(GetVehiclePedIsIn(ped));
console.log(ply.state.test); // should print { "ok": "yup" }
console.log(veh.state.test); // should print { "ok": "yes" }
console.log(GlobalState.mode); // should print "open"
ply.state.set('test', { ok: 'set from client' }, true)
veh.state.set('test', { ok: 'set from client' }, true)
```
=> feat(statebags) "State bag" support for JS

data/shared/citizen/scripting/v8/main.js
Forgot to push this, This should fix a silent TypeError.
=> fix(statebag): fixed a silent error in the proxy setter

code/components/citizen-server-impl/src/InitConnectMethod.cpp
Before: sv_endpoints is read (and re-set) each call at getEndpoints.
Running myself a GRE tunnel for fxserver - want to provide proper endpoint(s) to clients connecting.
=> fix(server): persistent sv_endpoints convar

code/client/clrcore/External/Vehicle.cs, code/components/extra-natives-five/src/VehicleExtraNatives.cpp, ext/native-decls/GetVehicleWheelBrakePressure.md, ext/native-decls/GetVehicleWheelFlags.md, ext/native-decls/GetVehicleWheelIsPowered.md, ext/native-decls/GetVehicleWheelPower.md, ext/native-decls/GetVehicleWheelRotationSpeed.md, ext/native-decls/GetVehicleWheelSuspensionCompression.md, ext/native-decls/GetVehicleWheelTractionVectorLength.md, ext/native-decls/SetVehicleSuspensionHeight.md, ext/native-decls/SetVehicleWheelBrakePressure.md, ext/native-decls/SetVehicleWheelFlags.md, ext/native-decls/SetVehicleWheelIsPowered.md, ext/native-decls/SetVehicleWheelPower.md, ext/native-decls/SetVehicleWheelRotationSpeed.md, ext/native-decls/SetVehicleWheelTractionVectorLength.md
also fixes some existing natives
Thanks to [ikt](https://github.com/E66666666/GTAVManualTransmission/blob/master/Gears/Memory/VehicleExtensions.cpp) for the offsets
=> feat(extra/natives): Add many vehicle natives

data/shared/citizen/scripting/lua/scheduler.lua
Hopefully a fix for https://forum.cfx.re/t/possible-bug-with-latest-server-versions-tested-with-3382-3394/2020351/4 ?
=>  fix(scripting/lua): unconditionally set curTime in CreateThreadNow

code/components/gta-net-five/src/MumbleVoice.cpp
when using MumbleSetServerAddress
=> Fix: Don't try to connect if should not connect 

code/components/citizen-server-impl/include/state/ServerGameState.h, code/components/citizen-server-impl/include/state/SyncTrees_Five.h, code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp, ext/native-decls/GetPlayerFakeWantedLevel.md, ext/native-decls/GetPlayerWantedCentrePosition.md
- `GET_PLAYER_WANTED_CENTRE_POSITION` (returns the last position where the player was seen by police)
- `GET_FAKE_WANTED_LEVEL`
=> OneSync: Added getters related to cops/wanted level

code/components/citizen-server-impl/src/state/ServerGameState.cpp
=> feat(onesync): add ptFxEvent + doc

code/components/citizen-server-impl/include/state/ServerGameState.h, code/components/citizen-server-impl/include/state/SyncTrees_Five.h, code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp, ext/native-decls/GetPedSourceOfDamage.md, ext/native-decls/GetPedSourceOfDeath.md
Even if I didn't notice anything wrong during my testing, note I'm not very comfortable with c++
=> feat(onesync): add GET_PED_SOURCE_OF_DEATH/DAMAGE natives

code/components/gta-net-five/src/MumbleVoice.cpp
Should fix double server id in getAudioContextByServerId with MumbleVoice
=> Double ID server bug fix

code/components/gta-net-five/src/MumbleVoice.cpp
Added a `reconnecting` flag to the connection event as well as implement a disconnection event when not trying to reconnect.
=> Extend mumble connection & disconnection events

data/shared/citizen/scripting/v8/index.d.ts
this can take a number or string
=> fix(scripting/v8): fix getPlayerIdentifiers type declaration

code/components/gta-core-five/src/CrashFixes.cpp
If a weapon is removed from the middle of the CWeaponInfoBlob array, the array will shift to fill the empty space. However, the game will not delete the end item after the shift, leading to two identical entries (https://i.imgur.com/EleUK3O.png). This can lead to a crash further down the line
Reproduction steps (two addon weapon resources):
start WeaponA
start WeaponB
stop WeaponA (shift happens here)
stop WeaponB
start WeaponA
start WeaponB (crash)
=> fix(game/five): identical entry in CWeaponInfoBlob leading to crash

code/components/rage-formats-x/include/convert/gtaDrawable_five_rdr3.h
Just adds more shaders for conversion to rdr3. CP did this but asked me to PR it for him since he couldn't do it for whatever reason, if anything is wrong blame him :P
=> Added more shaders to convert to for rdr3

code/client/launcher/GameCache.cpp
Gives a bit more context about what files specifically are corrupted/missing in the game cache.
=> More verbose "game cache corrupted" error messages

code/components/extra-natives-five/src/VehicleExtraNatives.cpp, ext/native-decls/GetTrainDoorCount.md, ext/native-decls/GetTrainDoorOpenRatio.md, ext/native-decls/SetTrainDoorOpenRatio.md, ext/native-decls/SetTrainsForceDoorsOpen.md
Adds:
SET_TRAINS_FORCE_DOORS_OPEN
GET_TRAIN_DOOR_OPEN_RATIO
SET_TRAIN_DOOR_OPEN_RATIO
GET_TRAIN_DOOR_COUNT
=> feat(natives/five): add door controls for trains

code/components/extra-natives-rdr3/src/HudNatives.cpp, ext/native-decls/SetMinimapType.md
Not too comfortable with cpp, hopefully this is fine.
=> feat(extra-natives-rdr3): SET_MINIMAP_TYPE for both 1311.20 and 1355.

ext/cfx-ui/src/app/home/home.component.html, ext/cfx-ui/src/app/home/home.component.scss, ext/cfx-ui/src/app/home/home.component.ts
- Makes the indicator larger
- Changes it from being a plain circle to having an additional 'element'
- Hover tooltip is now the latest status 'message' from status.cfx.re, i.e. 'All Systems Operational'
Tweaked UI:
=> tweak(cfxui): make status indicator more clear, re-format code

code/components/extra-natives-five/include/ropeManager.h, code/components/extra-natives-five/src/RopeNatives.cpp, ext/native-decls/GetAllRopes.md, ext/native-decls/GetRopeFlags.md, ext/native-decls/GetRopeLengthChangeRate.md, ext/native-decls/GetRopeTimeMultiplier.md, ext/native-decls/GetRopeUpdateOrder.md, ext/native-decls/SetRopeLengthChangeRate.md
Adds GET_ALL_ROPES, with four getters and a setter for ropes. Class structures remain the same between 1604 and 2189
=> feat(natives/five): rope getter and setter natives

code/components/gta-net-five/src/CloneExperiments.cpp
Should fix fire sync between players.
=> Fire applicability patch for RDR3

code/components/gta-mission-cleanup-rdr3/include/ScriptHandlerMgr.h, code/components/gta-mission-cleanup-rdr3/src/ScriptHandlerMgr.cpp
See https://github.com/citizenfx/fivem/commit/c1ef032f404644dc14fcd0a049a6a31174fe05f3
=> Set CTheScripts::ms_bUpdatingScriptThreads for non-tick execution in RDR3

code/components/citizen-devtools/src/ResourceTimeWarnings.cpp
An attempted implementation for #787 in the existing framework used for time warnings.
=> feat(game/five): win32k usercrit slowness warnings

code/components/glue/src/ConnectToNative.cpp, code/components/net/include/NetLibrary.h, code/components/net/src/NetLibrary.cpp, ext/cfx-ui/src/app/game.service.ts
This is a series of two changes for #794, as well as potentially fixing some other UI history-related issues by means of coincidence in the second commit.
=> Jump list icon fixes

code/components/glue/src/ConnectToNative.cpp
=> feat(glue): add build number to jump list shortcuts

code/components/rage-device-five/src/HookInitialMount.cpp
=> fix(device/five): newline for "can't open packfile" error

ext/cfx-ui/src/app/servers/workers/servers.worker.ts
=> fix(ext/cfx-ui): don't show pinned servers when doing a filtered search

code/components/conhost-v2/src/ConsoleHostImpl.cpp, code/components/conhost-v2/src/backends/imgui_impl_dx11.cpp
Some events of this kind showed up in crash reporting, also a forum post asking for this: https://forum.cfx.re/t/conhost-v2-dll-3b92c-error/4500824.
=> dear ImGui swapchain creation failures

code/components/glue/src/ConnectToNative.cpp, ext/cfx-ui/src/app/game.service.ts
=> fix(ui): continue connection after info blob if not in ui

code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp, ext/native-decls/GetVehicleType.md
=> feat(gamestate/server): GET_VEHICLE_TYPE native

ext/cfx-ui/src/app/servers/components/list/servers-list.component.ts, ext/cfx-ui/src/app/servers/server-utils.ts, ext/cfx-ui/src/app/servers/workers/servers.worker.ts, ext/cfx-ui/tsconfig.worker.json
=> Server list cleanup stuff

code/components/lovely-script/src/Lovely.cpp
=> fix(script/five): toggle dispatch back on if it was turned off by population

code/client/launcher/GameCache.cpp
=> fix(client/launcher): escape game cache file:/// URLs

code/components/gta-net-five/src/CloneManager.cpp
Fixes repro from https://forum.cfx.re/t/4549017.
=> tweak(net/five): allow freezing net-cloned helis

ext/cfx-ui/src/app/servers/server-utils.ts
Fixes #880, though I hope people will stop trying to be weird like this...
=> fix(ext/cfx-ui): another pass at server name/description cleanups

code/components/extra-natives-five/src/GamePrimitives_Outlines.cpp
Fixes #874 for now, minus the tree portion: this is a later concern.
=> fix(extra-natives/five): render cutout object outlines correctly

code/components/nui-core/src/NUIInitialize.cpp
Usually correlated with OOM or GPU errors, but we should rather crash downstream on this than here.
=> tweak(nui/core): error handling for Texture2DWrap

code/components/citizen-scripting-lua/src/LuaScriptNatives.cpp, code/components/citizen-server-impl/include/GameServer.h, code/components/citizen-server-impl/src/InfoHttpHandler.cpp, code/components/citizen-server-main/src/ServerInstance.cpp, data/shared/citizen/scripting/lua/natives_loader.lua
A few fixes that came up during constraints work and aren't big enough to make into separate PRs.
=> Miscellaneous game fixes

code/components/discord/src/DiscordPresence.cpp, code/components/lovely-script/component.json, code/components/lovely-script/src/Lovely.cpp, data/client_rdr/components.json
Require to set discord app id and app asset
=> Redm Discord Presence

code/components/citizen-server-main/src/ServerInstance.cpp
=> tweak(server/main): support +command for early-startup convars

code/tools/build/run_postbuild.ps1
=> Fix public source server builds failing on missing adhesive

vendor/citizen_enet/src/protocol.cpp
=> fix(enet): work around 256-packet limit

code/components/citizen-devtools/src/ResourceTimeWarnings.cpp
This is to reduce prevalence for prod.
=> tweak(game/five): increase 'stopped responding' threshold (#916)

code/client/citicore/PatternCache.cpp, code/client/citigame/Launcher.cpp, code/client/launcher/CitizenGame.cpp, code/client/launcher/DummyVariables.cpp, code/client/launcher/ExecutableLoader.cpp, code/client/launcher/Main.cpp, code/client/launcher/MiniDump.cpp, code/client/launcher/StdInc.h, code/client/launcher/UpdaterUI.cpp, code/components/citizen-resources-gta/src/ResourceMissionCleanup.cpp, code/components/citizen-resources-gta/src/ResourcesTest.cpp, code/components/citizen-scripting-lua/include/LuaScriptRuntime.h, code/components/citizen-server-impl/include/state/StateGuard.h, code/components/discord/src/DiscordPresence.cpp, code/components/gta-streaming-ny/src/LoadStreamingFileNY.cpp, code/components/lovely-script/src/Lovely.cpp, code/components/nui-core/src/NUIInitialize.cpp, code/components/nui-core/src/NUIRenderHandler.cpp, code/components/rage-graphics-ny/src/DrawCommands.cpp
This changeset seems to make NY functional again. It also adds some basic support for `data_file`.
=> NY fixes and data_file support

code/client/shared/EventCore.h
1. Removes a bunch of old-C++ dependencies.
2. Adds operator bool, const operator() and Disconnect methods.
The second part is required for a future changeset adding state bag events.
=> tweak(shared): modernize fwEvent

code/components/citizen-server-gui/src/PlayerList.cpp
Initially reported in https://forum.cfx.re/t/4739632.
=> fix(server/gui): client reference cycle in OnDrop

code/components/gta-net-five/src/NetInteriorLocationHacks.cpp
=> tweak(net/five): check for -1 mapIndex in CInteriorProxy code

code/components/rage-graphics-five/src/RenderHooks.cpp
=> fix(graphics/five): run rage::grcDevice::BeginFrame when minimized

code/client/citicore/FileMapping.Win32.cpp
ReShade 3.0.4 still would load and crash some small subset of users.
=> fix(core): block outdated crashing dxgi.dll correctly

code/components/glue/src/ConnectToNative.cpp, ext/cfx-ui/src/app/game.service.ts
=> feat(glue): add taskbar icon overlay with server icon

code/components/citizen-scripting-mono/src/MonoComponentHost.cpp
Amazingly, the Mono GC does get a lot faster like this - less pauses during normal vMenu usage even with resmon opened and tracking memory.
=> tweak(scripting/mono): tune mono GC, faster memory usage tracking + toggle-off

code/client/shared/MsgpackJson.h
See https://forum.cfx.re/t/4750800
=> fix(shared): msgpack->json conversion int map bad-cast

code/components/citizen-server-impl/src/state/ServerGameState.cpp, code/shared/state/RlMessageBuffer.h
These two were found on @gottfriedleibniz's branch set and should be safe enough to cherry-pick into mainline.
=> Event parsing fixes

code/client/citicore/console/Console.Base.cpp, code/client/citicore/console/Console.Base.h, code/client/shared/Utils.cpp, code/components/glue/src/ConsoleBinding.cpp
=> console printf suppression for glue

code/components/nui-core/src/NUIApp.cpp, ext/cfx-ui/src/app/home/home-tweet.component.html, ext/cfx-ui/src/app/home/home-tweet.component.scss, ext/cfx-ui/src/app/home/tweet.service.ts
No support for APub videos yet (until we implement approxy), but Disquse's example tweet embeds correctly with this applied.
=> tweak(ui): video support for twitter feed

code/components/citizen-server-impl/include/state/ServerGameState.h, code/components/citizen-server-impl/src/state/ServerGameState.cpp
=> fix(gamestate/server): limit amount of created entities per type

code/components/gta-streaming-five/src/EnableMPMapData.cpp, code/components/gta-streaming-five/src/LoadStreamingFile.cpp
Should fix a number of issues with story mode breaking due to map stuff. Didn't test reloading as 🤷🏻.
=> fix(game/five): load GROUP_MAP_SP for SP

code/client/citicore/DebugFlags.cpp, code/client/common/Error.cpp, code/client/shared/CrossBuildRuntime.h, code/components/conhost-v2/src/backends/imgui_impl_win32.cpp, code/components/glue/src/ConnectToNative.cpp, code/components/glue/src/CrossBuildSwitch.cpp, code/components/glue/src/GtaNui.cpp, code/components/gta-core-five/src/VidBehavior.cpp, code/components/net/src/NetLibrary.cpp, code/components/nui-core/src/CefDragDropHandler.cpp, code/components/nui-core/src/NUIRenderHandler.cpp, code/components/nui-resources/src/ResourceUIScripting.cpp, code/components/rage-graphics-five/src/RenderHooks.cpp, code/components/rage-input-five/src/InputHook.cpp
Blatantly getting grcWindow was a little wrong.
=> fix(game): correctly handle CL2 window handles

code/components/citizen-server-impl/src/ServerResources.cpp
1. Reduce complaininess of 'Some resources have an outdated resource manifest' prints.
2. Count refreshed resources separately from unchanged ones.
3. Mount `citizen:/` early to fix OAL/lazy-natives.
=> Resource setup fixes

data/shared/citizen/scripting/v8/main.js
Author @bladecoding and @DiscworldZA (Inactive PR: https://github.com/citizenfx/fivem/pull/687)
**This PR should implement __cfx_async_retval into V8 runtime.**
Testing:
https://github.com/citizenfx/fivem/blob/83cb017b2023d333654ea28996b92cc8baa3f32c/data/shared/citizen/scripting/lua/scheduler.lua#L1039
Lua tends to unpack awaited result so therefore I put result as array `cb([v], null)` inside V8.
Would be glad for any help with this.
=> feat(scripting/v8): Add support for __cfx_async_retval

code/components/gta-streaming-five/src/sfFontStuff.cpp
No more of these square circles.
=> Fix square loading circles in Five

code/client/citicore/om/OMClass.h, code/client/shared/Hooking.h, code/components/citizen-resources-core/include/ResourceEventComponent.h, code/components/citizen-resources-core/include/ResourceManager.h, code/components/citizen-server-impl/include/ServerEventComponent.h, code/components/citizen-server-impl/include/decorators/WithOutOfBand.h, code/components/citizen-server-impl/include/decorators/WithPacketHandler.h, code/components/citizen-server-impl/src/GameServer.cpp, code/components/extra-natives-five/src/NuiAudioSink.cpp, code/components/gta-net-five/src/ClientRPC.cpp, code/components/gta-net-five/src/MumbleVoice.cpp, code/components/rage-scripting-five/include/scrEngine.h, code/components/rage-scripting-ny/include/scrEngine.h, code/components/rage-scripting-rdr3/include/scrEngine.h, code/components/scripting-gta/include/ScriptEngine.h
=> tweak(scripting): improve NativeInvoke, remove 'struct pass'

code/client/launcher/Main.cpp
A lot of users ended up with AcLayers.dll (and similar) showing in game crash dumps.
=> tweak(client/launcher): remove app compatibility layers, if any

code/client/launcher/MiniDump.cpp
Ever since the 'FiveM has stopped responding' watchdog logic, people have been asking 'what is citizen-devtools.dll? how to fix?' instead of providing real information.
This can be due to two causes:
1. FatalError dialog boxes show the 'Crash signature' still in the 'Expand details' section.
2. 'Game crashed:' quit messages send the crash hash rather than the first line of the error message.
This changeset fixes the two, by:
1. Removing the 'Crash signature' line if error pickup is used.
2. Sending the actual error message ("Game crashed: Assertion failure: !"_assert command used" (W:\cf\code\fivem-master-pub\code\components\gta-core-five\src\GameInit.cpp:216)") instead of the crash signature ("Game crashed: gta-core-five.dll+111E7F") in a quit message.
=> tweak(client/launcher): reduce use of crash signatures for error pickup

code/components/citizen-scripting-lua/src/LuaScriptNatives.cpp, code/components/gta-streaming-five/src/PatchExtendedBudgeting.cpp, code/components/ros-patches-five/src/LegitimacyNui.cpp, code/components/steam/src/SteamComponent.cpp
These didn't deserve their own PR and should still be included in today's mini-push.
=> Miscellaneous fixes

code/client/clrcore/BaseScript.cs, code/client/clrcore/InternalManager.cs, code/client/clrcore/MonoScriptRuntime.cs, code/client/clrcore/PushRuntime.cs, code/client/clrcore/ScriptContext.cs
From local working tree, some with questionable benefit.
=> Pending C# ScRT tweaks

code/components/citizen-server-impl/src/ServerResources.cpp, ext/native-decls/server/PrintStructuredTrace.md
=> Add structured trace resource metadata

code/components/rage-formats-x/include/convert/gtaDrawable_five_rdr3.h
this should fix _some_ crashes while using @citicon formats:convert
=> defaulting cut outs

code/components/citizen-server-impl/src/TerminalInput.cpp
=> fix(server/impl): ensure stdin is non-blocking before we use it

code/components/glue/src/ConnectToNative.cpp, code/components/net/src/NetLibrary.cpp, ext/cfx-ui/package.json, ext/cfx-ui/src/app/servers/connecting-popup.component.html, ext/cfx-ui/src/app/servers/connecting-popup.component.scss, ext/cfx-ui/src/app/servers/connecting-popup.component.ts, ext/cfx-ui/yarn.lock
Hopefully doesn't break any other error messages. 😅
=> feat(ui): friendly timeout/getinfo error messages

code/components/citizen-server-impl/include/state/ServerGameState.h, code/components/citizen-server-impl/include/state/SyncTrees_Five.h, code/components/citizen-server-impl/include/state/SyncTrees_Header.h, code/components/gta-net-five/src/CloneDebug.cpp
A little memory/allocator performance saving.
Needs testing on a real server.
=> Server game state improvements

code/client/launcher/CrossBuildLaunch.cpp, code/client/launcher/Download.cpp, code/client/launcher/GameCache.cpp, code/client/launcher/GameSelect.cpp, code/client/launcher/Updater.cpp, code/client/launcher/UpdaterUI.NonMain.cpp, code/client/launcher/UpdaterUI.cpp, code/client/launcher/premake5.lua, code/components/citizen-scripting-core/src/ScriptHost.cpp, code/premake5.lua, code/premake5_layout.lua, code/tools/build/components.lua, code/tools/build/privates.lua, code/tools/build/run_prebuild.ps1, ext/cfx-ui/src/app/servers/connecting-popup.component.scss, ext/cfx-ui/src/app/servers/connecting-popup.component.ts
One actual bug fix, a behavior change, and some build system tweaks.
=> Miscellaneous build tweaks and fixes

code/client/clrcore/External/Entity.cs, code/client/shared/SharedFunction.h, code/components/citizen-resources-core/include/StateBagComponent.h, code/components/citizen-resources-core/src/StateBagComponent.cpp, code/components/citizen-resources-gta/src/EntityStateBags.cpp, code/components/citizen-resources-gta/src/GameEventFunctions.cpp, code/components/citizen-scripting-core/src/ResourceScriptFunctions.cpp, code/components/citizen-scripting-v8/src/V8ScriptRuntime.cpp, code/components/citizen-server-impl/src/ClientDeferral.cpp, code/components/citizen-server-impl/src/ResourceHttpHandler.cpp, code/components/gta-streaming-five/include/EntitySystem.h, code/components/gta-streaming-five/src/EntitySystem.cpp, code/components/gta-streaming-five/src/GameEventHooks.cpp, code/components/net-tcp-server/include/UvTcpServer.h, data/shared/citizen/scripting/lua/scheduler.lua, data/shared/citizen/scripting/v8/main.js, ext/native-decls/AddStateBagChangeHandler.md, ext/native-decls/EnsureEntityStateBag.md, ext/native-decls/RemoveStateBagChangeHandler.md
1. State bag change handlers
2. Local (non-network) entity state bags for clients
3. More reliable client damage event
=> Leftover feature merges from the LE branch

code/components/citizen-legacy-net-resources/src/ResourceNetBindings.cpp
Should fix some v8::Isolate deadlocks on resource restart (but for lack of repro, this wasn't tested).
=> fix(resources/client): stop resources on main thread

code/tools/ci/build.ps1, ext/cfx-ui/src/app/app.component.scss, ext/cfx-ui/src/app/home/home-tweet.component.html, ext/cfx-ui/src/app/home/home-tweet.component.scss, ext/cfx-ui/src/app/home/home.component.html, ext/cfx-ui/src/app/home/home.component.scss, ext/cfx-ui/src/app/nav/app-nav.component.scss, ext/cfx-ui/src/app/servers/connecting-popup.component.scss
Mostly fixing an oversight in CEF.
=> UI performance tweaks

code/components/citizen-scripting-v8/src/V8ScriptRuntime.cpp
Since the Node.js 16 upgrade, stdin gets initialized in more cases (like `require('process')`), but this will lead to a race on a Windows console handle read fighting replxx.
Since it's meaningless for Node.js in a ScRT context to be using stdin, we'll overwrite process.stdin with an ended no-op stream.
Fixes https://forum.cfx.re/t/4766509.
=> fix(scripting/v8node): no-op stream for stdin

code/components/extra-natives-five/src/PlayerNatives.cpp, ext/native-decls/GetPlayerMaxStamina.md, ext/native-decls/GetPlayerStamina.md, ext/native-decls/SetPlayerMaxStamina.md, ext/native-decls/SetPlayerStamina.md
=> feat(extra-natives-five): add player stamina natives

code/components/gta-net-five/src/MumbleVoice.cpp, code/components/gta-net-rdr3/component.json, code/components/gta-net-rdr3/component.lua, code/components/gta-net-rdr3/src/CoreNetworking.cpp, data/client_rdr/components.json, ext/native-decls/MumbleGetTalkerProximity.md, ext/native-decls/MumbleIsActive.md, ext/native-decls/MumbleIsPlayerTalking.md, ext/native-decls/MumbleSetActive.md, ext/native-decls/MumbleSetTalkerProximity.md
This PR adds a compatibility layer for Mumble support in RedM. Without native audio for now.
Thanks to @Ktos93 and @nikez for initial researches.
=> Mumble support for RedM

ext/native-decls/GetLastPedInVehicleSeat.md, ext/native-decls/GetPedInVehicleSeat.md
The previous description in the seat indexes part was incorrect.
=> tweak(ext/natives): link seatIndex to eSeatPosition

code/components/gta-net-five/src/MumbleVoice.cpp
This PR should resolve issues causing mumble disconnections after changing settings.
=> Resolve preferences conflict for Mumble on RedM

code/components/citizen-server-impl/include/state/ServerGameState.h, code/components/citizen-server-impl/include/state/SyncTrees_Five.h, code/components/citizen-server-impl/include/state/SyncTrees_RDR3.h, code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp, ext/native-decls/GetHeliMainRotorHealth.md, ext/native-decls/GetHeliTailRotorHealth.md
This PR adds 2 natives :
- `GET_HELI_MAIN_ROTOR_HEALTH`
- `GET_HELI_TAIL_ROTOR_HEALTH`
=> feat(onesync): heli health research

ext/sdk/resources/sdk-root/shell/src/fxdk/project/browser/project.commands.ts, ext/sdk/resources/sdk-root/shell/src/fxdk/project/browser/project.contribution.tsx, ext/sdk/resources/sdk-root/shell/src/fxdk/project/browser/state/projectInstance.ts, ext/sdk/resources/sdk-root/shell/src/fxdk/project/contrib/explorer/explorer.fileSystemItem.tsx, ext/sdk/resources/sdk-root/shell/src/fxdk/project/contrib/explorer/explorer.itemMenu.ts, ext/sdk/resources/sdk-root/shell/src/fxdk/ui/icons.tsx, ext/sdk/resources/sdk-root/shell/src/personalities/fxcode/FXCodeState.ts
Adds "Find in Folder" context menu option per https://github.com/citizenfx/fivem/issues/1186 requirements
Requires https://github.com/citizenfx/fxcode/pull/1
=> feat(sdk): Add "Find in Folder" Context Menu #1186

ext/sdk/resources/sdk-root/shell/src/fxdk/project/browser/project.commands.ts, ext/sdk/resources/sdk-root/shell/src/fxdk/project/browser/project.contribution.tsx, ext/sdk/resources/sdk-root/shell/src/fxdk/project/browser/state/projectInstance.ts, ext/sdk/resources/sdk-root/shell/src/fxdk/project/contrib/explorer/explorer.fileSystemItem.tsx, ext/sdk/resources/sdk-root/shell/src/personalities/fxcode/FXCodeState.ts
Adds "Open in Integrated Terminal" context menu option per #1185 requirements
Requires citizenfx/fxcode#2
=> feat(sdk): Add "Open In Terminal" context menu #1185

code/components/gta-net-five/src/CloneExperiments.cpp
The game removes the "player cached data" array's entry in `CNetworkObjectMgr::PlayerHasLeft`, but with OneSync this function are never getting called, so we end up with stale data and minor memory leak I believe (12 bytes per each physical player creation). There's some code where the game actually can use stale data, which is not safe.
=> Clear player cached data on client drop in RDR3

code/components/gta-net-five/src/CloneExperiments.cpp
Report: https://forum.cfx.re/t/spawned-human-peds-going-aggressive-crash-client-with-onesync-lemon-salami-california/4788577
=> Resolve combat task crash in RDR3

code/components/gta-net-five/src/CloneExperiments.cpp
Rework `SerializePlayerIndex` methods of `CSyncDataWriter` and `CSyncDataReader` classes for OneSync realities. This may resolve multiple in-game issues, testing case was wrong synchronization of `CTaskCombat` player targets.
=> Rework sync data player index serialization for RedM

code/components/citizen-server-impl/src/state/ServerGameState.cpp
Unsure of what v1 is, it gets set to 3 when its a ped is on fire, and 5 when a vehicle is (though it doesn't seem to be very consistent)
=> feat(server/state): update fireEvent variables

data/client_rdr/citizen/common/data/gameconfig.xml
Hi,
With modding we are able to go out of actual size.
Tested with few peoples no side effect with this new value.
:)
=> tweak(data/rdr3): Increase PortalInst pool size

code/components/extra-natives-five/src/NativeFixes.cpp
=> Fix vehicle window index validation for native fixes

code/components/gta-net-five/src/CloneExperiments.cpp
Should resolve weird dummy object behavior and some crashes potentially. 
First patch was tested in with 2 clients in real gameplay. Second patch was tested in a *simulated* situation.
=> Port dummy object patches for RedM

code/components/gta-net-five/src/CloneExperiments.cpp
Original report: https://forum.cfx.re/t/low-blossom-fifteen/4817583
Repro: 1-st player should enter stealth mode (i.e. ducking), 2-nd player should quickly stream-in and stream-out from 1-st player scope. The game will crash at some point, more players - bigger chance. I left more details in the code.
=> Fix player visibility checks related crash in RedM

code/components/extra-natives-rdr3/src/GraphicsNatives.cpp
Should resolve recent regression introduced in #1528.
=> Update graphics extra natives pattern for 1436.31

code/components/extra-natives-rdr3/src/DoorExtraNatives.cpp
=> feat(extra-natives/rdr3): Door system

code/client/clrcore/InternalManager.cs
- This will produce the same stack-trace as servers do.
=> fix(scripting/mono): Enable stack trace info for async/tasks on client

ext/native-decls/GetGamePool.md
Saw a user on Discord asking how to use `GetGamePool`, so provide a basic usage example.
=> feat(native-decls): Update GetGamePool.md (add usage example)

ext/native-decls/GetEntityType.md
Add a description for it including an explanation for its return value.
=> feat(native-decls): Update GetEntityType.md

code/components/extra-natives-five/src/VehicleExtraNatives.cpp
See https://github.com/citizenfx/fivem/commit/9d4c37aa5170710b22a75b2ce93ee6ac20710d6f#commitcomment-81980211
=> Fix highbeams xenon color overriding for FiveM

code/client/launcher/CrossBuildLaunch.cpp, code/client/launcher/ExecutableLoader.Snapshot.cpp, code/client/launcher/GameCache.cpp, code/client/launcher/StdInc.h, code/client/launcher/premake5.lua, code/client/shared/CrossBuildRuntime.h, code/components/gta-net-five/src/CloneManager.cpp, code/components/gta-net-five/src/CloneObjectManager.cpp, code/components/gta-net-rdr3/include/netObject.h, code/components/gta-net-rdr3/src/CoreNetworking.cpp, code/components/gta-net-rdr3/src/netObject.cpp, code/components/gta-streaming-rdr3/src/Streaming.cpp, code/components/net/src/NetLibrary.cpp, code/components/rage-graphics-rdr3/src/GfxSpec.cpp, code/components/ros-patches-five/src/ros/Entitlements.cpp, data/client_rdr/citizen/common/data/gameconfig.xml, ext/native-decls/GetGameBuildNumber.md
=> Add crossbuild support of b1491 for RedM

code/components/extra-natives-five/src/RuntimeAssetNatives.cpp, code/components/extra-natives-five/src/TextureReplacementNatives.cpp
This is not an ideal fix (mainly the hacked-together bimap use alongside the temporary next-frame action queue), but it fixes the reported issue and could be expanded to support using ADD_REPLACE_TEXTURE on *any* TXD, including ones that aren't loaded.
Fixes #1684.
=> Support 'deferred-creation' DUI textures for ADD_REPLACE_TEXTURE

code/components/gta-net-five/src/CloneExperiments.cpp, code/components/gta-net-five/src/CloneManager.cpp
* Fixes state bags not being replicated to the server
An oversight while fixing 28dcdc0640889f3a834fd7b1fb2b0d457ed99523
=> fix(net/five): update targets for client state bags as well

code/components/gta-core-five/src/PatchVehicleHoodCamera.cpp
A proper fix for the bug described in #1663
=> Fix first person vehicle hood camera drive by shooting sync

code/components/citizen-scripting-mono/include/MonoComponentHostShared.h, code/components/citizen-scripting-mono/src/MonoComponentHost.cpp, code/components/citizen-scripting-mono/src/MonoComponentHostShared.cpp
* Separates shared code for v1 and v2 with some optimizations
* Clean up to make code more readable and faster.
Prerequisite to mono_rt2
=> tweak(scripting-mono): preparing mono v1 runtime for v2

code/components/citizen-scripting-mono/src/MonoComponentHostShared.cpp
* Add profiler GC events (again, somehow went poof).
* Remove `/v2/` directory (for now) from `MONO_PATH` to remove warning "... in MONO_PATH doesn't exist or has wrong permissions".
* Set config file value for root domain.
=> fix(scripting-mono): remove warning and re-add missing code

code/components/steam/src/SteamLoader.cpp
As of Steam client update (17 Nov) users were no longer able to start FiveM/RedM and use their Xbox controller without using a Steam shortcut or Big Picture Mode. This will restore it.
* Unhooking Steam XInput hooks.
* Wrapper to easily add additional unhooks in the future.
=> fix(steam): Xbox controller usable outside Steam again

code/client/clrcore/External/Entity.cs
* Remove CAS attribute that was creating a SecurityManager exception
=> fix(clrcore): fixes broken Entity's properties

code/components/extra-natives-five/src/PedExtraNatives.cpp, ext/native-decls/GetPedMovementClipset.md
Tested on all FiveM versions.
Tested by using the native on my own ped and by targeting others (-cl2 and cloned peds).
=> feat(extra-natives-five): GetPedMovementClipset

code/components/gta-net-five/src/CloneExperiments.cpp
The previous attempt to fix water population (boats massive spawn/duping/mess/etc) issues was very unreliable, honestly it wasn't meant to work in any case except the one very specific (which was used as a test scenario by me, lol). This attempt should be way better as now we have proper position for a desired entity. Also the game will wait for 1 second before trying again if spawn was rejected by the hooked function. Was only tested with 2 players, hopefully will work as good with more players 🤞
=> Rework world grid handling for boat population for RedM

code/components/gta-core-five/src/PoolManagement.cpp, code/components/gta-core-rdr3/src/PoolManagement.cpp
this PR tries to add fwAssetStore pools(ScriptStore, MetaDataStore, AnimStore, TextStore, TxdStore etc) to the pool management this is untested in games.
=> (gta-core): add fwAssetStores pools to pool Management

code/components/gta-net-five/src/CloneExperiments.cpp
The task scenario getter crash happens when the game doesn't expect a function that meant to return `CScenarioInfo` from `rage::aiTask` for an unknown reason returns nullptr. It's almost impossible to reproduce on a local server, so we're trying to workaround this crash and output some maybe-useful notes when the potential crashing-case happens. For now we're only patching specific places where the crash appear to happen kinda often. Unfortunately, we can't be sure about no potential regressions introduced by this patch.
Sentry identifiers: `REDM-M7B` and `REDM-9KY` for b1491 and b1436.
https://forum.cfx.re/t/september-kitten-robert/4817577
https://forum.cfx.re/t/crash-rdr2-b136-exe-sub-141dcd004-0x9ce-100-player-in-town/4946257
=> Workaround for task scenario crash for RedM

code/components/gta-net-five/src/CloneExperiments.cpp
A free DLC for [`c9dcd16`](https://github.com/citizenfx/fivem/commit/c9dcd1654455fc8c0f53f93d4e579dadfb4b2fac).
A popular case of the task scenario crash that left unpatched.
=> Additional patch for scenario info crash workaround for RedM

ext/native-decls/GetEntityType.md
2, 1, 3 instead of 1, 2, 3 is slightly confusing.
=> tweak(native-decls): order entity types

code/components/extra-natives-five/src/WaterExtraNatives.cpp, ext/native-decls/GetWaveQuadBounds.md, ext/native-decls/GetWaveQuadDirection.md
>:( 33 natives okay, accidents happen
=> fix(extra-natives-five/water): copy paste/spelling errors

code/components/extra-natives-five/src/InterfaceExtraNatives.cpp, ext/native-decls/GetHudComponentAlign.md, ext/native-decls/GetHudComponentName.md, ext/native-decls/GetHudComponentSize.md, ext/native-decls/IsBigmapActive.md, ext/native-decls/IsBigmapFull.md, ext/native-decls/SetHudComponentAlign.md, ext/native-decls/SetHudComponentSize.md
Plus few minor tweaks in `InterfaceExtraNatives.cpp`
```cpp
char* GET_HUD_COMPONENT_NAME(int id);
void GET_HUD_COMPONENT_ALIGN(int id, int* horizontalAlign, int* verticalAlign);
void SET_HUD_COMPONENT_ALIGN(int id, int horizontalAlign, int verticalAlign);
Vector3 GET_HUD_COMPONENT_SIZE(int id);
void SET_HUD_COMPONENT_SIZE(int id, float x, float y);
```
=> Implement additional hud component natives for FiveM

code/client/clrcore-v2/Interop/ExportsManager.cs, code/client/clrcore-v2/Native/CustomNativeWrapper.cs
* Missing fixes for rdr3 build
=> fix(clrcore-v2): build errors for rdr3

code/components/gta-streaming-five/src/LoadStreamingFile.cpp
Resolves a crash when using a RBF/PSO vehicle meta. Changes the entry count to be calculated based off the parsed structure array count, rather than checking for text
=> tweak(streaming/five): dynamic vehicle metadata size calculation

data/client/citizen/common/data/gameconfig.xml
Resolves CScenarioInfo pool related crashes.
=> tweak(game/five): increase CScenarioInfo limit

code/components/gta-streaming-five/src/ScaleformHacks.cpp
Print `DEBUG_LOG` messages from scaleforms onto the console
* Togglable with convar `game_enableScaleformDebugLog`
Tested on: 1604, 2189, 2545, 2699, and 2802.
=> feat(streaming-five): Scaleform debug logging

code/components/gta-net-five/src/CloneExperiments.cpp
See more details here: https://github.com/citizenfx/fivem/commit/c9dcd1654455fc8c0f53f93d4e579dadfb4b2fac
Previous attempt to fix it has proved that this crash only happens with `CTaskUseScenario`. In this attempt we're going to hook the whole function and return a fallback value if an invalid task has been returned by the original function. Yet again, experimental solution.
=> Rework CTaskUseScenario crash workaround for RedM

code/client/clrcore-v2/Interop/MsgPackDeserializer.cs, code/client/clrcore-v2/Native/MemoryAccess.cs, code/client/clrcore/External/Entity.cs, code/client/clrcore/External/Game.cs, code/components/citizen-scripting-mono-v2/include/MonoDomainScope.h, code/components/citizen-scripting-mono-v2/src/MonoComponentHost.cpp, code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp
* Fix recursive domain switching
* MsgPack; deserialize Vector2/3/4 and Quaternion as little endian
* Move joaat encryption over to its user `Game.GenerateHash(string)`, fixing accessibility exceptions
resolves thorium-cfx/mono_v2_get_started#5, resolves thorium-cfx/mono_v2_get_started#4, resolves thorium-cfx/mono_v2_get_started#3
=> fix(clrcore-v2): several bug fixes

code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp
mono v2 runtime's `Create` function never went back to the root domain, crashing other code that relied on this rule: "always go back to the root domain for v1"
* back to root on `Create`
* revert unload code's domain setting.
* fixes SIGSEGV crash mentioned in f96fbe7adda55786fb83ed9f3742999a40dd3aad
resolves thorium-cfx/mono_v2_get_started#6
=> fix(scripting-mono-v2): unload regression

ext/native-decls/SetHttpHandler.md
Tried using the native but had to do some research to find out how it works, so update the docs for it.
Add a description for the function and its parameters.
Add a basic usage example.
=> feat(native-decls): update SET_HTTP_HANDLER

code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp
* Fixes logic error in date checking
* Remove dependency on local time and use epoch instead
fixes #2026
=> fix(scripting-mono-v2): use epoch timing check

ext/native-decls/SetHttpHandler.md
I've been informed that my previous PR missed some stuff so I added them.
=> feat(native-decls): add binary and header arrays to SET_HTTP_HANDLER

code/components/extra-natives-five/src/NativeFixes.cpp
Test script: https://pastebin.com/xv4jrcFf
=> fix(extra-natives/five): entity fire id not released

code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp
Bumps the pilot date to 2023-08-31
=> tweak(scripting-mono-v2): bump pilot date

code/client/clrcore-v2/Interop/Types/CString.cs, code/client/clrcore/External/Element.cs, code/client/clrcore/External/Font.cs, code/client/clrcore/External/Scaleform.cs, code/client/clrcore/External/Screen.cs, code/client/clrcore/External/Sprite.cs, code/client/clrcore/External/Text.cs, code/client/clrcore/Math/v2/Color.cs
* Adds v1 CitizenFX.Core.UI.* types in v2 CitizenFX.FiveM.GUI namespace.
* Refactored slow performing parts in GUI.* types for v2.
* CString.Concat(CString[]) added to support Text's caption retrieval.
resolves thorium-cfx/mono_v2_get_started#16
=> feat(clrcore-v2): add .GUI namespace types

code/components/gta-net-five/src/CloneExperiments.cpp
Fixes few crashes that happened in the same text/voice chat related function. Crashes happened because of invalid pointers passed as a first argument. The patched function seems to be unnecessary for OneSync, so we're simply not calling it anymore.
=> Resolve 32-sized text/voice chat related array crashes in FiveM

ext/native-decls/DoesPlayerExist.md
Thanks @MichaelCoding25 for pointing this out 😄
=> fix(native-decls): fix typo in return

code/components/gta-net-five/src/CloneManager.cpp
Hopefully it won't be a problem anymore as now it's "patternified".
=> Fix wrong object "created by" offset in FiveM

code/components/gta-net-five/src/netSyncTree.cpp
Blimps are techincally a NetObjHeli, but their model is not considered to be a heli. 
So the previous fix would force the model to a buzzard
=> fix(gta-net-five): Fix blimp desync

code/components/ros-patches-five/src/AccountID.cpp
This came up during an automated security scan. It's likely of no ill effect, but fixing rather than ignoring.
Launching RDR with an EGS copy was tested and worked fine.
=> tweak(ros/accountid): EGS command-line blob string behavior

code/components/nui-core/src/CefInput.cpp
This adds WM_SYSKEYDOWN and WM_SYSKEYUP to the message handler. Additionally, the message handler is cleaned up a little bit.
Fixes #2160.
=> fix(nui/core): handle Alt keys in NUI

code/components/citizen-level-loader-five/src/LevelLoader.cpp
Since b2699, some parts of the base map would load even if replacing the level meta with a custom one. This is because patchday27 has a changeset ("CCS_PATCHDAY27_NG_STREAMING_MAP") which updates a few map chunks such as dt1, but which lacks a <associatedMap>MO_JIM_L11</associatedMap> tag.
This was reported on https://forum.cfx.re/t/5162859, but likely also in some other places prior given it's a fairly old bug.
=> fix(level-loader/five): no more city chunk if replacing map on b2699+

code/client/clrcore/External/Audio.cs
The current implementation is incorrect and fetches a random sound ID at the end.
=> fix(clrcore): actually use sound ID when playing audio

ext/cfx-ui/src/cfx/apps/mpMenu/parts/LegacyConnectingModal/AdaptiveCardPresenter/AdaptiveCardPresenter.module.scss
This fixes disabled actions on adaptive cards not having proper styling.
Before:
After:
=> fix(ext/cfx-ui): adaptive card disabled button style fix

code/components/ros-patches-five/src/AccountID.cpp
SC SDK 2.2.6.9 moved the sessionKey field down a bit, for the first time in a long time.
This'd break automatic signin from the RGL in an unusual way (sessionKey would be read as a buffer of NULLs, leading to requests failing).
Ideally this'd be paired with an assertion or obtained from a pattern scan somewhere, but for this commit, these offsets have just been factored out in `constexpr`s.
Investigation notes: a blank sessionKey will lead to a misleading 500 error being returned from ROS, with a body encrypted with a key that matches neither a 0x00 sessionKey, nor a security-less key. While trying to see if the body could be decrypted if not using a sessionKey, but finding the response was the same as with the sessionKey, this led to me noticing the sessionKey was base64'd `00` bytes. …
=> fix(ros): sessionKey offset for RGL signin

.github/PULL_REQUEST_TEMPLATE.md
Fix typo "Consice" in PR template
By replacing it with "Concise" ;)
GitHub
N/A
**Platforms:** GitHub Web
=> fix(github): PR template concise typo

code/components/steam/src/ClientEngineMapper.cpp
See c5ae3cf3bf43895bdc299b3906309167677f893c
See c5ae3cf3bf43895bdc299b3906309167677f893c
FiveM/RedM
**Game builds:** All
Fixes #2415
=> fix(steam): support steamclient64.dll 8.75.5.19... for now.

code/components/extra-natives-five/src/NativeFixes.cpp
Using an invalid marker type index will cause an OOB crash. This PR is meant to fix this issue.
By replacing the original native handler with one that includes marker type index checks.
FiveM, Natives
**Game builds:** 1604, 2060, 2189, 2372, 2545, 2612, 2699, 2802, 2944, 3095
Addresses the problem reported in this forum topic:
https://forum.cfx.re/t/drawmarker-causing-crash-when-you-enter-a-string-as-type-instead-of-a-integer/5236598
=> Clamp marker type index in FiveM

code/components/citizen-server-impl/src/SteamIdentityProvider.cpp
=> feat(server): add steam_webApiDomain convar

ext/natives/codegen_out_cs.lua
It should be noted the testing for this was very minimal (only tested with one native having `cs_split`)
Allow for C# code gen to do method overloading on `cs_split` parameters
This should let us update to update the native docs argument types without having to worry about C# compatibility, as long as the arguments are properly split.
An example would be if given this native
```c
void NETWORK_FADE_IN_ENTITY(Entity entity, BOOL bNetwork, cs_split BOOL flash);
```
This will generate
```cs
public static NetworkFadeInEntity(int entity, bool bNetwork)
```
and
```cs
public static NetworkFadeInEntity(int entity, bool bNetwork, bool flash)
```
Adding `cs_split` as a valid doc annotation and splitting the methods when there's a split
FiveM, RedM, ScRT: C#
**Platforms:** …
=> feat(mono): allow for code definitions to be split

code/tools/ci/wsl-build.sh
WSL builds are currently broken due to recent build changes.
- Update WSL build script to use new build stages
- Remove 'svadhesive' from components if custom build
Linux Server building
**Platforms:** WSL2 - Linux
/
=> fix(build/linux): WSL build adjustments

ext/native-decls/GetPlayerIdentifierByType.md
Provide relavent information, regarding identifiers that are returned from this native.
Adds a link to the FiveM Docs listing identifiers that are known.
Server Native Docs
=> tweak(docs/natives/GetPlayerIdentifierByType): Add link to known identifiers

code/components/gta-streaming-five/src/PatchSkeletonCrash.cpp
This PR reworks the solution proposed in #3099, providing a global patch for the affected function by introducing a bounds check for `boneIndex`.
A trampoline is implemented to redirect execution to a bounds check before accessing matrix indices, ensuring they remain within valid bounds and preventing potential out-of-bounds access.
This function is referenced in over 100 locations and is called multiple times per frame. While the patch is necessary, if a noticeable performance impact is observed, we may need to consider moving to callee patching instead of applying a global hook.
FiveM
**Game builds:** 3407 - Pattern is valid for all builds >= 2372 (older ones unchecked)
fixes #2963
fixes #3095 
fixes #3103 
fixes #3120
=> fix(gta-streaming-five): skeleton bone index bounds check

code/components/extra-natives-five/src/TrackNatives.cpp
Fixes the direction check in track switching, an slightly incorrect warning message when attempting to remove train junctions, and correcting velocity on track switch.
Fixes flag check in CTrain::GetDirection, now will properly return the direction, this was missed in the original test cases I had for track switching. 
The trains current speed/velocity is now stored before beginning the track switch and is set back when finishing the switch. There was previous cases where the function used to smooth the transition would set the velocity to a negative speed, launching the train backwards and causing the train to jitter on remote clients.
FiveM
**Game builds:** 3258, 3407
=> tweak(extra-natives/five): track switching improvements

code/components/gta-core-five/src/PedAlternateVariationCache.cpp
Prevents crash when trying to add an alternate variation ped when there is no more space.
As @slashkeyvalue said, this PR should be merged before [this](https://github.com/citizenfx/fivem/pull/3190) to prevent people from crashing due to this problem and when it is already in production, the PR that increases this limit should be merged(#3190).
We check that the m_count which is the current index does not exceed the size of the outArray where the new variation will be inserted.
FiveM
**Game builds:** 3095, 3407
fixes #2760
=> fix(gta-core-five): crash in out bound alternate variation cache

code/components/gta-core-five/src/CrashFixes.cpp
This is still a common abuse vector on older game builds (< 3095) and patching this is quite straightforward. Until the new game build system is not globally enforced this doesn't hurt to be backported.
Injecting the newly added size check (Decorator list-count <= 11) into older game builds. Instruction-flow is a one-to-one copy from newer builds  and was copied from `41 39 0E 41 0F 42 0E` on `3407`.
FiveM
**Game builds:** 2189, 2944
/
=> fix(core-five): backport decorator crash mitigation

code/components/extra-natives-rdr3/src/NativeFixes.cpp
Networked objects without fragment model would not sync its rotation , gtav had the same issue but theres a native to "fix it"
such as `NETWORK_SET_OBJECT_CAN_BLEND_WHEN_FIXED` but not for RedM
The function pointer at index 204 was originally a nullsub (returning 0).
We replace it with our override function to ensure blending always occurs when enabled.
tests were properly made with with objects that were working before and with objects that weren't to ensure that there's no breakage with current scripts.
thanks to @Ktos93 
This change allows to fix net objects rotation to sync with other clients when its updated the rotation, using SET_ENTITY_ROTATION or SET_ENTITY_QUATERNION
RedM
1491
windows
#3252
=> fix(extra-natives-rdr3): fix net object rotation sync

code/client/launcher/GameSelect.cpp
Adds some specific errors/warnings during initial setup to inform users about no Enhanced support for FiveM, as this currently causes very unspecific load errors/crashes which confuses some users.
- Add warnings if a user selects an installation of GTA V Enhanced as their game directory (some users seem to rename the V executable to bypass filter checks in the game select window).
- Try to auto-detect GTA V Enhanced installs if auto-detection for Legacy fails to inform users about the need to have V Legacy installed.
- Clear wrong path entry from the private profile if it points to V Enhanced.
Early warning if auto-detect fails but V Enhanced seems installed:
Error on init/folder selection if the path points to V Enhanced:
FiveM, Launcher
**Platforms:** …
=> tweak(client/launcher): Gen9-specific warnings

code/components/conhost-v2/src/ConsoleHostGui.cpp
Adds the ability to adjust the vertical height of the F8 console.
I’ve occasionally encountered situations where the output in the console exceeded the default visible area, requiring me to scroll up and down, which felt a bit inconvenient. This change improves quality of life by allowing users to expand the console height as needed, making it easier to view large outputs without excessive scrolling.
https://github.com/user-attachments/assets/66a2bcd4-f6be-4a6c-9530-6508669960cc
The `ImGuiWindowFlags_NoResize` flag has been removed, enabling users to manually resize the console. Additionally, `SetNextWindowSize` is now configured to apply only on the first use by using the `ImGuiCond_FirstUseEver` condition. Height limits have been configured: the minimum height is set to half of the …
=> feat(conhost): allow console vertical resizing

ext/native-decls/GetEntityAddress.md
=> fix(native-decls): typo in GetEntityAddress

code/components/gta-core-five/src/CrashFixes.ValidatePedComponents.cpp
Re-allows empty head drawbls on a peds head component.
Introduces a ConVar to allow toggling null-drawbl checks for the head component.
FiveM
resolves: #3510
resolves: #3449
=> tweak(core/five): allow empty head drawbl ConVar
